/* WILDCRAFT — original voxel sandbox. Three.js is bundled under MIT. */
'use strict';
(() => {
const $ = id => document.getElementById(id);
const W=96,H=48,D=96,C=16,SEA=12,SAVE_KEY='wildcraft.world.v1';
const TYPES=[null,
 {name:'草ブロック',color:'#6c9650',tile:0,time:.55},
 {name:'土',color:'#897054',tile:2,time:.45},
 {name:'石',color:'#8d9490',tile:3,time:1.7},
 {name:'砂',color:'#d6c797',tile:4,time:.45},
 {name:'原木',color:'#85613c',tile:5,time:1.2},
 {name:'葉',color:'#568849',tile:7,time:.3},
 {name:'木材',color:'#bd9460',tile:8,time:.7},
 {name:'石炭鉱石',color:'#4f5751',tile:9,time:2.1},
 {name:'鉄鉱石',color:'#b6977e',tile:10,time:2.5},
 {name:'ガラス',color:'#b5dfd4',tile:11,time:.4},
 {name:'レンガ',color:'#ac7160',tile:12,time:1.3},
 {name:'作業台',color:'#ab7d47',tile:13,time:.8},
 {name:'松明',color:'#f6c76c',tile:14,time:.15},
 {name:'雪',color:'#e4eee3',tile:15,time:.4},
 {name:'岩盤',color:'#3d4544',tile:16,time:Infinity},
 {name:'かまど',color:'#717b74',tile:17,time:1.9}
];
const ITEMS={stick:{name:'棒',icon:'╱'},coal:{name:'石炭',icon:'◆'},iron:{name:'鉄インゴット',icon:'▰'},apple:{name:'りんご',icon:'🍎'},woodpick:{name:'木のツルハシ',icon:'⛏'},stonepick:{name:'石のツルハシ',icon:'⛏'},ironpick:{name:'鉄のツルハシ',icon:'⛏'}};
const RECIPES=[
 {out:7,n:4,cost:{5:1}}, {out:'stick',n:4,cost:{7:2}}, {out:12,n:1,cost:{7:4}},
 {out:'woodpick',n:1,cost:{7:3,stick:2},bench:true}, {out:'stonepick',n:1,cost:{3:3,stick:2},bench:true},
 {out:16,n:1,cost:{3:8},bench:true}, {out:'iron',n:1,cost:{9:1,coal:1},furnace:true},
 {out:'ironpick',n:1,cost:{iron:3,stick:2},bench:true}, {out:13,n:4,cost:{coal:1,stick:1}},
 {out:10,n:4,cost:{4:4,coal:1},furnace:true}, {out:11,n:4,cost:{3:4,2:2},furnace:true}
];
let seed=8271,mode='survival',world=new Uint8Array(W*H*D),chunks=new Map(),edits={},inventory={},hotbar=[1,2,3,5,7,4,12,13,'apple'],selected=0;
let started=false,paused=true,screen='landing',flying=false,health=20,hunger=20,dayTime=.32,days=1,playTime=0,autoSave=0,hungerClock=0;
let yaw=0,pitch=0,vy=0,grounded=false,target=null,breakProgress=0,breakKey='',mining=false,questStage=0,gathered=0,placed=0;
let sound=true,audioCtx,toastTimer,meshes=[],animals=[],monsters=[],particles=[],keys={},lastTime=0,lastHud=0,stepClock=0;
const player=new THREE.Vector3(48,25,50),spawn=new THREE.Vector3();
let renderer;
try{renderer=new THREE.WebGLRenderer({canvas:$('world'),antialias:true,alpha:false,powerPreference:'high-performance'});}catch(e){$('loading').innerHTML='<b>3D描画を開始できませんでした。WebGL対応ブラウザで開いてください。</b>';return;}
renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.setSize(innerWidth,innerHeight);renderer.outputEncoding=THREE.sRGBEncoding;
const scene=new THREE.Scene();scene.background=new THREE.Color('#a9c9bd');scene.fog=new THREE.Fog('#a9c9bd',32,105);
const camera=new THREE.PerspectiveCamera(67,innerWidth/innerHeight,.08,180);camera.rotation.order='YXZ';
const hemi=new THREE.HemisphereLight(0xe7f4e3,0x687151,.85);scene.add(hemi);
const sunLight=new THREE.DirectionalLight(0xffedc1,.8);sunLight.position.set(35,65,25);scene.add(sunLight);
const sun=new THREE.Mesh(new THREE.BoxGeometry(5,5,.5),new THREE.MeshBasicMaterial({color:0xffedb8}));scene.add(sun);
const moon=new THREE.Mesh(new THREE.BoxGeometry(3,3,.5),new THREE.MeshBasicMaterial({color:0xd9ebeb}));scene.add(moon);
const cloudGroup=new THREE.Group();scene.add(cloudGroup);
for(let i=0;i<24;i++){const m=new THREE.Mesh(new THREE.BoxGeometry(8+(i*7%11),1.1,3+i%4),new THREE.MeshLambertMaterial({color:0xf3f3df,transparent:true,opacity:.82}));m.position.set((i*31)%130-15,36+(i%3)*2,(i*53)%130-15);cloudGroup.add(m);}
const water=new THREE.Mesh(new THREE.PlaneGeometry(W,D),new THREE.MeshPhongMaterial({color:0x67a69e,transparent:true,opacity:.68,shininess:65,depthWrite:false,side:THREE.DoubleSide}));water.rotation.x=-Math.PI/2;water.position.set(W/2,SEA+.12,D/2);scene.add(water);
const outline=new THREE.LineSegments(new THREE.EdgesGeometry(new THREE.BoxGeometry(1.012,1.012,1.012)),new THREE.LineBasicMaterial({color:0xf0ffd3,transparent:true,opacity:.9}));outline.visible=false;scene.add(outline);
const torchLight=new THREE.PointLight(0xffbe68,0,13,2);scene.add(torchLight);
const hand=new THREE.Group();camera.add(hand);scene.add(camera);hand.position.set(.46,-.43,-.7);hand.rotation.set(-.15,-.3,.12);
cube(.19,.33,.2,0xcba780,0,0,0,hand);cube(.2,.3,.21,0x526c51,0,-.25,0,hand);
const heldBlock=new THREE.Mesh(new THREE.BoxGeometry(.25,.25,.25),new THREE.MeshLambertMaterial({color:0xc29c68}));heldBlock.position.set(0,.22,-.04);hand.add(heldBlock);hand.visible=false;
const idx=(x,y,z)=>(x*D+z)*H+y;
const inside=(x,y,z)=>x>=0&&z>=0&&y>=0&&x<W&&z<D&&y<H;
const get=(x,y,z)=>inside(x,y,z)?world[idx(x,y,z)]:0;
const hash=(x,z,s=seed)=>{let n=Math.imul(x^s,374761393)+Math.imul(z,668265263);n=Math.imul(n^(n>>>13),1274126177);return((n^(n>>>16))>>>0)/4294967295;};
const smooth=t=>t*t*(3-2*t);
function noise(x,z,scale){x/=scale;z/=scale;const a=Math.floor(x),b=Math.floor(z),u=smooth(x-a),v=smooth(z-b);return THREE.MathUtils.lerp(THREE.MathUtils.lerp(hash(a,b),hash(a+1,b),u),THREE.MathUtils.lerp(hash(a,b+1),hash(a+1,b+1),u),v);}
const heightAt=(x,z)=>Math.floor(8+noise(x,z,28)*13+noise(x,z,10)*5+noise(x,z,4)*1.6);
function topAt(x,z){for(let y=H-1;y>=0;y--)if(get(x,y,z)&&get(x,y,z)!==6)return y+1;return SEA+1;}
const name=id=>TYPES[id]?.name||ITEMS[id]?.name||'空きスロット';
const count=id=>inventory[id]||0;
function toast(msg){$('toast').textContent=msg;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),3000);}
function beep(freq=330,len=.08,type='triangle',volume=.055){if(!sound)return;try{audioCtx ||= new(window.AudioContext||window.webkitAudioContext)();audioCtx.resume();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=type;o.frequency.setValueAtTime(freq,audioCtx.currentTime);o.frequency.exponentialRampToValueAtTime(freq*.55,audioCtx.currentTime+len);g.gain.setValueAtTime(volume,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+len);o.connect(g);g.connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+len);}catch{}}
// Each tile is drawn locally, so the game has no external asset dependency.
const atlas=document.createElement('canvas');atlas.width=128;atlas.height=64;const ac=atlas.getContext('2d'),tileURLs=[];
const palette=['#7c9e54','#8a7350','#8d7155','#929890','#d7c89c','#84603c','#be9860','#568a4c','#bc9560','#8c938b','#90948b','#b1d4cd','#aa7662','#a27a46','#edbb53','#e0e9df','#424b48','#7a837c'];
for(let t=0;t<18;t++){const ox=t%8*16,oy=Math.floor(t/8)*16;ac.fillStyle=palette[t];ac.fillRect(ox,oy,16,16);for(let j=0;j<65;j++){const x=Math.floor(hash(j,t,42)*16),y=Math.floor(hash(t,j,91)*16);ac.fillStyle=j%2?'#ffffff13':'#00000014';ac.fillRect(ox+x,oy+y,1+(j%3),1+(j%2));}if(t===1){ac.fillStyle='#70994c';ac.fillRect(ox,oy,16,4);for(let x=0;x<16;x+=3)ac.fillRect(ox+x,oy+4,2,2+x%3);}if(t===5){ac.fillStyle='#4a392f50';for(let x=1;x<16;x+=4)ac.fillRect(ox+x,oy,1,16);}if(t===6){ac.strokeStyle='#755336';for(let k=1;k<8;k+=2)ac.strokeRect(ox+k,oy+k,16-k*2,16-k*2);}if([8,12,13].includes(t)){ac.strokeStyle='#493d354b';for(let y=0;y<16;y+=4){ac.beginPath();ac.moveTo(ox,oy+y);ac.lineTo(ox+16,oy+y);ac.stroke();ac.fillStyle='#493d354b';ac.fillRect(ox+(y%8?4:11),oy+y,1,4);}}if(t===9||t===10){ac.fillStyle=t===9?'#333b36':'#cba58a';for(let k=0;k<7;k++)ac.fillRect(ox+(k*7%13),oy+(k*11%13),3,2);}if(t===11){ac.strokeStyle='#e3f3df';ac.strokeRect(ox+.5,oy+.5,15,15);ac.fillStyle='#e6f1e366';ac.fillRect(ox+3,oy+3,2,6);}if(t===14){ac.fillStyle='#754d30';ac.fillRect(ox,oy+7,16,9);ac.fillStyle='#ffed9a';ac.fillRect(ox+3,oy,10,7);}if(t===17){ac.fillStyle='#303e37';ac.fillRect(ox+3,oy+6,10,7);ac.fillStyle='#ba8150';ac.fillRect(ox+5,oy+10,6,2);}const mini=document.createElement('canvas');mini.width=16;mini.height=16;mini.getContext('2d').drawImage(atlas,ox,oy,16,16,0,0,16,16);tileURLs[t]=mini.toDataURL();}
const texture=new THREE.CanvasTexture(atlas);texture.magFilter=THREE.NearestFilter;texture.minFilter=THREE.NearestFilter;texture.encoding=THREE.sRGBEncoding;
const blockMaterial=new THREE.MeshLambertMaterial({map:texture,vertexColors:true});
const faces=[{n:[1,0,0],v:[[1,0,1],[1,0,0],[1,1,0],[1,1,1]],shade:.84},{n:[-1,0,0],v:[[0,0,0],[0,0,1],[0,1,1],[0,1,0]],shade:.69},{n:[0,1,0],v:[[0,1,1],[1,1,1],[1,1,0],[0,1,0]],shade:1},{n:[0,-1,0],v:[[0,0,0],[1,0,0],[1,0,1],[0,0,1]],shade:.5},{n:[0,0,1],v:[[0,0,1],[1,0,1],[1,1,1],[0,1,1]],shade:.9},{n:[0,0,-1],v:[[1,0,0],[0,0,0],[0,1,0],[1,1,0]],shade:.75}];
function buildChunk(cx,cz){const key=cx+','+cz,old=chunks.get(key);if(old){scene.remove(old);old.geometry.dispose();}const p=[],n=[],uv=[],col=[],inds=[];for(let x=cx*C;x<Math.min(W,(cx+1)*C);x++)for(let z=cz*C;z<Math.min(D,(cz+1)*C);z++)for(let y=0;y<H;y++){const id=get(x,y,z);if(!id)continue;for(let f=0;f<6;f++){const face=faces[f],nn=face.n;if(get(x+nn[0],y+nn[1],z+nn[2]))continue;let tile=TYPES[id].tile;if(id===1)tile=f===2?0:f===3?2:1;if(id===5&&f>=2&&f<=3)tile=6;const u=tile%8/8,v=1-Math.floor(tile/8)/4,eps=.0007,base=p.length/3;const shade=face.shade*(.94+hash(x+y,z,71)*.06);for(let k=0;k<4;k++){p.push(x+face.v[k][0],y+face.v[k][1],z+face.v[k][2]);n.push(...nn);col.push(shade,shade,shade);}uv.push(u+eps,v-.25+eps,u+.125-eps,v-.25+eps,u+.125-eps,v-eps,u+eps,v-eps);inds.push(base,base+1,base+2,base,base+2,base+3);}}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(p,3));g.setAttribute('normal',new THREE.Float32BufferAttribute(n,3));g.setAttribute('uv',new THREE.Float32BufferAttribute(uv,2));g.setAttribute('color',new THREE.Float32BufferAttribute(col,3));g.setIndex(inds);g.computeBoundingSphere();const mesh=new THREE.Mesh(g,blockMaterial);scene.add(mesh);chunks.set(key,mesh);}
function setBlock(x,y,z,id){if(!inside(x,y,z))return;world[idx(x,y,z)]=id;edits[idx(x,y,z)]=id;const affected=new Set();for(const [a,b]of[[x,z],[x-1,z],[x+1,z],[x,z-1],[x,z+1]])if(a>=0&&b>=0&&a<W&&b<D)affected.add(Math.floor(a/C)+','+Math.floor(b/C));for(const s of affected)buildChunk(...s.split(',').map(Number));}
function generate(){world.fill(0);for(let x=0;x<W;x++)for(let z=0;z<D;z++){const h=heightAt(x,z);for(let y=0;y<h;y++){let id=y===0?15:y<h-4?3:y<h-1?2:h<=SEA+1?4:h>23?14:1;if(y>2&&y<h-5&&Math.sin(x*.23+y*.65)*Math.cos(z*.22-y*.31)>.84)continue;if(id===3&&hash(x+y*23,z,seed)>.966)id=y<11?9:8;world[idx(x,y,z)]=id;}}
for(let x=3;x<W-3;x++)for(let z=3;z<D-3;z++){const y=heightAt(x,z);if(y<SEA+3||y>24||hash(x,z,seed+9)<.979||Math.hypot(x-48,z-48)<5)continue;const th=4+Math.floor(hash(z,x)*3);for(let k=0;k<th;k++)world[idx(x,y+k,z)]=5;for(let dx=-2;dx<=2;dx++)for(let dz=-2;dz<=2;dz++)for(let dy=-2;dy<=1;dy++){if(Math.abs(dx)+Math.abs(dz)+Math.max(0,dy)>4)continue;const i=idx(x+dx,y+th+dy,z+dz);if(!world[i])world[i]=6;}}
for(const [k,v]of Object.entries(edits))world[Number(k)]=v;
for(let x=0;x<W/C;x++)for(let z=0;z<D/C;z++)buildChunk(x,z);
let sx=48,sz=48;for(let r=0;r<30;r++){if(heightAt(sx,sz)>SEA+2)break;sx=48+r%12;sz=48+Math.floor(r/12)*5;}spawn.set(sx+.5,topAt(sx,sz)+.05,sz+.5);player.copy(spawn);createAnimals();}
function cube(w,h,d,color,x,y,z,parent){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),new THREE.MeshLambertMaterial({color}));m.position.set(x,y,z);parent.add(m);return m;}
function createAnimals(){for(const a of [...animals,...monsters])disposeCreature(a);animals=[];monsters=[];for(let i=0;i<14;i++){const x=15+hash(i,17)*66,z=15+hash(i,25)*66;if(heightAt(x|0,z|0)<=SEA+1)continue;const group=new THREE.Group(),sheep=i%3!==0;cube(.75,.58,1.05,sheep?0xe4e3cc:0xdcb09b,0,.73,0,group);cube(.43,.44,.48,sheep?0xb9ad8d:0xe8b6a7,0,.81,-.63,group);for(const dx of[-.23,.23])for(const dz of[-.33,.33])cube(.15,.44,.15,0x82785f,dx,.24,dz,group);for(const dx of[-.15,.15])cube(.06,.065,.025,0x2b3730,dx,.88,-.88,group);group.position.set(x,topAt(x|0,z|0),z);scene.add(group);animals.push({group,dir:hash(i,34)*6.28,timer:0,base:0,kind:'animal'});}}
function disposeCreature(a){scene.remove(a.group);a.group.traverse(o=>{if(o.isMesh){o.geometry.dispose();o.material.dispose();}});}
function spawnMonster(){if(monsters.length>=5)return;const ang=Math.random()*6.28,x=Math.floor(player.x+Math.sin(ang)*19),z=Math.floor(player.z+Math.cos(ang)*19);if(x<2||z<2||x>W-3||z>D-3||topAt(x,z)<SEA)return;const group=new THREE.Group();cube(.6,.7,.35,0x445c4a,0,.85,0,group);cube(.48,.5,.45,0x7f9c68,0,1.47,0,group);for(const x of[-.15,.15]){cube(.2,.5,.25,0x303f3c,x,.3,0,group);cube(.08,.06,.02,0xe9ce79,x,1.52,-.24,group);}scene.add(group);group.position.set(x+.5,topAt(x,z),z+.5);monsters.push({group,hp:3,cooldown:0,kind:'monster'});}
function icon(id){if(TYPES[id])return '<span class="block-icon" style="background:'+TYPES[id].color+' url('+tileURLs[TYPES[id].tile]+');background-size:100% 100%"></span>';return '<span class="item-icon">'+(ITEMS[id]?.icon||'')+'</span>';}
function refreshUI(){const creative=mode==='creative';$('hotbar').innerHTML=hotbar.map((id,i)=>'<button class="slot '+(i===selected?'active':'')+'" data-slot="'+i+'" title="'+name(id)+'">'+icon(id)+'<span class="num">'+(i+1)+'</span><span class="count">'+(creative&&TYPES[id]?'∞':count(id)||'')+'</span></button>').join('');$('held-name').textContent=name(hotbar[selected]);$('health').textContent=creative?'CREATIVE MODE':Array.from({length:10},(_,i)=>health>i*2?'♥':'♡').join(' ');$('hunger').textContent=creative?'∞':Array.from({length:10},(_,i)=>hunger>i*2?'◆':'◇').join(' ');$('fly-hint').hidden=!creative;$('world-label').textContent=creative?'クリエイティブ':'サバイバル';const item=hotbar[selected];heldBlock.visible=!!TYPES[item]&&(creative||count(item)>0);if(TYPES[item])heldBlock.material.color.set(TYPES[item].color);if(screen==='inventory')renderInventory();}
function nearBlock(id){const x=Math.floor(player.x),y=Math.floor(player.y),z=Math.floor(player.z);for(let a=-4;a<=4;a++)for(let b=-3;b<=3;b++)for(let c=-4;c<=4;c++)if(get(x+a,y+b,z+c)===id)return true;return false;}
function recipeAvailable(r){return(!r.bench||nearBlock(12))&&(!r.furnace||nearBlock(16))&&Object.entries(r.cost).every(([id,n])=>count(id)>=n);}
function renderInventory(){const ids=mode==='creative'?[...TYPES.keys()].slice(1).filter(i=>i!==15).concat(Object.keys(ITEMS)):Object.keys(inventory).filter(id=>count(id)>0);$('bag').innerHTML=ids.map(id=>'<button class="slot" data-item="'+id+'" title="'+name(id)+'">'+icon(id)+'<span class="count">'+(mode==='creative'?'∞':count(id))+'</span></button>').join('')||'<p class="subtle">まずは木を切って、原木を集めよう。</p>';$('inventory-mode').textContent=mode==='creative'?'すべての素材':'集めた素材';const tool=count('ironpick')?'鉄':count('stonepick')?'石':count('woodpick')?'木':null;$('equipment').textContent='⛏ '+(tool?tool+'のツルハシ装備中（自動使用）':'素手 · 原木からツルハシをつくろう');$('recipes').innerHTML=RECIPES.map((r,i)=>'<button class="recipe" data-recipe="'+i+'" '+(!recipeAvailable(r)?'disabled':'')+'>'+icon(r.out)+'<div><strong>'+name(r.out)+' × '+r.n+'</strong><small>'+Object.entries(r.cost).map(([id,n])=>name(id)+' '+count(id)+'/'+n).join(' · ')+(r.bench?' / 近くに作業台':r.furnace?' / 近くにかまど':'')+'</small></div><span>＋</span></button>').join('');}
function craft(i){const r=RECIPES[i];if(!r||!recipeAvailable(r))return;for(const [id,n]of Object.entries(r.cost))inventory[id]-=n;inventory[r.out]=count(r.out)+r.n;beep(600,.14);toast(name(r.out)+' × '+r.n+' をつくった');if(r.out==='woodpick'&&questStage===1)questStage=2;refreshUI();updateQuest();}
function addItem(id,n=1){inventory[id]=count(id)+n;refreshUI();}
function updateQuest(){if(gathered>=3&&questStage===0)questStage=1;if(placed>=12&&questStage===2)questStage=3;const quests=[['森からはじまる暮らし','原木を3個集めよう',Math.min(gathered,3)+' / 3'],['はじめての道具','作業台を置いて木のツルハシをつくろう','E → クラフト'],['あなただけの居場所','ブロックを12個置いて拠点をつくろう',Math.min(placed,12)+' / 12'],['冒険はつづく','地下の鉄鉱石を探して、自由に建築しよう','✓']];const q=quests[questStage]||quests[3];$('quest-title').textContent=q[0];$('quest-text').innerHTML=q[1]+' <em>'+q[2]+'</em>';$('quest').hidden=mode==='creative';}
function saveWorld(quiet=false){if(!started)return false;try{localStorage.setItem(SAVE_KEY,JSON.stringify({version:1,seed,mode,edits,inventory,hotbar,selected,player:player.toArray(),yaw,pitch,health,hunger,dayTime,days,playTime,questStage,gathered,placed}));$('continue').hidden=false;$('save-status').textContent='保存済み · '+new Date().toLocaleTimeString('ja-JP');if(!quiet)toast('世界を保存しました');return true;}catch{toast('保存できませんでした。ブラウザの保存容量・設定を確認してください。');return false;}}
function validSave(s){return s&&s.version===1&&Number.isInteger(s.seed)&&['survival','creative'].includes(s.mode)&&s.edits&&typeof s.edits==='object'&&Object.entries(s.edits).every(([i,v])=>Number.isInteger(+i)&&+i>=0&&+i<world.length&&Number.isInteger(v)&&v>=0&&v<TYPES.length)&&s.inventory&&typeof s.inventory==='object'&&Object.entries(s.inventory).every(([id,n])=>(TYPES[id]||ITEMS[id])&&Number.isFinite(n)&&n>=0)&&Array.isArray(s.hotbar)&&s.hotbar.length===9&&s.hotbar.every(id=>TYPES[id]||ITEMS[id])&&Array.isArray(s.player)&&s.player.length===3&&s.player.every(Number.isFinite)&&s.player[0]>=.3&&s.player[0]<=W-.3&&s.player[2]>=.3&&s.player[2]<=D-.3&&s.player[1]>=0&&s.player[1]<=H+15&&[s.yaw,s.pitch,s.health,s.hunger,s.dayTime,s.days,s.playTime,s.questStage,s.gathered,s.placed,s.selected].every(Number.isFinite)&&s.selected>=0&&s.selected<9&&s.questStage>=0&&s.questStage<=3;}
function begin(load=false){let s;try{if(load){s=JSON.parse(localStorage.getItem(SAVE_KEY));if(!validSave(s))throw Error('invalid');}}catch{toast('セーブデータを読み込めませんでした');return;}
let existing=false;try{existing=!!localStorage.getItem(SAVE_KEY);}catch{}if(!load&&existing&&!confirm('新しい世界をつくると、現在のセーブを上書きします。つくりますか？'))return;
$('loading').hidden=false;setTimeout(()=>{try{seed=s?.seed??Array.from($('seed').value||'wildwood').reduce((a,c)=>(Math.imul(a,31)+c.charCodeAt(0))|0,7);mode=s?.mode??mode;edits=s?.edits??{};inventory=s?.inventory??{apple:5};hotbar=s?.hotbar??[1,2,3,5,7,4,12,13,'apple'];selected=s?.selected??3;health=s?.health??20;hunger=s?.hunger??20;dayTime=s?.dayTime??.32;days=s?.days??1;playTime=s?.playTime??0;questStage=s?.questStage??0;gathered=s?.gathered??0;placed=s?.placed??0;generate();if(s)player.fromArray(s.player);yaw=s?.yaw??-.45;pitch=s?.pitch??-.05;vy=0;flying=false;started=true;$('landing').hidden=true;$('hud').hidden=false;document.body.classList.add('playing');refreshUI();updateQuest();$('loading').hidden=true;screen='pause';paused=true;$('pause').hidden=false;resume();toast(mode==='creative'?'自由につくろう。Eで素材一覧、Fで空へ。':'木を見つけたら、左クリック長押しで採掘。');}catch(e){$('loading').hidden=true;toast('世界の生成に失敗しました：'+e.message);}},40);}
function clearInput(){keys={};mining=false;breakProgress=0;}
function pause(which='pause'){if(!started||screen==='death')return;paused=true;screen=which;clearInput();document.exitPointerLock?.();$('pause').hidden=which!=='pause';$('inventory').hidden=which!=='inventory';if(which==='inventory')renderInventory();}
function resume(){if(!started)return;$('pause').hidden=true;$('inventory').hidden=true;if(health<=0&&mode==='survival'){screen='death';paused=true;$('death').hidden=false;return;}$('death').hidden=true;screen='game';paused=false;clearInput();if(!matchMedia('(pointer:coarse)').matches){try{const p=$('world').requestPointerLock();p?.catch(()=>toast('マウスを動かすだけで視点を操作できます'));}catch{toast('マウスを動かすだけで視点を操作できます');}}}
function collision(pos){if(pos.x<.3||pos.z<.3||pos.x>W-.3||pos.z>D-.3||pos.y<0||pos.y>H+12)return true;for(let x=Math.floor(pos.x-.29);x<=Math.floor(pos.x+.29);x++)for(let y=Math.floor(pos.y+.015);y<=Math.floor(pos.y+1.72);y++)for(let z=Math.floor(pos.z-.29);z<=Math.floor(pos.z+.29);z++)if(get(x,y,z))return true;return false;}
function moveAxis(axis,amount){const steps=Math.max(1,Math.ceil(Math.abs(amount)/.15)),d=amount/steps;for(let i=0;i<steps;i++){player[axis]+=d;if(collision(player)){player[axis]-=d;return false;}}return true;}
function updatePlayer(dt){let forward=(keys.KeyW||keys.ArrowUp?1:0)-(keys.KeyS||keys.ArrowDown?1:0),right=(keys.KeyD||keys.ArrowRight?1:0)-(keys.KeyA||keys.ArrowLeft?1:0);const len=Math.hypot(forward,right)||1;forward/=len;right/=len;const wet=player.y<SEA+.12&&!get(Math.floor(player.x),SEA,Math.floor(player.z));const sprint=keys.ShiftLeft||keys.ShiftRight,speed=flying?10:wet?2.5:sprint&&hunger>4?6.4:4.2;
moveAxis('x',(-Math.sin(yaw)*forward+Math.cos(yaw)*right)*speed*dt);moveAxis('z',(-Math.cos(yaw)*forward-Math.sin(yaw)*right)*speed*dt);
if(flying){vy=0;moveAxis('y',((keys.Space?1:0)-(sprint?1:0))*7*dt);}else{if(keys.Space&&(grounded||wet)){vy=wet?4.1:7.5;grounded=false;}vy-=dt*(wet?6:23);vy=Math.max(vy,wet?-3:-28);const falling=vy;if(!moveAxis('y',vy*dt)){if(vy<0){if(!grounded&&falling<-12&&!wet)damage(Math.floor((-falling-11)*.9));grounded=true;}vy=0;}else grounded=false;}
if((forward||right)&&grounded){stepClock+=dt;if(stepClock>.42){stepClock=0;beep(100+Math.random()*30,.035,'triangle',.018);}}camera.position.copy(player).add(new THREE.Vector3(0,1.58,0));if(forward||right)camera.position.y+=Math.sin(playTime*11)*.022;camera.rotation.set(pitch,yaw,0);const underwater=camera.position.y<SEA+.1;scene.fog.near=underwater?0:32;scene.fog.far=underwater?14:105;if(underwater)scene.fog.color.set('#467f79');}
function rayVoxel(origin,dir,max=6){let x=Math.floor(origin.x),y=Math.floor(origin.y),z=Math.floor(origin.z),prev={x,y,z},dist=0;const sx=Math.sign(dir.x)||1,sy=Math.sign(dir.y)||1,sz=Math.sign(dir.z)||1,dx=Math.abs(1/dir.x),dy=Math.abs(1/dir.y),dz=Math.abs(1/dir.z);let tx=dir.x===0?Infinity:(dir.x>0?x+1-origin.x:origin.x-x)*dx,ty=dir.y===0?Infinity:(dir.y>0?y+1-origin.y:origin.y-y)*dy,tz=dir.z===0?Infinity:(dir.z>0?z+1-origin.z:origin.z-z)*dz;while(dist<max){const id=get(x,y,z);if(id)return{x,y,z,id,prev,dist};prev={x,y,z};if(tx<ty&&tx<tz){x+=sx;dist=tx;tx+=dx;}else if(ty<tz){y+=sy;dist=ty;ty+=dy;}else{z+=sz;dist=tz;tz+=dz;}}return null;}
function pickLevel(){return count('ironpick')?3:count('stonepick')?2:count('woodpick')?1:0;}
function burst(x,y,z,id){for(let i=0;i<9;i++){const m=new THREE.Mesh(new THREE.BoxGeometry(.09,.09,.09),new THREE.MeshBasicMaterial({color:TYPES[id].color}));m.position.set(x+.5,y+.5,z+.5);scene.add(m);particles.push({m,v:new THREE.Vector3((Math.random()-.5)*3,Math.random()*3,(Math.random()-.5)*3),life:.55});}}
function mineBlock(hit){const{x,y,z,id}=hit;if(id===15)return;setBlock(x,y,z,0);burst(x,y,z,id);beep(id===5?165:280,.07,'square',.025);if(mode==='survival'){const tool=pickLevel();if([3,8,9,16].includes(id)&&tool===0){toast('石・鉱石の回収にはツルハシが必要です');}else if(id===9&&tool<2){toast('鉄鉱石の回収には石以上のツルハシが必要です');}else{addItem(id===8?'coal':id);if(id===5)gathered++;if(id===6&&Math.random()<.25)addItem('apple');}}updateQuest();}
function updateTarget(dt){target=rayVoxel(camera.position,camera.getWorldDirection(new THREE.Vector3()),mode==='creative'?9:6);outline.visible=!!target;if(target){outline.position.set(target.x+.5,target.y+.5,target.z+.5);$('target-name').textContent=name(target.id);}else $('target-name').textContent='';if(mining&&target){const k=target.x+','+target.y+','+target.z;if(k!==breakKey){breakProgress=0;breakKey=k;}const hard=[3,8,9,16].includes(target.id),duration=mode==='creative'?.12:TYPES[target.id].time/(hard?(pickLevel()?1+pickLevel()*1.8:.7):1);breakProgress+=dt/duration;$('mining').style.opacity=1;$('mining').firstElementChild.style.width=Math.min(100,breakProgress*100)+'%';outline.scale.setScalar(1+Math.sin(breakProgress*35)*.014);if(breakProgress>=1){mineBlock(target);breakProgress=0;}}else{breakProgress=0;$('mining').style.opacity=0;outline.scale.setScalar(1);}}
function placeBlock(){if(paused)return;target=rayVoxel(camera.position,camera.getWorldDirection(new THREE.Vector3()),mode==='creative'?9:6);if(!target)return;const id=hotbar[selected];if(!TYPES[id]){if(id==='apple')eat();return;}if(mode!=='creative'&&!count(id)){toast(name(id)+'を持っていません');return;}const{x,y,z}=target.prev;if(!inside(x,y,z)||get(x,y,z))return;world[idx(x,y,z)]=id;const overlap=collision(player);world[idx(x,y,z)]=0;if(overlap){toast('自分に重なる場所には置けません');return;}setBlock(x,y,z,id);if(mode!=='creative')inventory[id]--;placed++;beep(220,.055);refreshUI();updateQuest();}
function eat(){if(count('apple')<=0){toast('りんごを持っていません。木の葉から見つかります。');return;}if(hunger>=20&&health>=20){toast('おなかはいっぱいです');return;}inventory.apple--;hunger=Math.min(20,hunger+6);health=Math.min(20,health+2);beep(520,.12);toast('りんごを食べた · 満腹度 +6');refreshUI();}
function damage(n){if(mode==='creative'||paused||n<=0)return;health=Math.max(0,health-n);beep(90,.17,'sawtooth',.045);refreshUI();if(health===0){paused=true;screen='death';clearInput();document.exitPointerLock?.();$('death').hidden=false;}}
function attack(){const direction=camera.getWorldDirection(new THREE.Vector3());for(const m of monsters){const delta=m.group.position.clone().add(new THREE.Vector3(0,1,0)).sub(camera.position),distance=delta.length();if(distance<3.5&&delta.normalize().dot(direction)>.9&&(!target||target.dist>distance-.5)){m.hp-=pickLevel()?2:1;beep(120,.1,'sawtooth');if(m.hp<=0){disposeCreature(m);monsters=monsters.filter(v=>v!==m);addItem('coal');}return true;}}return false;}
function updateCreatures(dt){for(const a of animals){a.timer-=dt;if(a.timer<0){a.timer=2+Math.random()*6;a.dir+=Math.random()*2-1;}const p=a.group.position,x=p.x+Math.sin(a.dir)*dt*.5,z=p.z+Math.cos(a.dir)*dt*.5,y=topAt(x|0,z|0);if(x>2&&z>2&&x<W-2&&z<D-2&&Math.abs(y-p.y)<1.2&&y>SEA){p.set(x,y,z);a.group.rotation.y=a.dir+Math.PI;}else a.dir+=Math.PI*.6;}
const night=dayTime<.2||dayTime>.8;if(night&&mode==='survival'&&Math.random()<dt*.1)spawnMonster();for(const m of [...monsters]){if(!night){disposeCreature(m);monsters=monsters.filter(a=>a!==m);continue;}const p=m.group.position,delta=player.clone().sub(p);delta.y=0;const distance=delta.length();if(distance>1.15&&distance<32){delta.normalize();const x=p.x+delta.x*dt*1.5,z=p.z+delta.z*dt*1.5,y=topAt(x|0,z|0);if(Math.abs(y-p.y)<1.2&&y>=SEA)p.set(x,y,z);m.group.rotation.y=Math.atan2(delta.x,delta.z)+Math.PI;}m.cooldown-=dt;if(distance<1.5&&Math.abs(player.y-p.y)<2&&m.cooldown<=0){damage(2);m.cooldown=1.5;}}
}
function updateSky(dt){const daylight=Math.max(.08,Math.sin((dayTime-.22)*Math.PI*2)*.92+.18),color=new THREE.Color('#182b40').lerp(new THREE.Color('#afc9b7'),daylight);scene.background.copy(color);scene.fog.color.copy(color);hemi.intensity=.3+daylight*.65;sunLight.intensity=daylight*.9;const angle=(dayTime-.25)*Math.PI*2;sun.position.set(48+Math.cos(angle)*65,Math.sin(angle)*65,0);sun.lookAt(camera.position);moon.position.set(48-Math.cos(angle)*65,-Math.sin(angle)*65,0);moon.lookAt(camera.position);sunLight.position.copy(sun.position);cloudGroup.position.x=Math.sin(playTime*.002)*12;water.position.y=SEA+.12+Math.sin(playTime*.7)*.025;torchLight.position.copy(camera.position);torchLight.intensity=hotbar[selected]===13&&(count(13)||mode==='creative')?1.6:0;}
function frame(t){requestAnimationFrame(frame);const dt=Math.min((t-lastTime)/1000,.05)||.016;lastTime=t;if(started&&!paused){playTime+=dt;dayTime+=dt/900;if(dayTime>=1){dayTime-=1;days++;}updateSky(dt);updatePlayer(dt);updateTarget(dt);updateCreatures(dt);autoSave+=dt;if(autoSave>30){saveWorld(true);autoSave=0;}hungerClock+=dt;if(hungerClock>18){hungerClock=0;if(mode==='survival'){hunger=Math.max(0,hunger-1);if(hunger>14)health=Math.min(20,health+1);if(!hunger)damage(1);refreshUI();}}if(t-lastHud>250){lastHud=t;$('position').textContent=[player.x,player.y,player.z].map(Math.floor).join(' / ');$('biome').textContent=player.y<12?'UNDERGROUND':player.y>24?'HIGHLANDS':player.y<SEA+2?'COASTLAND':'GREENWOOD';const h=Math.floor(dayTime*24),m=Math.floor(dayTime*24%1*60);$('clock').textContent='DAY '+String(days).padStart(2,'0')+' · '+String(h).padStart(2,'0')+':'+String(m).padStart(2,'0');}}
else if(!started){const a=t*.000025;camera.position.set(53+Math.sin(a)*5,29,67+Math.cos(a)*4);camera.lookAt(43,16,36);dayTime=.37;updateSky(dt);}
hand.visible=started;hand.rotation.x=-.15+(mining?Math.sin(playTime*18)*.3:0);hand.position.y=-.43+(!paused?Math.sin(playTime*2)*.012:0);
for(let i=particles.length-1;i>=0;i--){const p=particles[i];if(!paused){p.life-=dt;p.v.y-=dt*9;p.m.position.addScaledVector(p.v,dt);}if(p.life<=0){scene.remove(p.m);p.m.geometry.dispose();p.m.material.dispose();particles.splice(i,1);}}renderer.render(scene,camera);}
$('start').onclick=()=>begin();$('continue').onclick=()=>begin(true);$('resume').onclick=resume;$('save').onclick=()=>saveWorld();$('menu-button').onclick=()=>{if(started)pause();};$('brand').onclick=e=>{e.preventDefault();if(started)pause();};$('home').onclick=()=>{if(!saveWorld(true))return;started=false;paused=true;screen='landing';$('pause').hidden=true;$('hud').hidden=true;$('landing').hidden=false;document.body.classList.remove('playing');};$('inventory-button').onclick=()=>pause('inventory');$('close-inventory').onclick=resume;$('respawn').onclick=()=>{player.copy(spawn);health=20;hunger=20;vy=0;refreshUI();resume();};$('sound').onclick=()=>{sound=!sound;$('sound').textContent=sound?'♪':'♩';$('sound').style.opacity=sound?1:.45;};
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;document.querySelectorAll('[data-mode]').forEach(a=>a.classList.toggle('selected',a===b));});
$('hotbar').onclick=e=>{const b=e.target.closest('[data-slot]');if(b){selected=+b.dataset.slot;refreshUI();}};$('bag').onclick=e=>{const b=e.target.closest('[data-item]');if(b){let id=b.dataset.item;id=TYPES[id]?+id:id;hotbar[selected]=id;if(mode==='creative'&&!TYPES[id])inventory[id]=64;refreshUI();toast(name(id)+'をスロット '+(selected+1)+' に装備');}};$('recipes').onclick=e=>{const b=e.target.closest('[data-recipe]');if(b)craft(+b.dataset.recipe);};
document.addEventListener('keydown',e=>{if(e.target instanceof HTMLInputElement)return;if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Tab'].includes(e.code))e.preventDefault();if(e.repeat&&(e.code==='KeyE'||e.code==='KeyF'))return;if(e.code==='KeyE'&&started&&screen!=='death'){screen==='inventory'?resume():pause('inventory');return;}if(e.code==='Escape'&&started){if(screen==='inventory')pause();else if(screen==='game')pause();return;}if(paused)return;keys[e.code]=true;if(/^Digit[1-9]$/.test(e.code)){selected=+e.code.slice(-1)-1;refreshUI();}if(e.code==='KeyF'&&mode==='creative'){flying=!flying;vy=0;toast(flying?'飛行モード ON':'飛行モード OFF');}if(e.code==='KeyQ')eat();});document.addEventListener('keyup',e=>{delete keys[e.code];});
document.addEventListener('pointerlockchange',()=>{if(!document.pointerLockElement&&screen==='game'&&!matchMedia('(pointer:coarse)').matches)pause();});
let touchId=null,tx=0,ty=0;
$('world').addEventListener('pointerdown',e=>{if(paused)return;if(e.pointerType==='touch'){touchId=e.pointerId;tx=e.clientX;ty=e.clientY;return;}if(e.button===0&&!attack())mining=true;if(e.button===2)placeBlock();});window.addEventListener('pointerup',e=>{mining=false;if(e.pointerId===touchId)touchId=null;});
window.addEventListener('pointermove',e=>{if(paused)return;let dx=0,dy=0,sensitivity=.0048;if(e.pointerId===touchId){dx=e.clientX-tx;dy=e.clientY-ty;tx=e.clientX;ty=e.clientY;sensitivity=.0024;}else if(e.pointerType==='mouse'||document.pointerLockElement){dx=e.movementX;dy=e.movementY;}yaw-=dx*sensitivity;pitch=THREE.MathUtils.clamp(pitch-dy*sensitivity,-1.54,1.54);});$('world').addEventListener('contextmenu',e=>e.preventDefault());$('world').addEventListener('wheel',e=>{if(paused)return;e.preventDefault();selected=(selected+(e.deltaY>0?1:8))%9;refreshUI();},{passive:false});
document.querySelectorAll('[data-key]').forEach(b=>{b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);keys[b.dataset.key]=true;});const release=()=>delete keys[b.dataset.key];b.addEventListener('pointerup',release);b.addEventListener('pointercancel',release);});$('touch-break').addEventListener('pointerdown',e=>{e.preventDefault();if(!attack())mining=true;});$('touch-place').onclick=placeBlock;
window.addEventListener('blur',()=>{if(started&&screen==='game')pause();clearInput();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&started){saveWorld(true);if(screen==='game')pause();}});window.addEventListener('beforeunload',()=>saveWorld(true));window.addEventListener('resize',()=>{renderer.setSize(innerWidth,innerHeight);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();});
try{$('continue').hidden=!localStorage.getItem(SAVE_KEY);}catch{}
// Read-only diagnostics are useful when checking a world without altering play state.
window.Wildcraft={getState:()=>({started,paused,screen,mode,seed,position:player.toArray(),health,hunger,dayTime,days,inventory:{...inventory},selected,hotbar:[...hotbar],target,questStage,placed,blockCount:world.reduce((a,b)=>a+!!b,0),chunks:chunks.size,triangles:renderer.info.render.triangles}),getBlock:get};
setTimeout(()=>{generate();$('loading').hidden=true;requestAnimationFrame(frame);},30);
})();
