const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

(async()=>{
 const browser = await chromium.launch({headless:true, executablePath:process.env.CHROME_PATH || '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});
 const output=path.join(__dirname,'artifacts');fs.mkdirSync(output,{recursive:true});
 const page=await browser.newPage({viewport:{width:1440,height:1040},deviceScaleFactor:1});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
 await page.goto('http://127.0.0.1:4178');await page.waitForFunction(()=>[...document.images].every(i=>i.complete));
 await page.screenshot({path:path.join(output,'home-desktop.png'),fullPage:true});
 assert.equal(await page.locator('.mini-unit').count(),6);
 await page.locator('.nav-item[data-action="upgrade"]').click();
 await page.locator('[data-action="level-up"]').click();
 assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('yurumon-march-v1')).levels[1]),2);
 await page.screenshot({path:path.join(output,'upgrade-desktop.png'),fullPage:true});
 await page.locator('.nav-item[data-action="summon"]').click();await page.locator('[data-action="draw"]').click();
 assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('yurumon-march-v1')).gems),60);
 await page.locator('[data-action="close-modal"]').first().click();
 await page.locator('.nav-item[data-action="team"]').click();await page.locator('[data-action="slot"][data-id="0"]').click();await page.locator('[data-action="equip"][data-id="2"]').click();
 assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('yurumon-march-v1')).team[0]),2);
 await page.locator('.nav-item[data-action="map"]').click();await page.screenshot({path:path.join(output,'map-desktop.png'),fullPage:true});
 await page.locator('[data-action="start"]').click();await page.locator('#auto-button').click();await page.locator('#speed-button').click();
 await page.waitForTimeout(7500);await page.screenshot({path:path.join(output,'battle-desktop.png'),fullPage:true});
 await page.locator('[data-action="pause"]').click();const time=await page.locator('#battle-timer').textContent();await page.waitForTimeout(600);assert.equal(await page.locator('#battle-timer').textContent(),time);
 await page.locator('[data-action="resume"]').click();
 await page.locator('.modal').waitFor({state:'visible',timeout:90000});
 assert.match(await page.locator('.modal').innerText(),/よくがんばりました/);
 await page.screenshot({path:path.join(output,'victory-desktop.png'),fullPage:true});
 const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('yurumon-march-v1')));assert.equal(saved.cleared,1);
 await page.reload();assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('yurumon-march-v1')).cleared),1);
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(output,'home-mobile.png'),fullPage:true});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 await page.locator('.nav-item[data-action="map"]').click();await page.locator('[data-action="start"]').click();await page.locator('#auto-button').click();await page.waitForTimeout(1000);
 await page.screenshot({path:path.join(output,'battle-mobile.png'),fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 assert.deepEqual(errors,[]);
 console.log(JSON.stringify({passed:true,checks:['desktop home','level up','summon','party swap','stage map','battle','pause and resume','victory','save reload','390px mobile layout'],errors,saved},null,2));
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1);});
