import {FestivalAnimation} from './festival-animation.js';
const names={'ビートくん':'bird','オオカミ':'wolf','ウサギ':'rabbit','クマ':'bear','キツネ':'fox','ロボット':'robot','ネコ':'cat','カエル':'frog','ゴリラ':'gorilla','ドラゴン':'dragon','宇宙人':'alien','タコ':'octopus','アライグマ':'raccoon','カワウソ':'otter','イヌの司会':'dog','イヌ':'dog'};
export class FestivalArt{
 constructor(){this.images=new Map();this.theme='gold';this.reduceMotion=false;this.animation=new FestivalAnimation();}
 async load(){const res=await fetch('./assets/runtime/art-manifest.json');if(!res.ok)throw Error('絵の素材を読み込めませんでした');this.manifest=await res.json();const files=[...Object.values(this.manifest.characters).flatMap(Object.values),...Object.values(this.manifest.digits).flatMap(Object.values)];await Promise.all([this.animation.load(),...files.map(file=>new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>{this.images.set(file,im);resolve();};im.onerror=reject;im.src='./assets/runtime/'+file;}))]);}
 async prepareStage(game,variant=0,guest){const cast=game.id===20?[game.character,'カエル','クマ','ウサギ','ネコ','ロボット']:game.id===21?[guest||'オオカミ','オオカミ','ウサギ','クマ','キツネ']:[game.character,...(game.id===15?['ビートくん']:[])];await this.animation.prepare(game.slug,variant,[...new Set(cast.map(n=>names[n]||n))]);}
 setStage(game,variant=0){this.animation.setStage(game.slug,variant);}
 setContext(context){this.animation.setContext(context);}
 drawBackdrop(ctx,time){return this.animation.drawBackdrop(ctx,time,this.reduceMotion);}
 drawProp(ctx,x,y,size,time,options={}){return this.animation.drawProp(ctx,x,y,size,time,{...options,reduceMotion:this.reduceMotion});}
 hasProp(){return this.animation.hasProp();}
 drawEffect(ctx,action,x,y,size,time,options={}){return this.animation.drawEffect(ctx,action,x,y,size,time,{...options,reduceMotion:this.reduceMotion});}
 drawShared(ctx,kind,x,y,size,time,options={}){return this.animation.drawShared(ctx,kind,x,y,size,time,{...options,reduceMotion:this.reduceMotion});}
 drawCharacter(ctx,name,x,y,size,state='idle',time=0){const key=names[name]||name||'bird';if(this.animation.drawCharacter(ctx,key,x,y,size,state,time,this.reduceMotion))return;const s=state==='celebrate'?'win':state==='talk'?(Math.floor(time*7)%2?'talk':'idle'):state==='act'?'talk':'idle';const file=this.manifest?.characters[key]?.[s]||this.manifest?.characters.bird?.[s],im=this.images.get(file);if(!im)return;ctx.save();const bob=this.reduceMotion?0:state==='celebrate'?Math.abs(Math.sin(time*10))*size*.08:Math.sin(time*3)*size*.012;ctx.translate(x,y-bob);if(!this.reduceMotion&&state==='act')ctx.rotate(Math.sin(time*8)*.07);const h=size,w=h*im.width/im.height;ctx.drawImage(im,-w/2,-h,w,h);ctx.restore();}
 drawNumber(ctx,value,x,y,size,theme=this.theme){const chars=String(value).split('');const widths=chars.map(c=>{const im=this.images.get(this.manifest?.digits[theme]?.[c]);return im?size*im.width/im.height:size*.55;});let xx=x-widths.reduce((a,b)=>a+b,0)/2;chars.forEach((c,i)=>{const im=this.images.get(this.manifest?.digits[theme]?.[c]);if(/\d/.test(c)&&this.animation.drawDigit(ctx,c,theme,xx,y,size,this.reduceMotion)){}else if(im)ctx.drawImage(im,xx,y-size/2,widths[i],size);else{ctx.save();ctx.fillStyle='#172b46';ctx.font=`900 ${size}px system-ui`;ctx.textAlign='left';ctx.textBaseline='middle';ctx.fillText(c,xx,y);ctx.restore();}xx+=widths[i];});}
 numberElement(value,theme='gold'){const span=document.createElement('span');span.className='art-number';span.setAttribute('aria-label',String(value));for(const c of String(value)){if(/\d/.test(c)){const clip=this.animation.digit(theme,c);if(clip){const digit=document.createElement('span');digit.className='sprite-digit';digit.style.backgroundImage=`url("./assets/runtime/rich/${clip.file}")`;const f=clip.posterFrame??clip.usableFrames?.[0]??0;digit.style.backgroundPosition=`${(f%3)*50}% ${Math.floor(f/3)*100}%`;digit.dataset.frames=JSON.stringify(clip.usableFrames||[0,1,2,3,4,5]);digit.setAttribute('aria-hidden','true');span.append(digit);}else{const im=document.createElement('img');im.src=`./assets/runtime/digit-${theme}-${c}.webp`;im.alt='';span.append(im);}}else span.append(c);}return span;}
}
