import {GAMES,createMiniGame} from './minigames.js';
import {FestivalAudio} from './festival-audio.js';
import {FestivalArt} from './festival-art.js';
import {BEAT,ROUND_BEATS,makePlaylist,grade,summarize,newSave,normalizeSave,record} from './festival-core.js';
const $=id=>document.getElementById(id), audio=new FestivalAudio(), art=new FestivalArt();
const KEY='kuku-beat-festival-v1';let save=newSave(),storageAvailable=true;
try{save=normalizeSave(JSON.parse(localStorage.getItem(KEY)));}catch{storageAvailable=false;}
let playlist=[],results=[],index=0,mini=null,roundStart=0,phase='',running=false,paused=false,watch=false,flags={},streak=0,lastOptions={},token=0,frame=0,allowPortrait=false,wakeLock=null,toastTimer;
let swRegistration=null,cacheStatus=null,offlineManifest=null,previewAudio=null,dialogRequest=0;
let artReady=null;
function ensureArt(){if(!artReady)artReady=art.load().catch(error=>{artReady=null;throw error;});return artReady;}
ensureArt().catch(()=>{});
const ctx=$('stage').getContext('2d');
const musicFor=id=>[1,6,8,17].includes(id)?'jackpot':[2,7,10,13,18].includes(id)?'kitchen':[3,4,12,15].includes(id)?'space':[5,9,16,21].includes(id)?'forest':id===20?'finale':'sports';
const paths=['jackpot','sushi','rocket','ninja','frog','quiz','donuts','gorilla','train','magic','basketball','ghost','socks','hero','aliens','fishing','delivery','octopus','dragon','orchestra','forest'];
const artPath=id=>`./designs/20-minigames/images/${String(id).padStart(2,'0')}-${paths[id-1]}.webp`;
const safeText=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(text){$('toast').textContent=text;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,4500);}
function persist(){try{localStorage.setItem(KEY,JSON.stringify(save));}catch{storageAvailable=false;toast('このブラウザでは記録を保存できません。遊びは続けられます。');}}
function screen(name){for(const id of ['home','play','results'])$(id).hidden=id!==name;document.body.classList.toggle('in-game',name==='play');window.scrollTo(0,0);orientation();}
function openDialog(content){dialogRequest++;$('dialog-content').innerHTML=content;if(!$('dialog').open)$('dialog').showModal();}
function applySettings(){audio.setVolumes(save.settings);art.reduceMotion=save.settings.reduceMotion||matchMedia('(prefers-reduced-motion: reduce)').matches;document.body.classList.toggle('reduced',art.reduceMotion);}
function refreshHome(){
 $('home-record').textContent=save.plays?`${save.plays}回あそんだね！ ★ ${Object.values(save.stars).reduce((a,b)=>a+b,0)} / 63`:'はじめての九九も、だいじょうぶ。';
 $('game-grid').replaceChildren();
 for(const game of GAMES){const b=document.createElement('button');b.className='game-card';b.dataset.game=game.id;b.innerHTML=`<img loading="lazy" src="${artPath(game.id)}" alt=""><div class="card-copy"><small>SHOW ${String(game.id).padStart(2,'0')}</small><span class="card-stars">${'★'.repeat(save.stars[game.id]||0)}${'☆'.repeat(3-(save.stars[game.id]||0))}</span><h3>${game.title}</h3><p>${game.subtitle}</p></div>`;b.addEventListener('click',()=>preview(game));$('game-grid').append(b);}
}
function preview(game){openDialog(`<img class="modal-hero" src="${artPath(game.id)}" alt="${game.title}"><h2>${game.title}</h2><p>${game.instruction}</p><p>まず九九をきく → 答えをえらぶ → リズムに合わせて操作。<br>5問・約1分。タイミングと九九の正解は、別々にほめるよ。</p><div class="modal-buttons"><button id="start-single" class="primary">あそぶ！</button><button id="start-watch" class="secondary">お手本をみる</button></div>`);$('start-single').onclick=()=>start({mode:'single',gameId:game.id});$('start-watch').onclick=()=>start({mode:'single',gameId:game.id,watch:true});}
async function start(options){
 const run=++token;running=false;paused=false;audio.stop();cancelAnimationFrame(frame);$('dialog').close();$('loading').hidden=false;$('loading').querySelector('progress').value=0;
 watch=!!options.watch;lastOptions={...options};results=[];index=0;streak=0;
 playlist=makePlaylist(options.mode,options.gameId,Number($('table').value),Math.random,options.review||[]);
 try{
  await audio.unlock();applySettings();
  await Promise.all([ensureArt(),audio.load(playlist,p=>{$('loading').querySelector('progress').value=p;})]);
  if(run!==token)return;
  audio.start(musicFor(playlist[0].gameId));running=true;audio.cheer(Math.random()<.25?'encourage':'start',{},3.1);roundStart=8*BEAT;beginRound(true);$('loading').hidden=true;screen('play');requestWakeLock();frame=requestAnimationFrame(tick);
 }catch(error){if(run!==token)return;$('loading').hidden=true;audio.stop();screen('home');openDialog(`<h2>準備がとまってしまいました</h2><p>通信を確認して、もう一度おためしください。保存済みならオフラインでも遊べます。</p><p>${safeText(error.message||'素材の読み込みに失敗しました')}</p><div class="modal-buttons"><button id="retry-load" class="primary">もう一度</button></div>`);$('retry-load').onclick=()=>start(options);}
}
function beginRound(changed){
 const q=playlist[index],game=GAMES[q.gameId-1];if(q.gameId===21)q.character=['オオカミ','ウサギ','クマ','キツネ'][(q.a+q.b)%4];flags={q:false,answer:false,cheer:false,auto:false,tick:-1};phase='intro';
 mini=createMiniGame(game.id,q,{drawCharacter:art.drawCharacter.bind(art),drawNumber:art.drawNumber.bind(art)});art.theme=game.id===21?'wood':[3,5,10,15,16,18].includes(game.id)?'jelly':'gold';
 $('game-no').textContent=String(game.id).padStart(2,'0');$('game-title').textContent=game.title;$('play-mode').textContent=watch?'お手本モード':lastOptions.mode==='tour'?'21 SHOWS TOUR':'ON AIR';$('round-count').textContent=`${index+1} / ${playlist.length}`;$('score-live').textContent=`せいかい ${results.filter(x=>x.correct).length}`;$('instruction').textContent=game.instruction;
 $('feedback').hidden=true;$('progress-caption').textContent=watch?'みて、きいて、まねしてみよう':`全${playlist.length}問`;$('round-hint').textContent='正しい九九は、あとで一緒にいおう。';
 const intro=$('game-intro');intro.hidden=!changed;intro.querySelector('h3').textContent=game.title;intro.querySelector('p').textContent=game.instruction;
 renderEquation('listen');$('answers').replaceChildren();
 mini.controls.forEach((c,i)=>{const b=document.createElement('button');b.className='answer-button';b.dataset.value=c.value;b.disabled=true;b.setAttribute('aria-label',c.label);if(/^\d+$/.test(c.label))b.append(art.numberElement(c.label,art.theme));else b.append(document.createTextNode(c.label));const key=document.createElement('small');key.textContent=String(i+1);b.append(key);b.onclick=()=>{if(canPlay()){mini.choose(c.value,localTime());audio.sfx('tap');updateControls();}};$('answers').append(b);});
 const actionLabels={hold:'ためて…はなす',pour:'そそぐ → はなす',pull:'まって…つる！',breathe:'ためて…はなす',double:'ドン・ドン！',conduct:'1・2・3！',throw:'シュート！',climb:'ジャンプ！',deliver:'おとどけ！',pair:'ペアにする'};
 $('action-btn').innerHTML=`${actionLabels[game.mechanic]||'ポン！'}<small>${['hold','pour','pull','breathe'].includes(game.mechanic)?'長おしして はなす':'タップ / SPACE'}</small>`;
 $('action-btn').hidden=[4,6,18,21].includes(game.id);$('action-btn').disabled=true;
 mini.update({time:0,beat:0,phase:'listen',reduceMotion:art.reduceMotion});mini.draw(ctx,1000,440);
}
function localTime(){return audio.now()-roundStart;}
function canPlay(){return running&&!paused&&!watch&&phase==='play'&&!mini.completed;}
function renderEquation(p){const q=playlist[index],truth=[4,21].includes(q.gameId);$('equation').replaceChildren();
 if(q.gameId===12&&p==='play'){$('equation').textContent='どの数字だった？';return;}
 const parts=p==='reveal'?[q.a,'×',q.b,'＝',q.answer]:q.gameId===15?[q.a,'×','□','＝',q.answer]:truth?[q.a,'×',q.b,'＝',q.claimed]:[q.a,'×',q.b,'＝','？'];
 for(const part of parts){if(typeof part==='number')$('equation').append(art.numberElement(part,art.theme));else{const s=document.createElement('span');s.textContent=part;$('equation').append(s);}}
 $('equation').setAttribute('aria-label',parts.join(' '));
}
function updateControls(){for(const b of $('answers').children){b.disabled=!canPlay();b.classList.toggle('selected',Number(b.dataset.value)===mini.selected);} $('action-btn').disabled=!canPlay();}
function tick(){
 if(!running)return;
 if(!paused){let time=localTime(),beat=time/BEAT;
  if(beat>=ROUND_BEATS){if(!flags.answer)reveal();if(index+1>=playlist.length){finish();return;}const old=playlist[index].gameId;index++;const changed=old!==playlist[index].gameId;roundStart+=ROUND_BEATS*BEAT+(changed?8*BEAT:0);if(changed){audio.setMusic(musicFor(playlist[index].gameId));const event=flags.grade?.correct?(index%2?'character':'transition'):'encourage';audio.cheer(event,{...flags.cheerContext,nextIsLast:index===playlist.length-1},3)||audio.cheer('transition',{nextIsLast:index===playlist.length-1},3);}beginRound(changed);time=localTime();beat=time/BEAT;}
  const q=playlist[index],listenBeats=q.gameId===15?7:[4,21].includes(q.gameId)?6:4,next=beat<0?'intro':beat<listenBeats?'listen':beat<14?'play':'reveal';
  if(next!==phase){phase=next;if(phase!=='intro')$('game-intro').hidden=true;renderEquation(phase);$('phase-label').textContent=phase==='intro'?'つぎのステージ！':phase==='listen'?'まずは、きこう':phase==='play'?(watch?'お手本をみよう':'答えをえらんで、ポン！'):'いっしょに九九！';}
  mini.update({time:Math.max(0,time),beat:Math.max(0,beat),phase:phase==='intro'?'listen':phase,reduceMotion:art.reduceMotion,correct:flags.grade?.correct});
  if(beat>=.2&&!flags.q){flags.q=true;const kind=[4,21].includes(q.gameId)?q.truth?'a':'f':q.gameId===15?'r':'q';audio.speak(`${kind}-${q.a}-${q.b}`,{maxSeconds:3.2});}
  if(beat>=4&&beat<14){const k=Math.floor(beat);if(k!==flags.tick){flags.tick=k;if(k>=9&&k<=12)audio.sfx('tick');}if(watch&&beat>=12&&!flags.auto)autoPlay(time);}
  if(beat>=14&&!flags.answer)reveal();
  if(beat>=20&&!flags.cheer){flags.cheer=true;const r=flags.grade;const context={correct:r.correct,attempted:r.value!==null,rhythmHit:['perfect','nice'].includes(r.rhythm),streak,answerShown:true,reviewQueued:!r.correct,nearMiss:r.value!==null&&Math.abs(r.value-q.answer)<=2,isLast:index===playlist.length-1,gameId:GAMES[q.gameId-1].slug,isSlot:q.gameId===1,hintUsed:watch,claimFalse:!q.truth,caughtLie:!q.truth&&r.correct,character:q.character||GAMES[q.gameId-1].character,isJump:[5,14].includes(q.gameId),punchSuccess:q.gameId===8&&r.correct&&r.performed,repairSuccess:q.gameId===18&&r.correct&&r.performed,responseSeconds:r.errorMs===null?0:mini.getResult().hitTime,wasWrongBefore:save.facts[`${q.a}-${q.b}`]?.lastCorrect===false||results.slice(0,-1).some(x=>x.a===q.a&&x.b===q.b&&!x.correct),struggled:save.facts[`${q.a}-${q.b}`]?.lastCorrect===false,willRetry:playlist[index+1]?.a===q.a&&playlist[index+1]?.b===q.b};flags.cheerContext=context;const events=r.correct?['correct','correct_big',...(context.rhythmHit?['rhythm']:[]),...(streak>=2?['streak']:[]),'character']:['wrong'];const event=events[Math.floor(Math.random()*events.length)];let cheer=audio.cheer(event,context,Math.max(0,(24-beat)*BEAT-.1));if(!cheer&&r.correct)cheer=audio.cheer('correct',context,1.6);if(cheer)$('round-hint').textContent=cheer.text;}
  const n=Math.max(0,Math.min(24,beat));$('beat-fill').style.width=`${n/24*100}%`;$('beat-count').textContent=beat>=9&&beat<12?String(12-Math.floor(beat)):beat>=12&&beat<13?'●':'♪';$('rhythm-message').textContent=beat<0?'じゅんび！':beat<9?'●でポン！':beat<12?'せーの…':beat<14?'いま！':'いっしょに！';
  mini.draw(ctx,1000,440);updateControls();
 }
 frame=requestAnimationFrame(tick);
}
function autoPlay(time){const q=playlist[index],expected=[4,21].includes(q.gameId)?Number(q.truth):q.answer;mini.choose(expected,time);for(let i=0;i<3&&!mini.completed;i++){mini.pointer('down',500,410,time-.18);mini.pointer('up',500,410,time);}flags.auto=true;}
function reveal(){
 flags.answer=true;const q=playlist[index];let result=mini.getResult();if(watch)result={value:[4,21].includes(q.gameId)?Number(q.truth):q.answer,performed:true,hitTime:12*BEAT};
 const r=grade(q,result,{offset:save.settings.offset,watch});flags.grade=r;results.push(r);streak=r.correct?streak+1:0;audio.sfx(r.correct?'correct':'wrong');audio.speak(`a-${q.a}-${q.b}`,{maxSeconds:2.6});renderEquation('reveal');
 $('feedback').hidden=false;$('feedback').className=`feedback ${r.correct?'':'retry'}`;$('feedback').textContent=r.correct?(q.gameId===21&&!q.truth?'みやぶった！':r.rhythm==='perfect'?'せいかい！ ぴったり！':'せいかい！'):`いっしょに！ ${q.a} × ${q.b} ＝ ${q.answer}`;
 $('score-live').textContent=`せいかい ${results.filter(x=>x.correct).length}`;for(const b of $('answers').children)b.classList.toggle('correct-answer',Number(b.dataset.value)===([4,21].includes(q.gameId)?Number(q.truth):q.answer));
 $('round-hint').textContent=r.correct?'いいね！ 正しい九九を声に出してみよう。':'正しい答えをきいて、もう一度おぼえよう。';
}
async function finish(){
 running=false;paused=false;cancelAnimationFrame(frame);audio.stop();releaseWakeLock();const s=summarize(results);save=record(save,results);if(!watch)persist();refreshHome();screen('results');
 $('result-title').textContent=watch?'お手本、おしまい！':s.correct===s.total?'ぜんぶ、せいかい！':'さいごまで、できたね！';$('result-correct').textContent=`${s.correct} / ${s.total}`;$('result-rhythm').textContent=`${s.rhythm}回`;$('result-note').textContent=watch?'お手本はきろくに入りません。つぎは自分でやってみよう！':s.review.length?'下の九九を押すと、正しい答えをもう一度きけるよ。':'楽しくできたね！ 別のゲームや、別のだんでも遊んでみよう。';
 $('review-list').replaceChildren();for(const q of s.review){const b=document.createElement('button');b.textContent=`♪ ${q.a} × ${q.b} ＝ ${q.a*q.b}`;b.onclick=async()=>{await audio.unlock();audio.speak(`a-${q.a}-${q.b}`,{force:true});};$('review-list').append(b);}
 $('review-btn').hidden=!s.review.length||watch;$('review-btn').onclick=()=>start({mode:'review',gameId:1,review:s.review});audio.sfx('finish');audio.cheer('finish',{allCompleted:true,roundsCompleted:results.length,finale:lastOptions.mode==='tour'},4);
}
function home(){++token;running=false;paused=false;audio.stop();cancelAnimationFrame(frame);releaseWakeLock();$('loading').hidden=true;$('dialog').close();refreshHome();screen('home');}
async function pause(show=true){if(!running||paused)return;paused=true;mini?.pointer('cancel',0,0,localTime());await audio.pause();releaseWakeLock();if(show)pauseDialog();}
function pauseDialog(){openDialog('<h2>ひとやすみ</h2><p>音楽もゲームも、とまっているよ。</p><div class="modal-buttons"><button id="resume-btn" class="primary">つづける</button><button id="pause-settings" class="secondary">設定</button><button id="quit-btn" class="quiet">ホームへ戻る</button></div>');$('resume-btn').onclick=()=>$('dialog').close();$('pause-settings').onclick=settings;$('quit-btn').onclick=home;}
async function resume(){if(!running||!paused)return;try{await audio.resume();paused=false;requestWakeLock();}catch{toast('画面をもう一度タップしてください。');}}
function settings(){openDialog(`<h2>音とあそびの設定</h2>${[['music','音楽'],['voice','九九の声'],['cheer','掛け声'],['sfx','効果音']].map(([k,label])=>`<label class="setting-row">${label}<input type="range" min="0" max="100" value="${save.settings[k]}" data-setting="${k}" aria-label="${label}"></label>`).join('')}<label class="setting-row">動きをひかえめに<input type="checkbox" id="reduce-motion" ${save.settings.reduceMotion?'checked':''}></label><label class="setting-row">タイミング補正 <output id="offset-label">${save.settings.offset}ms</output><input id="offset" aria-label="タイミング補正" type="range" min="-300" max="300" step="10" value="${save.settings.offset}"></label><p>Bluetoothイヤホンなどでずれを感じるときに調整。プラスにすると、遅いタップに合わせます。</p><p>タップの代わりに、1・2・3キーで答え、スペースでアクション。長おしはスペースを押して、はなしてね。</p><div class="modal-buttons"><button class="secondary" id="voices-btn">掛け声100コレクション</button><button class="quiet" id="settings-done">もどる</button></div><p style="margin-top:18px;font-size:10px">音声：VOICEVOX:ずんだもん（キャラクターごとに抑揚を調整）<br>音楽6曲は本作のオリジナル。記録はこの端末内に保存されます。</p>`);
 for(const input of document.querySelectorAll('[data-setting]'))input.oninput=()=>{save.settings[input.dataset.setting]=Number(input.value);applySettings();persist();};$('reduce-motion').onchange=e=>{save.settings.reduceMotion=e.target.checked;applySettings();persist();};$('offset').oninput=e=>{save.settings.offset=Number(e.target.value);$('offset-label').textContent=e.target.value+'ms';persist();};$('settings-done').onclick=()=>running?pauseDialog():$('dialog').close();$('voices-btn').onclick=voices;
}
async function voices(){previewAudio?.stop();previewAudio=new FestivalAudio();const player=previewAudio;openDialog('<h2>掛け声100コレクション</h2><p>声をじゅんびしています…</p>');const request=dialogRequest;try{await player.unlock();await player.load([],()=>{});if(request!==dialogRequest||!$('dialog').open){player.stop();if(player.ctx.state!=='closed')player.ctx.close();return;}player.setVolumes(save.settings);const clips=player.manifest.cheers;openDialog('<h2>掛け声100コレクション</h2><p>好きな台詞を押すと、声がきけるよ。</p><div class="review-list" id="voice-collection"></div><div class="modal-buttons"><button class="quiet" id="voices-back">設定へ</button></div>');for(const c of clips){const b=document.createElement('button');b.textContent=c.text;b.onclick=()=>player.speak(c.id,{force:true});$('voice-collection').append(b);}$('voices-back').onclick=()=>{player.stop();player.ctx.close();previewAudio=null;settings();};}catch{if(request===dialogRequest&&$('dialog').open)toast('声を読み込めませんでした。通信を確認してください。');}}
function records(){const facts=Object.entries(save.facts);openDialog(`<h2>九九のきろく</h2><p>${save.plays}回プレイ ／ ${save.correct}問せいかい ／ ★ ${Object.values(save.stars).reduce((a,b)=>a+b,0)} / 63</p><div class="fact-grid">${Array.from({length:81},(_,i)=>{const a=Math.floor(i/9)+1,b=i%9+1,f=save.facts[`${a}-${b}`];return `<span class="${f?f.lastCorrect?'learned':'retry':''}" title="${a}×${b}：${f?.correct||0}回正解">${a}×${b}</span>`;}).join('')}</div><p class="record-legend">緑：さいきん正解した九九　黄：もう一度れんしゅう<br>お手本の結果は記録しません。</p><div class="modal-buttons"><button class="primary" id="weak-btn">苦手な九九をれんしゅう</button><button class="quiet" id="export-btn">きろくを書き出す</button></div>`);$('weak-btn').onclick=()=>{const review=facts.filter(([,f])=>!f.lastCorrect).map(([k])=>{const [a,b]=k.split('-').map(Number);return{a,b};});if(!review.length){toast('苦手の記録はまだないよ。好きなゲームを遊んでみよう！');return;}start({mode:'review',gameId:1,review});};$('export-btn').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(save,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='kuku-beat-record.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};}
function pointer(e,type,action=false){if(!canPlay())return;e.preventDefault();const r=$('stage').getBoundingClientRect(),x=action?500:(e.clientX-r.left)/r.width*1000,y=action?410:(e.clientY-r.top)/r.height*440;if(type==='down'){e.currentTarget.setPointerCapture?.(e.pointerId);audio.sfx('tap');}mini.pointer(type,x,y,localTime());updateControls();}
for(const [id,isAction] of [['stage',false],['action-btn',true]])for(const [event,type] of [['pointerdown','down'],['pointermove','move'],['pointerup','up'],['pointercancel','cancel']])$(id).addEventListener(event,e=>pointer(e,type,isAction));
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&running&&!$('dialog').open){e.preventDefault();pause();return;}if(!canPlay()||e.repeat)return;if(['1','2','3','ArrowLeft','ArrowRight',' ','Enter'].includes(e.key)){e.preventDefault();if(e.key===' '||e.key==='Enter')mini.pointer('down',500,410,localTime());else mini.key(e.key,localTime());audio.sfx('tap');updateControls();}});
document.addEventListener('keyup',e=>{if(canPlay()&&(e.key===' '||e.key==='Enter')){e.preventDefault();mini.pointer('up',500,410,localTime());updateControls();}});
$('dialog').addEventListener('close',()=>{previewAudio?.stop();previewAudio?.ctx?.close();previewAudio=null;dialogRequest++;if(!running)audio.stopSpoken();if(running&&paused&&$('rotate').hidden)resume();});
$('mix-btn').onclick=()=>start({mode:'mix'});$('tour-btn').onclick=()=>start({mode:'tour'});$('browse-btn').onclick=()=>$('library').scrollIntoView({behavior:art.reduceMotion?'instant':'smooth'});$('settings-btn').onclick=settings;$('records-btn').onclick=records;$('pause-btn').onclick=()=>pause();$('home-btn').onclick=home;$('again-btn').onclick=()=>start(lastOptions);
function orientation(){const portrait=innerHeight>innerWidth&&innerWidth<700;const show=running&&portrait&&!allowPortrait;$('rotate').hidden=!show;if(show&&!paused)pause(false);else if(!show&&running&&paused&&!$('dialog').open)pauseDialog();}
$('portrait-continue').onclick=()=>{allowPortrait=true;$('rotate').hidden=true;pauseDialog();};addEventListener('resize',orientation);document.addEventListener('visibilitychange',()=>{if(document.hidden&&running)pause();});addEventListener('pagehide',()=>{if(running)pause(false);});
async function requestWakeLock(){try{if(navigator.wakeLock&&!document.hidden)wakeLock=await navigator.wakeLock.request('screen');}catch{}}
function releaseWakeLock(){wakeLock?.release().catch(()=>{});wakeLock=null;}
async function setupPWA(){if(!('serviceWorker'in navigator))return;try{swRegistration=await navigator.serviceWorker.register('./sw.js',{updateViaCache:'none'});navigator.serviceWorker.addEventListener('message',e=>{const d=e.data;if(d?.type==='CACHE_PROGRESS'||d?.type==='CACHE_COMPLETE'||d?.type==='CACHE_STATUS'){cacheStatus={...d,complete:d.complete||d.type==='CACHE_COMPLETE'};renderOfflineStatus();if(d.type==='CACHE_COMPLETE')toast('オフラインのじゅんびができました！');}if(d?.type==='CACHE_ERROR'){cacheStatus={...cacheStatus,type:'CACHE_ERROR',complete:false};renderOfflineStatus();toast(d.message||'保存を中断しました。通信と空き容量を確認して、再開できます。');const b=$('cache-all');if(b)b.disabled=false;}});swRegistration.active?.postMessage({type:'GET_CACHE_STATUS'});swRegistration.addEventListener('updatefound',()=>{swRegistration.installing?.addEventListener('statechange',()=>{if(swRegistration.waiting)toast('新しいバージョンがあります。ホームの「スマホに追加」から更新できます。');});});}catch{/* Local source previews do not contain a production asset manifest. */}}
function renderOfflineStatus(){if(!$('offline-status'))return;const c=cacheStatus;$('offline-status').textContent=c?.complete?'保存済み。この端末でオフラインでも遊べます。':c?.total?`${c.completed||0} / ${c.total} ファイルを保存`:'素材を保存すると、通信がなくても遊べます。';if($('offline-progress'))$('offline-progress').value=c?.total?c.completed/c.total:0;const b=$('cache-all');if(b){b.disabled=!!c?.complete||c?.type==='CACHE_PROGRESS';b.textContent=c?.complete?'保存できました':c?.type==='CACHE_PROGRESS'?'保存中…':'全ゲームを端末に保存';}}
$('install-btn').onclick=async()=>{try{offlineManifest=await (await fetch('./assets-manifest.json')).json();}catch{}const mb=offlineManifest?.totalBytes?`約${Math.ceil(offlineManifest.totalBytes/1e6)}MB`:'';openDialog(`<h2>スマホに入れて、いつでも遊ぼう</h2><p>iPhoneではSafariで開き、共有ボタン →「ホーム画面に追加」。追加したアイコンから開き、横向きで遊んでね。</p><p>AndroidやPCでは、ブラウザの「アプリをインストール」も使えます。</p><p id="offline-status"></p><progress id="offline-progress" class="offline-progress" max="1" value="0"></progress><p>${mb}。保存中はこの画面を開いたままにしてください。端末が保存データを整理した場合は、再保存できます。</p><div class="modal-buttons"><button id="cache-all" class="primary">全ゲームを端末に保存</button>${swRegistration?.waiting?'<button id="update-app" class="secondary">新しいバージョンへ更新</button>':''}</div>`);renderOfflineStatus();$('cache-all').onclick=async()=>{if(!swRegistration){toast('公開版をSafariなどの対応ブラウザで開いてください。');return;}const reg=await navigator.serviceWorker.ready;reg.active?.postMessage({type:'CACHE_ALL'});$('cache-all').disabled=true;$('cache-all').textContent='保存中…';};if($('update-app'))$('update-app').onclick=()=>{navigator.serviceWorker.addEventListener('controllerchange',()=>location.reload(),{once:true});swRegistration.waiting?.postMessage({type:'ACTIVATE_UPDATE'});};};
applySettings();refreshHome();setupPWA();if(!storageAvailable)toast('記録保存が使えないため、今回の記録は画面を閉じるまで有効です。');
// This development-only bridge drives real UI/mini-game inputs in deterministic browser tests.
if(['127.0.0.1','localhost'].includes(location.hostname))globalThis.__festival={start,home,audio,get state(){return{running,paused,phase,index,question:playlist[index],mini,results,playlist,roundStart,save};},seekBeat(beat){roundStart=audio.now()-beat*BEAT;},async ready(){await ensureArt();},snapshot(){return{running,paused,phase,index,results:[...results],selected:mini?.selected,completed:mini?.completed};}};
