import {createRequire} from 'node:module';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
const {chromium}=createRequire(import.meta.url)(process.env.MAGMA_PLAYWRIGHT||'playwright');
const browser=await chromium.launch({channel:'chrome',headless:true});
const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});
const page=await context.newPage(),errors=[];
page.on('pageerror',e=>errors.push(e.message));
const pixel=selector=>page.locator(selector).evaluate(c=>c.toDataURL());
const changes=async selector=>{const before=await pixel(selector);await page.waitForTimeout(260);assert.notEqual(await pixel(selector),before,selector+' must change actual pixels');};
await fs.mkdir(new URL('../test-output/',import.meta.url),{recursive:true});
try{
  await page.goto('http://localhost:4188/?test=1');await page.waitForFunction(()=>window.__magma);await page.locator('#loading').waitFor({state:'hidden'});
  assert.equal(await page.evaluate(()=>Object.keys(window.__magma.assets).filter(n=>n.startsWith('anim-')).length),9);
  await page.getByRole('button',{name:'ガチャ',exact:true}).click();
  await page.locator('[data-action="preview-select"]').click();await page.locator('[data-action="preview"][data-id="phoenix"]').click();
  await page.waitForFunction(()=>window.__magma.cinema?.phase==='ready');
  await changes('.capsule-energy');
  await page.locator('[data-cinema="open"]').click();await page.waitForFunction(()=>window.__magma.cinema?.phase==='reveal');
  await changes('.reward-art');
  await page.waitForTimeout(1200);await page.screenshot({path:new URL('../test-output/v22-phoenix.png',import.meta.url).pathname});
  await page.locator('[data-cinema="next"]').click();
  await page.evaluate(()=>{const m=window.__magma;m.save.tutorial=true;m.start();m.game.pause();m.showBattle();});
  await changes('.battle-enemy');
  await page.evaluate(()=>{const m=window.__magma;m.battle.cursor=.1;m.attack();});
  await page.waitForFunction(()=>document.querySelector('.battle-enemy').dataset.frame==='enemy-attack:1');
  assert.equal(await page.evaluate(()=>window.__magma.battle.lives),2);
  await page.screenshot({path:new URL('../test-output/v22-golem-attack.png',import.meta.url).pathname});
  await page.waitForFunction(()=>window.__magma.battle.cooldown===0);
  await page.evaluate(()=>{const m=window.__magma;m.battle.cursor=.5;m.attack();});
  await page.waitForFunction(()=>document.querySelector('.battle-enemy').dataset.frame==='enemy-hit:2');
  assert.equal(await page.evaluate(()=>window.__magma.battle.hits),1);
  await page.screenshot({path:new URL('../test-output/v22-golem-hit.png',import.meta.url).pathname});
  await page.waitForFunction(()=>window.__magma.battle.cooldown===0);
  await page.emulateMedia({reducedMotion:'reduce'});await page.waitForTimeout(50);
  const still=await pixel('.battle-enemy');await page.waitForTimeout(400);assert.equal(await pixel('.battle-enemy'),still);
  await page.evaluate(()=>{window.__magma.game.alive=false;window.__magma.resume();window.__magma.panel('gacha');});
  await page.locator('[data-action="preview-select"]').click();await page.locator('[data-action="preview"][data-id="ice"]').click();
  await page.waitForFunction(()=>window.__magma.cinema?.phase==='ready');await page.locator('[data-cinema="open"]').click();
  await page.waitForFunction(()=>window.__magma.cinema?.phase==='reveal');
  const reduced=await pixel('.reward-art');await page.waitForTimeout(450);assert.equal(await pixel('.reward-art'),reduced);
  await page.locator('[data-cinema="next"]').click();
  await page.evaluate(async()=>{await navigator.serviceWorker.ready;});await page.waitForFunction(()=>navigator.serviceWorker.controller);
  await context.setOffline(true);await page.reload();await page.waitForFunction(()=>window.__magma);await page.locator('#loading').waitFor({state:'hidden'});
  await page.getByRole('button',{name:'ガチャ',exact:true}).click();await page.locator('[data-action="preview-select"]').click();await page.locator('[data-action="preview"][data-id="mint"]').click();
  await page.waitForFunction(()=>window.__magma.cinema?.phase==='ready');await page.locator('[data-cinema="open"]').click();await page.waitForFunction(()=>window.__magma.cinema?.phase==='reveal');
  assert.equal(await page.locator('.reward-art').getAttribute('data-frame'),'aura-mint:0');
  assert.deepEqual(errors,[]);
  console.log('PASS: 9 loaded alpha sheets; capsule and phoenix pixels animate; golem idle/attack/hit actions; reduced-motion frames frozen; all sheets work offline; no browser errors.');
}finally{await browser.close();}
