import {createRequire} from 'node:module';
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.url);
const {chromium}=require(process.env.MAGMA_PLAYWRIGHT||'playwright');
const browser=await chromium.launch({channel:'chrome',headless:true});
const context=await browser.newContext({viewport:{width:1440,height:1000},deviceScaleFactor:1});
const page=await context.newPage();const errors=[];
page.on('pageerror',e=>errors.push(e.message));
page.on('response',r=>{if(r.status()>=400)errors.push(`${r.status()} ${r.url()}`);});
await fs.mkdir(new URL('../test-output/',import.meta.url),{recursive:true});
const screenshot=async name=>{await page.waitForTimeout(350);return page.screenshot({path:new URL(`../test-output/${name}.png`,import.meta.url).pathname,animations:'disabled'});};
try{
  await page.goto('http://localhost:4188/?test=1');await page.waitForFunction(()=>window.__magma);await page.locator('#loading').waitFor({state:'hidden'});
  await screenshot('01-home-desktop');
  await page.getByRole('button',{name:'冒険をはじめる'}).click();await page.getByRole('button',{name:'わかった、出発！'}).click();
  await page.keyboard.press('Space');await page.waitForTimeout(220);assert((await page.evaluate(()=>window.__magma.game.player.y))>0);
  await screenshot('02-gameplay-desktop');
  await page.keyboard.press('Escape');assert.equal(await page.evaluate(()=>window.__magma.game.paused),true);
  const y=await page.evaluate(()=>window.__magma.game.player.y);await page.waitForTimeout(250);assert.equal(await page.evaluate(()=>window.__magma.game.player.y),y);
  await page.getByRole('button',{name:'設定',exact:true}).click();await page.getByRole('switch',{name:'サウンド',exact:true}).click();assert.equal(await page.evaluate(()=>window.__magma.save.sound),false);
  await page.getByRole('button',{name:'戻る',exact:true}).click();await page.getByRole('button',{name:'ホームに戻る',exact:true}).click();await page.getByRole('button',{name:'ホームに戻る',exact:true}).click();
  const beforeUpgrade=await page.evaluate(()=>window.__magma.save.coins);
  await page.getByRole('button',{name:'強化',exact:true}).click();await page.locator('[data-action="upgrade"]').first().click();assert.equal(await page.evaluate(()=>window.__magma.save.speed),1);assert.equal(await page.evaluate(()=>window.__magma.save.coins),beforeUpgrade-100);
  await page.locator('[data-action="upgrade"]').first().click();assert.equal(await page.evaluate(()=>window.__magma.save.speed),1);
  await screenshot('03-upgrades');
  await page.getByRole('button',{name:'戻る',exact:true}).click();
  await page.evaluate(()=>{window.__magma.save.coins=500;window.__magma.persist();});
  await page.getByRole('button',{name:'ガチャ',exact:true}).click();await screenshot('04-gacha');await page.getByRole('button',{name:'1回まわす'}).click();
  const coins=await page.evaluate(()=>window.__magma.save.coins);assert(coins===400||coins===430);await screenshot('05-gacha-result');await page.getByRole('button',{name:'装備する',exact:true}).click();
  await page.getByRole('button',{name:'戻る',exact:true}).click();await page.getByRole('button',{name:'コレクション',exact:true}).click();await screenshot('06-collection');
  await page.evaluate(()=>window.__magma.start());
  await page.evaluate(()=>{window.__magma.game.pause();window.__magma.game.hunger=30;window.__magma.showShop();});
  await page.getByRole('button',{name:'食べる'}).first().click();assert.equal(await page.evaluate(()=>window.__magma.game.hunger),65);await screenshot('07-shop');await page.getByRole('button',{name:'元気に出発する'}).click();
  await page.evaluate(()=>{window.__magma.game.pause();window.__magma.showQuiz();});await screenshot('08-quiz');
  await page.evaluate(()=>window.dispatchEvent(new Event('blur')));const timer=await page.locator('#quiz-timer').getAttribute('style');await page.waitForTimeout(250);assert.equal(await page.locator('#quiz-timer').getAttribute('style'),timer);await page.evaluate(()=>window.dispatchEvent(new Event('focus')));
  await page.locator('[data-action="answer"]').first().click();assert.equal(await page.evaluate(()=>window.__magma.dialog),'quiz-result');await page.getByRole('button',{name:'冒険をつづける'}).click();
  await page.evaluate(()=>{window.__magma.game.pause();window.__magma.showBattle();});await screenshot('09-battle');
  for(let i=0;i<3;i++)await page.evaluate(()=>{window.__magma.battle.cursor=.5;window.__magma.battle.cooldown=0;window.__magma.attack();});assert.equal(await page.evaluate(()=>window.__magma.dialog),'battle-result');await page.getByRole('button',{name:'上を目指そう'}).click();
  await page.evaluate(()=>{window.__magma.game.lava=window.__magma.game.player.y+40;});await page.waitForFunction(()=>window.__magma.dialog==='result');await screenshot('10-result');
  const saved=await page.evaluate(()=>JSON.stringify(window.__magma.save));await page.reload();await page.waitForFunction(()=>window.__magma);assert.equal(await page.evaluate(()=>JSON.stringify(window.__magma.save)),saved);
  await page.evaluate(()=>navigator.serviceWorker.ready);await page.reload();await page.waitForFunction(()=>window.__magma);assert(await page.evaluate(()=>!!navigator.serviceWorker.controller));
  await context.setOffline(true);await page.reload();await page.waitForFunction(()=>window.__magma);await page.locator('#loading').waitFor({state:'hidden'});assert.equal(await page.evaluate(()=>window.__magma.view),'home');await context.setOffline(false);
  await page.setViewportSize({width:390,height:844});await screenshot('11-home-iphone');await page.getByRole('button',{name:'冒険をはじめる'}).click();await page.waitForTimeout(150);await screenshot('12-gameplay-iphone');
  await page.getByRole('button',{name:'ジャンプ',exact:true}).click();await page.waitForTimeout(200);assert((await page.evaluate(()=>window.__magma.game.player.y))>0);
  await page.keyboard.press('Escape');await page.setViewportSize({width:375,height:667});await screenshot('13-pause-iphone-se');
  assert.deepEqual(errors,[]);
  console.log('PASS: start, keyboard jump, pause, settings, upgrade, insufficient balance, gacha, equip, collection, food, quiz, battle, death, persistence, offline PWA, mobile layouts. No browser errors.');
}finally{await browser.close();}
