import test from 'node:test';
import assert from 'node:assert/strict';
import {puzzles3d,Game3D,index3,coordinates,allLines,lineIds} from '../dist/puzzles3d.mjs';
function candidates(n,clue){if(clue[0]===0)return [Array(n).fill(0)];const result=[];function visit(k,start,line){if(k===clue.length){result.push(line);return;}const tail=clue.slice(k+1).reduce((a,b)=>a+b,0)+clue.length-k-1;for(let pos=start;pos<=n-clue[k]-tail;pos++){const copy=[...line];for(let j=pos;j<pos+clue[k];j++)copy[j]=1;visit(k+1,pos+clue[k]+1,copy);}}visit(0,0,Array(n).fill(0));return result;}
function solve(p){const grid=Array(p.size**3).fill(-1),lines=allLines(p).map(line=>({...line,options:candidates(p.size,line.clue)}));let changed=true;while(changed){changed=false;for(const line of lines){line.options=line.options.filter(bits=>line.ids.every((id,k)=>grid[id]===-1||grid[id]===bits[k]));assert.ok(line.options.length);for(let k=0;k<p.size;k++){const bit=line.options[0][k];if(grid[line.ids[k]]===-1&&line.options.every(o=>o[k]===bit)){grid[line.ids[k]]=bit;changed=true;}}}}return grid;}
for(const p of puzzles3d)test(`3D ${p.id}: all three axes uniquely determine the sculpture`,()=>{assert.equal(p.solution.length,p.size**3);assert.ok(p.solution.some(v=>v===0));assert.ok(p.solution.some(v=>v===1));assert.deepEqual(solve(p),p.solution);});
test('coordinates and indices roundtrip; each cube belongs to exactly three clue lines',()=>{for(const p of puzzles3d){const counts=Array(p.size**3).fill(0);allLines(p).forEach(l=>l.ids.forEach(i=>counts[i]++));assert.ok(counts.every(v=>v===3));for(let i=0;i<p.size**3;i++)assert.equal(index3(...coordinates(i,p.size),p.size),i);}});
test('wrong destruction leaves required block intact, with escalating penalties',()=>{const g=new Game3D(puzzles3d[0]);g.start();const i=g.puzzle.solution.indexOf(1);for(const penalty of [120,240,480]){assert.equal(g.act(i,'remove'),penalty);assert.equal(g.cells[i],0);}assert.equal(g.remaining,960);});
test('removing every blank reveals the sculpture; marking solids is optional',()=>{const g=new Game3D(puzzles3d[0]);g.start();g.puzzle.solution.forEach((v,i)=>{if(!v)assert.equal(g.act(i,'remove'),'removed');});assert.equal(g.status,'won');assert.ok(g.puzzle.solution.every((v,i)=>v?g.cells[i]===0:g.cells[i]===-1));});
test('left mark toggles; marking a blank costs time, removed cubes cannot be edited',()=>{const g=new Game3D(puzzles3d[0]);g.start();const i=g.puzzle.solution.indexOf(1),j=g.puzzle.solution.indexOf(0);assert.equal(g.act(i,'keep'),'marked');assert.equal(g.act(i,'keep'),'unmarked');assert.equal(g.act(j,'keep'),120);assert.equal(g.cells[j],0);assert.equal(g.act(j,'remove'),'removed');assert.equal(g.act(j,'keep'),'ignored');});
test('hint opens the three selected lines only and costs 5 minutes after a free start',()=>{const g=new Game3D(puzzles3d[8]);g.start();assert.equal(g.hint([2,2,2],true),true);assert.equal(g.remaining,1800);for(let a=0;a<3;a++)for(const i of lineIds(a,[2,2,2],5))assert.equal(g.cells[i],g.puzzle.solution[i]?1:-1);assert.equal(g.hint([2,2,2],true),false);assert.equal(g.hint([1,1,1]),true);assert.equal(g.remaining,1500);g.remaining=300;assert.equal(g.hint([0,0,0]),false);});
test('saved sculpture resumes paused with carved blocks; time over freezes input',()=>{const g=new Game3D(puzzles3d[0]);g.start();const j=g.puzzle.solution.indexOf(0);g.act(j,'remove');g.tick(10);const restored=new Game3D(puzzles3d[0],g.snapshot());assert.equal(restored.status,'paused');assert.equal(restored.cells[j],-1);restored.tick(100);assert.equal(restored.remaining,1790);restored.start();restored.tick(1800);assert.equal(restored.status,'lost');assert.equal(restored.act(0,'keep'),'ignored');});
