"""170 independently illustrated designs; not generated color swaps."""
GROUPS=[
('街の職人',[
('時計職人','repair',.92,'elderly tiny man with huge silver moustache round jeweler loupe navy vest repairing a pocket watch'),('鍵屋さん','keys',1.04,'stocky red-haired woman green apron brass key ring filing a key'),('靴職人','polish',.99,'bald dark-skinned man round glasses leather apron polishing a boot'),('ガラス職人','glass',1.10,'slim woman curly blonde hair blue protective glasses holding colorful glass vase'),('仕立て屋さん','sew',1.02,'older Asian woman black bob plum dress with measuring tape stitching cloth'),('かご職人','weave',.86,'elderly broad woman gray braids teal smock weaving a wicker basket'),('革職人','stitch',1.15,'tall bearded man flat cap orange apron stitching a satchel'),('和傘職人','umbrella',1.05,'Japanese middle-aged man tied gray hair indigo workwear opening a red paper umbrella'),('提灯職人','lantern',.97,'round young woman dark skin pink turban olive apron painting a lantern'),('石工さん','carve',1.25,'very large muscular older man white beard bandana sand overalls carefully chiseling small stone')]),
('おいしい街',[
('クレープ屋さん','crepe',.95,'short woman freckled cheeks lilac chef cap mint apron folding a crepe'),('寿司職人','sushi',1.09,'older Japanese man white headband navy apron making sushi on a little tray'),('アイス屋さん','icecream',1.06,'plump cheerful man ginger curled moustache striped pink vest scooping icecream'),('たこ焼き屋さん','cook',1.0,'woman brown skin short curly hair red happi coat turning takoyaki'),('ピザ職人','pizza',1.20,'tall thin man bald head black goatee green apron tossing pizza dough'),('チョコ職人','chocolate',.88,'tiny elderly woman white bob brown chef coat stirring chocolate'),('お茶屋さん','tea',1.02,'middle-aged woman deep skin long braided bun jade kimono pouring tea'),('果物屋さん','fruit',1.13,'broad man wavy dark hair straw visor coral apron arranging oranges'),('たい焼き屋さん','waffle',.91,'short round man silver hair yellow bandana blue apron offering fish-shaped waffle'),('ドーナツ屋さん','donut',1.07,'plus-size woman pastel blue curls orange dress decorating a donut')]),
('市場のひと',[
('魚屋さん','fishbox',1.18,'robust woman dark bob rubber boots striped navy apron holding a fish crate'),('八百屋さん','vegetables',1.03,'bald friendly man green cap mustard apron arranging carrots'),('古道具屋さん','antique',.91,'elderly woman enormous round glasses orange shawl examining brass teapot'),('帽子屋さん','hat',1.20,'very tall elegant man long moustache velvet purple coat trying a top hat'),('ぬいぐるみ屋さん','toy',.95,'petite adult curly pink hair blue pinafore hugging plush rabbit'),('レコード屋さん','record',1.10,'dark-skinned young man round afro cream cardigan spinning vinyl record'),('花束のおじさん','bouquet',1.15,'large tattooed bearded adult wearing floral apron arranging bouquet'),('新聞屋さん','newspaper',.84,'older tiny woman gray pixie hair tan trousers unfolding newspaper'),('ジャム屋さん','jam',.98,'round young man freckles red curls plaid shirt stirring jar of jam'),('せっけん屋さん','soap',1.06,'woman wearing yellow headscarf turquoise dress stacking pastel soap bars')]),
('町の仕事',[
('消防士さん','hose',1.17,'muscular woman dark skin short hair red firefighter helmet yellow jacket winding hose'),('郵便屋さん','letter',.93,'petite older man white beard navy post cap teal bag sorting letters'),('車掌さん','ticket',1.12,'tall slender woman silver bob green conductor uniform punching tickets'),('救急隊員さん','bag',1.03,'stocky adult brown skin wavy hair orange paramedic jumpsuit opening first aid bag'),('研究者さん','science',1.09,'young woman huge curly black hair white labcoat purple boots examining test tube'),('先生','teach',1.05,'older man salt-and-pepper beard tan vest red tie showing picture book'),('司書さん','books',.92,'short woman with gray braid round spectacles burgundy cardigan stacking books'),('配管工さん','wrench',1.14,'broad man blue beard yellow beanie dark overalls turning a wrench'),('電気屋さん','bulb',.99,'woman copper pixie hair blue hardhat orange toolbox inspecting light bulb'),('獣医さん','vet',1.10,'androgynous adult long silver ponytail mint medical coat gently petting small toy dog')]),
('音楽の時間',[
('サックスの人','sax',1.16,'tall dark-skinned woman long dreadlocks orange jumpsuit playing saxophone'),('チェロの人','cello',1.19,'broad older man silver swept hair burgundy suit bowing small cello'),('フルートの人','flute',.97,'short slim woman black pixie hair teal long dress playing flute'),('トランペットの人','trumpet',1.09,'round freckled man curly red hair navy suspenders playing trumpet'),('ハープの人','harp',1.04,'woman gray hair bun lavender dress plucking small harp'),('三味線の人','shamisen',1.01,'Japanese elderly man shaved head indigo kimono playing shamisen'),('マラカスの人','maracas',.92,'plump joyful adult short pink hair rainbow vest shaking maracas'),('木琴の人','xylophone',.87,'small teenager brown skin blue beanie yellow shirt tapping a strapped xylophone'),('チューバの人','tuba',1.27,'very tall stocky woman ginger braid green band uniform playing brass tuba'),('ハーモニカの人','harmonica',.95,'elderly man oversized gray sideburns olive cap tan jacket playing harmonica')]),
('公園の遊び',[
('凧あげの子','kite',.75,'child with purple braids yellow dungarees flying a compact red diamond kite'),('こま回しの子','top',.70,'small Japanese boy shaved sides orange vest spinning a wooden top'),('けん玉の子','kendama',.77,'girl dark skin twin afro puffs teal hoodie playing kendama'),('竹馬の人','stilts',1.31,'tall slim adult messy ginger hair green shorts balancing on short stilts'),('竹とんぼの子','rotor',.71,'round child silver bob pink rainboots releasing bamboo rotor toy'),('紙飛行機の人','paperplane',1.05,'androgynous young adult black undercut blue scarf launching paper plane'),('シャボンの老人','bubbles',.89,'tiny old man huge white moustache red waistcoat blowing bubbles through large wand'),('お手玉のおばさん','beanbag',1.0,'plump woman dark skin lilac bun mustard dress juggling beanbags'),('将棋のおじいさん','boardgame',.88,'elderly hunched man bald with white fringe dark blue haori thinking over small gameboard'),('ブーメランの人','boomerang',1.14,'athletic woman brown skin short auburn hair violet shorts throwing soft blue boomerang')]),
('いろいろな運動',[
('卓球の人','tabletennis',1.00,'short stocky woman lime headband blue tracksuit swinging red table-tennis paddle'),('テニスの人','tennis',1.22,'tall slim man silver curls white sports shirt teal shorts swinging tennis racket'),('バドミントンの人','badminton',1.08,'woman dark skin long braids pink visor yellow sports dress swinging badminton racket'),('フェンシングの人','fencing',1.18,'adult curly brown hair white fencing outfit mask under arm practicing safe fencing stance'),('ボウリングの人','bowling',1.07,'plus-size woman purple bob black bowling shirt red trousers rolling blue bowling ball'),('ラグビーの人','rugby',1.29,'huge muscular man dark skin bald head green rugby kit holding oval ball'),('サーファー','surf',1.14,'tall adult long blonde hair tied back coral wetsuit balancing with little surfboard'),('ローラースケートの人','rollers',.99,'woman brown skin pink afro mint shorts skating on yellow roller skates'),('太極拳のおばあちゃん','taichi',.87,'elderly Chinese woman silver bun loose pale blue suit practicing tai chi'),('体操のおじいちゃん','stretch',1.13,'tall thin elderly man gray eyebrows orange tracksuit gently stretching sideways')]),
('庭と自然',[
('養蜂家さん','bees',1.10,'broad woman brown skin in white beekeeper suit mesh hat holding honey frame'),('きのこ博士','mushroom',.94,'older man huge red moustache olive mushroom-shaped hat brown overalls inspecting mushroom'),('盆栽のおじいさん','bonsai',.85,'very old Japanese man silver short hair green kimono trimming tiny bonsai'),('蝶をみる人','butterfly',1.07,'woman blonde braided crown lavender hiking coat watching butterfly on finger'),('双眼鏡の人','binoculars',1.21,'tall dark-skinned man gray beard tan safari jacket lifting binoculars'),('種まきの人','seeds',.98,'plus-size woman blue headscarf red apron scattering seeds from pouch'),('落ち葉のおじさん','rake',1.15,'broad elderly man black-gray beard orange knit hat green vest raking autumn leaves'),('虫めがねの子','inspect',.69,'tiny child with dark curls red raincoat inspecting ladybug with magnifier'),('植木鉢の人','plant',1.06,'androgynous adult purple buzzcut cream overalls carefully repotting a fern'),('バラの庭師','prune',1.03,'older woman silver curly bob large sunhat burgundy apron tending pink rose')]),
('ものづくり',[
('折り紙の人','origami',.96,'petite elderly woman white bob orange cardigan folding paper crane'),('模型の人','model',1.12,'thin man curly brown hair round glasses teal shirt building tiny model ship'),('刺しゅうの人','embroider',1.02,'woman dark skin long silver braids maroon dress sewing embroidery hoop'),('人形師さん','puppet',1.08,'bearded man red beret violet waistcoat operating a wooden marionette'),('書道の人','calligraphy',1.13,'Japanese woman tied black hair blue kimono writing with thick brush on blank scroll'),('スケッチの人','sketch',.95,'short adult green mohawk mustard hoodie sketching in notebook'),('折りたたみ椅子の人','chair',1.20,'large bald man ginger beard striped shirt unfolding small camping chair'),('風車を作る子','pinwheel',.73,'child with black pigtails green romper making colorful pinwheel'),('ビーズの人','beads',.93,'round woman bright pink turban denim apron threading big beads'),('ラジコンの人','remote',1.04,'adult silver undercut rainbow scarf navy jumpsuit holding controller for tiny robot car')]),
('おでかけ',[
('旅行のおばあちゃん','suitcase',.87,'tiny elderly woman gray perm round glasses red coat pulling polka-dot suitcase'),('登山のおじさん','hike',1.22,'large bearded man dark skin green hat orange hiking gear adjusting walking poles'),('カメラのおばさん','photo',1.01,'plus-size woman gray ponytail yellow vest holding big camera'),('スケッチ旅行者','map',1.15,'tall slim woman pink pixie hair purple coat unfolding large map'),('ピクニックの人','picnic',.97,'brown-skinned adult curly black hair teal dress opening wicker picnic basket'),('おみやげの青年','souvenir',1.09,'handsome man ash-blonde bob cream jacket carrying small souvenir packages'),('双眼鏡のおばあさん','binoculars',.89,'elderly woman long white braid navy sunhat coral coat looking through binoculars'),('海辺の子','shell',.74,'freckled child ginger curls blue bucket hat orange shorts inspecting seashell'),('虫よけの人','fan',1.03,'adult dark brown skin short purple hair lime cardigan waving a paper fan'),('水筒の人','drink',1.16,'tall stocky woman black braids blue hiking shirt taking drink from silver flask')]),
('おしゃれな住人',[
('ロングコートの紳士','watch',1.27,'very tall elegant older man dark skin silver goatee plum long coat checking pocket watch'),('ベレーの女性','read',1.10,'woman wavy dark bob red beret striped shirt navy wide trousers reading magazine'),('モードな青年','phone',1.19,'handsome slim man silver asymmetrical hair black cape orange boots taking selfie'),('虹色のスカーフの人','dance',1.06,'nonbinary adult round body blue short hair cream suit rainbow scarf gentle dance'),('大きなイヤリングの人','earrings',1.02,'dark-skinned woman big purple afro coral jumpsuit adjusting gold hoop earrings'),('花柄スーツの人','bouquet',1.18,'broad bearded man dark bun floral pink suit holding daisy bouquet'),('和モダンの人','fan',1.14,'adult woman shaved side hair indigo kimono jacket mustard hakama folding fan'),('リボンの紳士','bowtie',1.07,'short stocky older man gray handlebar moustache teal suit huge yellow bow tie adjusting tie'),('フリルの人','parasol',1.04,'adult androgynous person black curls lavender frilly dress tiny hat twirling parasol'),('スニーカーの人','laces',.96,'young adult brown skin orange buzzcut green oversized hoodie tying colorful sneakers')]),
('街の家族',[
('おんぶのおばあちゃん','cradle',.94,'round elderly woman white braid blue cardigan carrying toddler on her back'),('絵本のパパ','read',1.18,'large father dark skin silver-framed glasses orange sweater reading picture book'),('おやつのママ','snack',1.05,'woman red braided bob mint overalls sharing cookie from small tin'),('肩車のお父さん','shoulder',1.26,'broad man wavy black hair burgundy shirt with smiling small child riding shoulders'),('赤い長靴の子','puddle',.68,'tiny child silver bob yellow raincoat oversized red rainboots stomping playfully'),('工作の子','paper',.72,'brown-skinned girl curly dark hair purple apron holding folded paper crown'),('しゃがむおじいちゃん','crouch',.91,'elderly man bald head gray moustache plaid green shirt kneeling to look at flower'),('手袋のおばさん','knit',1.01,'plus-size woman short blue curls coral dress trying on knitted mittens'),('お菓子の兄ちゃん','snack',1.10,'slim teen boy ginger side-part hair navy hoodie eating pretzel'),('リュックのお姉ちゃん','pack',.87,'teen girl dark skin two long braids pink jacket organizing big yellow backpack')]),
('物語の仮装',[
('大きな騎士','knight',1.28,'very large adult in rounded silver foam knight armor blue plume doing courteous bow'),('小さな妖精','fairy',.84,'tiny adult woman silver pixie hair green leaf dress translucent fairy wings fluttering'),('かぼちゃの人','pumpkin',1.05,'rotund adult in orange pumpkin costume leaf hat doing little dance'),('きのこの人','mushroom',.96,'short adult wearing huge red spotted mushroom cap beige suit bobbing'),('ゆきだるまの人','snowman',1.14,'wide soft snowman mascot orange nose purple scarf waving mitten hands'),('ねこの仮装の人','catdance',1.01,'adult black pixie hair gray cat-eared hood pink paw gloves striped tail dancing'),('王冠のおじいさん','royal',.90,'short elderly man enormous white beard golden cardboard crown royal blue cape waving'),('天使のお姉さん','angel',1.12,'tall woman dark skin braided bun cream angel costume small gold halo flapping wings'),('カラフルな怪獣','monster',1.20,'adult in broad friendly turquoise monster suit yellow horns purple belly stomping'),('本の妖精','bookfairy',1.08,'androgynous adult red bob violet wizard hat book-shaped backpack turning book pages')]),
('楽しい衣装',[
('バナナの人','banana',1.24,'tall adult in bright yellow banana costume tiny blue shoes swaying'),('いちごの人','strawberry',.92,'short round adult in red strawberry mascot suit green leaf cap waving'),('宇宙人の人','alien',1.17,'slim adult in friendly mint alien costume two antennae silver cape playful wave'),('パンダの人','panda',1.07,'broad adult in fluffy panda mascot costume red bowtie rolling arms'),('トラの人','tiger',1.12,'adult in orange striped tiger costume long tail little green scarf stretching'),('うさぎの人','rabbit',1.16,'tall adult in white rabbit mascot costume long ears blue waistcoat hopping'),('カニの人','crab',.93,'wide adult red crab costume foam pincers gold crown clapping claws'),('ハチの人','bee',1.02,'short adult yellow-black bee suit transparent wings orange boots fluttering'),('恐竜博士','dinosaur',1.19,'older woman gray bun friendly blue dinosaur hood green lab apron inspecting fossil'),('星の人','star',1.0,'adult inside wide yellow five-point star costume purple leggings doing star jumps')]),
('動物の仲間',[
('ビーグル','sniff',.65,'real four-legged tricolor beagle floppy ears green bandana sniffing'),('コーギー','fetch',.56,'real four-legged orange-white corgi short legs blue collar chasing ball'),('ハスキー','shake',.79,'real four-legged gray-white husky blue eyes red collar shaking fur'),('ダルメシアン','stretch',.81,'real four-legged spotted Dalmatian purple collar stretching front legs'),('垂れ耳うさぎ','hop',.43,'real small lop-eared brown rabbit white paws nibbling carrot'),('白うさぎ','groom',.42,'real white rabbit pink ears washing face'),('ハリネズミ','curl',.36,'real small round hedgehog beige face curling into spiky ball'),('アヒル','waddle',.50,'real white duck orange bill turquoise bow swimming-waddling pose'),('ミニブタ','sniff',.57,'real plump pink miniature pig red bandana sniffing ground'),('リス','acorn',.37,'real red squirrel huge bushy tail holding and nibbling acorn')]),
('働く乗りもの好き',[
('自転車整備士','bikefix',1.09,'stocky woman dark skin short orange hair gray overalls tightening bicycle wheel'),('船長さん','captain',1.23,'large elderly man huge white beard navy captain cap cream coat raising binoculars'),('パイロットさん','pilot',1.15,'tall woman black ponytail brown aviator jacket goggles adjusting scarf'),('バスの運転手','driver',1.08,'round middle-aged man gray hair blue driver cap purple uniform polishing steering wheel prop'),('鉄道模型の人','train',.96,'short older woman red glasses green waistcoat holding toy steam train'),('宇宙好きの子','rocket',.74,'child dark skin curly hair silver hoodie holding orange toy rocket'),('消防好きの子','firetoy',.71,'little boy red curls yellow toy firefighter helmet carrying toy truck'),('車いすのダンサー','dance',.84,'young adult purple undercut rainbow shirt black manual wheelchair doing arm dance'),('車いすの読書家','read',.89,'elderly dark-skinned man gray beard teal cardigan seated in manual wheelchair reading'),('ベビーカーの人','stroller',1.08,'adult woman silver short hair coral coat gently pushing compact green stroller')]),
('夜のお祭り',[
('りんご飴の人','candy',.90,'petite adult black bob red yukata nibbling shiny candied apple'),('金魚すくいの人','goldfish',1.07,'round man ginger hair blue festival coat examining small goldfish bag'),('お面のおばさん','mask',1.02,'plus-size older woman silver curls purple kimono trying a white fox festival mask'),('星を見る人','stars',1.21,'tall slim woman dark skin large afro navy star-pattern cape using little telescope'),('灯りのおじいさん','lantern',.91,'elderly man white moustache teal happi coat swinging paper lantern'),('太鼓の子','drum',.76,'child brown skin red braid green happi coat beating small chest drum'),('踊る花笠の人','dance',1.14,'adult woman dark bun orange floral festival hat blue robe dancing'),('わたあめの人','cottoncandy',1.04,'stocky young man blue curls pink striped apron twirling cotton candy'),('扇子の青年','fan',1.16,'handsome adult man long silver hair black floral yukata waving folding fan'),('花火柄の人','sparkle',.99,'androgynous adult brown skin short mint hair plum firework-pattern jacket turning a star-shaped light toy')]),
]
