const defineKeyMove = (key, label, category, effect, animation, options = {}) => ({
    key,
    label,
    category,
    startup: options.startup ?? 9,
    recovery: options.recovery ?? 18,
    damage: options.damage ?? 34,
    knockback: options.knockback ?? 7,
    meterGain: options.meterGain ?? 4,
    effect,
    cooldown: options.cooldown ?? 22,
    animation,
    tint: options.tint ?? "#ffffff",
    reach: options.reach ?? 88,
    speed: options.speed ?? 11,
    status: options.status ?? null,
    barrier: options.barrier ?? 0,
    heal: options.heal ?? 0,
    buff: options.buff ?? null,
    projectileSpread: options.projectileSpread ?? 0,
    shots: options.shots ?? 1,
    arc: options.arc ?? 0
});

const KEY_MOVE_MAP = {
    q: defineKeyMove("q", "瞬打", "melee", "jab", "snap", { damage: 28, cooldown: 12, reach: 74, tint: "#8ff9ff" }),
    w: defineKeyMove("w", "しなり斬り", "melee", "slash", "arc", { damage: 34, reach: 90, tint: "#67d8ff" }),
    e: defineKeyMove("e", "肘槍", "rush", "rush", "burst", { damage: 42, knockback: 10, speed: 18, tint: "#54ffb8" }),
    r: defineKeyMove("r", "昇り膝", "anti-air", "launcher", "rise", { damage: 39, knockback: 12, cooldown: 24, tint: "#ffe08a" }),
    a: defineKeyMove("a", "碇蹴り", "melee", "low", "sweep", { damage: 33, knockback: 8, reach: 96, tint: "#8fd1ff" }),
    s: defineKeyMove("s", "螺旋掌", "melee", "wave", "pulse", { damage: 36, cooldown: 20, reach: 104, tint: "#9fffeb", status: "stagger" }),
    d: defineKeyMove("d", "疾走爪", "rush", "rush", "trail", { damage: 46, knockback: 13, speed: 20, cooldown: 26, tint: "#ff9b70" }),
    f: defineKeyMove("f", "牙圧", "breaker", "guardBreak", "impact", { damage: 48, reach: 92, cooldown: 28, tint: "#ff6b6b" }),
    z: defineKeyMove("z", "蛇行滑り", "mobility", "slide", "glitch", { damage: 30, speed: 16, cooldown: 18, tint: "#8cff93" }),
    x: defineKeyMove("x", "閃踵", "anti-air", "launcher", "cross", { damage: 40, knockback: 11, cooldown: 23, tint: "#ff9ae5" }),
    c: defineKeyMove("c", "旋鉤", "melee", "spin", "ring", { damage: 41, reach: 118, cooldown: 24, tint: "#88f7ff" }),
    v: defineKeyMove("v", "渦裂き", "rush", "rush", "shock", { damage: 44, knockback: 12, cooldown: 26, speed: 19, tint: "#ffd36d" }),

    t: defineKeyMove("t", "糸跳び", "mobility", "hop", "rise", { damage: 25, cooldown: 16, tint: "#ffd7ff", meterGain: 5 }),
    y: defineKeyMove("y", "受け流し斬り", "melee", "slash", "arc", { damage: 35, cooldown: 19, tint: "#afffb3" }),
    g: defineKeyMove("g", "格子砕き", "breaker", "guardBreak", "square", { damage: 45, cooldown: 28, tint: "#ffe27d" }),
    h: defineKeyMove("h", "六角破", "projectile", "projectile", "hex", { damage: 36, cooldown: 20, speed: 12, tint: "#abf3ff", reach: 260 }),
    b: defineKeyMove("b", "二進退き", "mobility", "backstep", "trail", { damage: 18, cooldown: 14, tint: "#9fd6ff", meterGain: 6 }),

    u: defineKeyMove("u", "影針", "projectile", "projectile", "needle", { damage: 32, cooldown: 16, speed: 14, tint: "#a2f0ff", reach: 320 }),
    i: defineKeyMove("i", "電荷弾", "projectile", "projectile", "bolt", { damage: 38, cooldown: 18, speed: 15, tint: "#68d2ff", reach: 340, status: "shock" }),
    o: defineKeyMove("o", "周回地雷", "trap", "trap", "ring", { damage: 34, cooldown: 28, tint: "#9d8cff", reach: 220, duration: 3.8 }),
    p: defineKeyMove("p", "虹柱光線", "beam", "beam", "beam", { damage: 50, cooldown: 34, tint: "#ff95d3", reach: 420, status: "blind" }),
    j: defineKeyMove("j", "投槍火花", "projectile", "projectile", "needle", { damage: 34, cooldown: 15, speed: 17, tint: "#afff6d", reach: 360 }),
    k: defineKeyMove("k", "薬缶爆弾", "bomb", "bomb", "explode", { damage: 55, cooldown: 36, tint: "#ffb36b", arc: 7, reach: 240, status: "burn" }),
    l: defineKeyMove("l", "光網", "trap", "trap", "grid", { damage: 30, cooldown: 29, tint: "#86fffc", duration: 4.2, status: "slow" }),
    n: defineKeyMove("n", "星種", "projectile", "projectile", "burst", { damage: 35, cooldown: 18, tint: "#8fffcc", reach: 300, status: "poison" }),
    m: defineKeyMove("m", "流星破", "rain", "rain", "meteor", { damage: 52, cooldown: 38, tint: "#ffb88e", reach: 260, status: "burn" }),

    "1": defineKeyMove("1", "鉄壁の構え", "buff", "shield", "guard", { damage: 0, cooldown: 34, barrier: 95, meterGain: 8, tint: "#c6d0de" }),
    "2": defineKeyMove("2", "双歩", "buff", "dash", "double", { damage: 18, cooldown: 20, speed: 22, tint: "#7ce6ff" }),
    "3": defineKeyMove("3", "第三の眼", "buff", "counter", "eye", { damage: 24, cooldown: 28, tint: "#c89dff", buff: "counter" }),
    "4": defineKeyMove("4", "第四の壁", "buff", "barrier", "plate", { damage: 0, cooldown: 36, barrier: 140, tint: "#ffd474" }),
    "5": defineKeyMove("5", "五速駆動", "buff", "haste", "pulse", { damage: 0, cooldown: 30, tint: "#73ff9e", buff: "haste", meterGain: 10 }),
    "6": defineKeyMove("6", "第六感", "buff", "evade", "fade", { damage: 0, cooldown: 26, tint: "#d2f5ff", buff: "evade" }),
    "7": defineKeyMove("7", "七刻印", "buff", "heal", "seal", { damage: 0, cooldown: 34, heal: 52, tint: "#a0ffe3", meterGain: 6 }),
    "8": defineKeyMove("8", "八拍衝", "buff", "wave", "drum", { damage: 38, cooldown: 25, tint: "#ff9e7b", status: "stagger" }),
    "9": defineKeyMove("9", "九生招来", "buff", "summon", "paw", { damage: 42, cooldown: 34, tint: "#ffc96d", status: "bleed" }),
    "0": defineKeyMove("0", "零刻", "buff", "time", "fracture", { damage: 0, cooldown: 40, tint: "#7dd0ff", buff: "timewarp", meterGain: 12 }),

    "-": defineKeyMove("-", "横滑り", "symbol", "backstep", "trail", { damage: 16, cooldown: 14, tint: "#a7d8ff", meterGain: 5 }),
    "=": defineKeyMove("=", "均衡光線", "symbol", "beam", "beam", { damage: 44, cooldown: 28, tint: "#ffe06e", reach: 360 }),
    "^": defineKeyMove("^", "山跳ね", "symbol", "hop", "rise", { damage: 20, cooldown: 16, tint: "#e8e68d", meterGain: 4 }),
    "@": defineKeyMove("@", "記号衛星", "symbol", "orbit", "orbit", { damage: 33, cooldown: 26, tint: "#e5a8ff", duration: 4.5 }),
    "[": defineKeyMove("[", "左括弧の護り", "symbol", "counter", "brace", { damage: 22, cooldown: 22, tint: "#8fddff", buff: "counter" }),
    "]": defineKeyMove("]", "右括弧の跳び", "symbol", "teleport", "blink", { damage: 30, cooldown: 24, tint: "#ff9dd0", knockback: 9 }),
    ";": defineKeyMove(";", "含み笑い", "symbol", "taunt", "flicker", { damage: 12, cooldown: 14, tint: "#d5f2ff", status: "weaken" }),
    ":": defineKeyMove(":", "双点砲", "symbol", "projectile", "double", { damage: 39, cooldown: 24, tint: "#9ccaff", shots: 2, projectileSpread: 18, reach: 340 }),
    ",": defineKeyMove(",", "払い下ろし", "symbol", "low", "sweep", { damage: 29, cooldown: 17, tint: "#7fe4ff", reach: 100 }),
    ".": defineKeyMove(".", "点穿ち", "symbol", "projectile", "pin", { damage: 43, cooldown: 21, tint: "#ff8ea0", speed: 20, reach: 420 }),
    "/": defineKeyMove("/", "斜線奔流", "symbol", "beam", "slash", { damage: 47, cooldown: 30, tint: "#7dffda", reach: 380 }),
    "`": defineKeyMove("`", "逆点瞬き", "symbol", "teleport", "glitch", { damage: 26, cooldown: 19, tint: "#b7bcff" }),
    "\\": defineKeyMove("\\", "割り込み砕き", "symbol", "guardBreak", "impact", { damage: 49, cooldown: 30, tint: "#ffb5a2" }),
    "'": defineKeyMove("'", "引用針", "symbol", "projectile", "needle", { damage: 31, cooldown: 16, tint: "#b5ecff", speed: 18, reach: 340 })
};

window.KEY_MOVE_MAP = KEY_MOVE_MAP;
