const defineKeyMove = (key, label, category, effect, animation, options = {}) => ({
    key,
    label,
    category,
    startup: options.startup ?? 9,
    recovery: options.recovery ?? 18,
    damage: options.damage ?? 34,
    knockback: options.knockback ?? 7,
    meterGain: options.meterGain ?? 4,
    effect,
    cooldown: options.cooldown ?? 22,
    animation,
    tint: options.tint ?? "#ffffff",
    reach: options.reach ?? 88,
    speed: options.speed ?? 11,
    status: options.status ?? null,
    barrier: options.barrier ?? 0,
    heal: options.heal ?? 0,
    buff: options.buff ?? null,
    projectileSpread: options.projectileSpread ?? 0,
    shots: options.shots ?? 1,
    arc: options.arc ?? 0
});

const KEY_MOVE_MAP = {
    q: defineKeyMove("q", "Quick Jab", "melee", "jab", "snap", { damage: 28, cooldown: 12, reach: 74, tint: "#8ff9ff" }),
    w: defineKeyMove("w", "Whiplash Chop", "melee", "slash", "arc", { damage: 34, reach: 90, tint: "#67d8ff" }),
    e: defineKeyMove("e", "Elbow Lance", "rush", "rush", "burst", { damage: 42, knockback: 10, speed: 18, tint: "#54ffb8" }),
    r: defineKeyMove("r", "Rising Knee", "anti-air", "launcher", "rise", { damage: 39, knockback: 12, cooldown: 24, tint: "#ffe08a" }),
    a: defineKeyMove("a", "Anchor Kick", "melee", "low", "sweep", { damage: 33, knockback: 8, reach: 96, tint: "#8fd1ff" }),
    s: defineKeyMove("s", "Spiral Palm", "melee", "wave", "pulse", { damage: 36, cooldown: 20, reach: 104, tint: "#9fffeb", status: "stagger" }),
    d: defineKeyMove("d", "Dash Claw", "rush", "rush", "trail", { damage: 46, knockback: 13, speed: 20, cooldown: 26, tint: "#ff9b70" }),
    f: defineKeyMove("f", "Fang Press", "breaker", "guardBreak", "impact", { damage: 48, reach: 92, cooldown: 28, tint: "#ff6b6b" }),
    z: defineKeyMove("z", "Zigzag Slide", "mobility", "slide", "glitch", { damage: 30, speed: 16, cooldown: 18, tint: "#8cff93" }),
    x: defineKeyMove("x", "Xenon Heel", "anti-air", "launcher", "cross", { damage: 40, knockback: 11, cooldown: 23, tint: "#ff9ae5" }),
    c: defineKeyMove("c", "Cyclone Hook", "melee", "spin", "ring", { damage: 41, reach: 118, cooldown: 24, tint: "#88f7ff" }),
    v: defineKeyMove("v", "Vortex Splitter", "rush", "rush", "shock", { damage: 44, knockback: 12, cooldown: 26, speed: 19, tint: "#ffd36d" }),

    t: defineKeyMove("t", "Thread Kick", "mobility", "hop", "rise", { damage: 25, cooldown: 16, tint: "#ffd7ff", meterGain: 5 }),
    y: defineKeyMove("y", "Yield Slice", "melee", "slash", "arc", { damage: 35, cooldown: 19, tint: "#afffb3" }),
    g: defineKeyMove("g", "Grid Crash", "breaker", "guardBreak", "square", { damage: 45, cooldown: 28, tint: "#ffe27d" }),
    h: defineKeyMove("h", "Hex Burst", "projectile", "projectile", "hex", { damage: 36, cooldown: 20, speed: 12, tint: "#abf3ff", reach: 260 }),
    b: defineKeyMove("b", "Binary Boot", "mobility", "backstep", "trail", { damage: 18, cooldown: 14, tint: "#9fd6ff", meterGain: 6 }),

    u: defineKeyMove("u", "Umbra Needle", "projectile", "projectile", "needle", { damage: 32, cooldown: 16, speed: 14, tint: "#a2f0ff", reach: 320 }),
    i: defineKeyMove("i", "Ion Shot", "projectile", "projectile", "bolt", { damage: 38, cooldown: 18, speed: 15, tint: "#68d2ff", reach: 340, status: "shock" }),
    o: defineKeyMove("o", "Orbit Mine", "trap", "trap", "ring", { damage: 34, cooldown: 28, tint: "#9d8cff", reach: 220, duration: 3.8 }),
    p: defineKeyMove("p", "Prism Beam", "beam", "beam", "beam", { damage: 50, cooldown: 34, tint: "#ff95d3", reach: 420, status: "blind" }),
    j: defineKeyMove("j", "Javelin Spark", "projectile", "projectile", "needle", { damage: 34, cooldown: 15, speed: 17, tint: "#afff6d", reach: 360 }),
    k: defineKeyMove("k", "Kettle Bomb", "bomb", "bomb", "explode", { damage: 55, cooldown: 36, tint: "#ffb36b", arc: 7, reach: 240, status: "burn" }),
    l: defineKeyMove("l", "Laser Web", "trap", "trap", "grid", { damage: 30, cooldown: 29, tint: "#86fffc", duration: 4.2, status: "slow" }),
    n: defineKeyMove("n", "Nova Seed", "projectile", "projectile", "burst", { damage: 35, cooldown: 18, tint: "#8fffcc", reach: 300, status: "poison" }),
    m: defineKeyMove("m", "Meteor Pop", "rain", "rain", "meteor", { damage: 52, cooldown: 38, tint: "#ffb88e", reach: 260, status: "burn" }),

    "1": defineKeyMove("1", "Iron Stance", "buff", "shield", "guard", { damage: 0, cooldown: 34, barrier: 95, meterGain: 8, tint: "#c6d0de" }),
    "2": defineKeyMove("2", "Twin Step", "buff", "dash", "double", { damage: 18, cooldown: 20, speed: 22, tint: "#7ce6ff" }),
    "3": defineKeyMove("3", "Third Eye", "buff", "counter", "eye", { damage: 24, cooldown: 28, tint: "#c89dff", buff: "counter" }),
    "4": defineKeyMove("4", "Fourth Wall", "buff", "barrier", "plate", { damage: 0, cooldown: 36, barrier: 140, tint: "#ffd474" }),
    "5": defineKeyMove("5", "Fifth Gear", "buff", "haste", "pulse", { damage: 0, cooldown: 30, tint: "#73ff9e", buff: "haste", meterGain: 10 }),
    "6": defineKeyMove("6", "Sixth Sense", "buff", "evade", "fade", { damage: 0, cooldown: 26, tint: "#d2f5ff", buff: "evade" }),
    "7": defineKeyMove("7", "Seventh Sign", "buff", "heal", "seal", { damage: 0, cooldown: 34, heal: 52, tint: "#a0ffe3", meterGain: 6 }),
    "8": defineKeyMove("8", "Eight Beat", "buff", "wave", "drum", { damage: 38, cooldown: 25, tint: "#ff9e7b", status: "stagger" }),
    "9": defineKeyMove("9", "Ninth Life", "buff", "summon", "paw", { damage: 42, cooldown: 34, tint: "#ffc96d", status: "bleed" }),
    "0": defineKeyMove("0", "Zero Frame", "buff", "time", "fracture", { damage: 0, cooldown: 40, tint: "#7dd0ff", buff: "timewarp", meterGain: 12 }),

    "-": defineKeyMove("-", "Hyphen Drift", "symbol", "backstep", "trail", { damage: 16, cooldown: 14, tint: "#a7d8ff", meterGain: 5 }),
    "=": defineKeyMove("=", "Equalizer Ray", "symbol", "beam", "beam", { damage: 44, cooldown: 28, tint: "#ffe06e", reach: 360 }),
    "^": defineKeyMove("^", "Caret Hop", "symbol", "hop", "rise", { damage: 20, cooldown: 16, tint: "#e8e68d", meterGain: 4 }),
    "@": defineKeyMove("@", "Atmark Satellite", "symbol", "orbit", "orbit", { damage: 33, cooldown: 26, tint: "#e5a8ff", duration: 4.5 }),
    "[": defineKeyMove("[", "Left Bracket Guard", "symbol", "counter", "brace", { damage: 22, cooldown: 22, tint: "#8fddff", buff: "counter" }),
    "]": defineKeyMove("]", "Right Bracket Snap", "symbol", "teleport", "blink", { damage: 30, cooldown: 24, tint: "#ff9dd0", knockback: 9 }),
    ";": defineKeyMove(";", "Semicolon Feint", "symbol", "taunt", "flicker", { damage: 12, cooldown: 14, tint: "#d5f2ff", status: "weaken" }),
    ":": defineKeyMove(":", "Colon Cannon", "symbol", "projectile", "double", { damage: 39, cooldown: 24, tint: "#9ccaff", shots: 2, projectileSpread: 18, reach: 340 }),
    ",": defineKeyMove(",", "Comma Sweep", "symbol", "low", "sweep", { damage: 29, cooldown: 17, tint: "#7fe4ff", reach: 100 }),
    ".": defineKeyMove(".", "Period Pierce", "symbol", "projectile", "pin", { damage: 43, cooldown: 21, tint: "#ff8ea0", speed: 20, reach: 420 }),
    "/": defineKeyMove("/", "Slash Torrent", "symbol", "beam", "slash", { damage: 47, cooldown: 30, tint: "#7dffda", reach: 380 }),
    "`": defineKeyMove("`", "Backtick Blink", "symbol", "teleport", "glitch", { damage: 26, cooldown: 19, tint: "#b7bcff" }),
    "\\": defineKeyMove("\\", "Backslash Breaker", "symbol", "guardBreak", "impact", { damage: 49, cooldown: 30, tint: "#ffb5a2" }),
    "'": defineKeyMove("'", "Quote Needle", "symbol", "projectile", "needle", { damage: 31, cooldown: 16, tint: "#b5ecff", speed: 18, reach: 340 })
};

window.KEY_MOVE_MAP = KEY_MOVE_MAP;
