const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path'),C=require('../src/expedition-core.js');
const context={window:{}};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../expedition/data.js'),'utf8'),context);const D=context.window.WACHA24_DATA;
function fixture(){const s=C.create(D,0,821),p=s.people[0];s.people=[p];s.targetId=0;s.rides=[];s.sites=[];s.walkable=null;s.definition={...s.definition,activityAreas:[],stairEdges:[{from:0,to:1,direction:'up'}]};const nodes=[{x:200,y:300,links:[1],level:0},{x:200,y:220,links:[0,2],level:1},{x:300,y:220,links:[1],level:1}],bins=new Map();nodes.forEach((n,i)=>{const key=`${Math.floor(n.x/80)},${Math.floor(n.y/80)}`;if(!bins.has(key))bins.set(key,[]);bins.get(key).push(i);});s.graph={nodes,bins,parents:new Int32Array(3),queue:new Int32Array(3)};Object.assign(p,{id:0,node:0,to:null,x:200,y:300,level:0,layer:0,station:null,ride:null,path:[1,2],activity:'walking',speed:38,pace:1,wantPace:1,nextPace:1000,pauseUntil:0,until:1000,nextDecision:1000,exitSite:null,transitSite:null,pendingSite:undefined,partner:null,chaseId:null,floorEscape:undefined,yieldWaitUntil:0,animal:false,phase:.25});s.nextEvent=1000;C.start(s);return{s,p};}
test('accepted upward and downward stair movement select opposite clips on the actual edge',()=>{const {s,p}=fixture();C.step(s,.1);assert.equal(p.visualStair,'up');assert.equal(p.visualView,'back');assert.ok(p.visualDY<0);assert.ok(Math.abs(p.visualSpeed-38)<1e-8);Object.assign(p,{node:1,to:0,path:[],x:200,y:240,level:1,layer:1});C.step(s,.1);assert.equal(p.visualStair,'down');assert.equal(p.visualView,'front');assert.ok(p.visualDY>0);});
test('flat upstairs movement is ordinary walking, not climbing inferred from its level',()=>{const {s,p}=fixture();Object.assign(p,{node:1,to:2,path:[],x:200,y:220,level:1,layer:1});C.step(s,.1);assert.equal(p.visualStair,null);assert.equal(p.visualView,'front');assert.equal(p.visualMoving,true);});
test('stopped stairs and paused game preserve the captured animation phase',()=>{const {s,p}=fixture();C.step(s,.1);p.pauseUntil=10;const phase=p.visualPhase;C.step(s,.1);assert.equal(p.visualMoving,false);assert.equal(p.visualStair,'up');assert.equal(p.visualPhase,phase);const snapshot=JSON.stringify(p);C.pause(s);C.step(s,2);assert.equal(JSON.stringify(p),snapshot);});
test('manual movement uses accepted path direction and zero input does not cycle feet',()=>{const {s,p}=fixture();s.targetControlled=true;Object.assign(p,{to:null,path:[],activity:'controlled'});C.input(s,0,-1);C.step(s,.1);assert.equal(p.visualStair,'up');assert.equal(p.visualView,'back');const phase=p.visualPhase;C.input(s,0,0);C.step(s,.1);assert.equal(p.visualPhase,phase);assert.equal(p.visualMoving,false);});
test('blocked input does not animate movement that the floor rejected',()=>{const {s,p}=fixture();s.targetControlled=true;s.walkable={unit:6,cols:300,rows:200,layers:[new Uint8Array(60000),new Uint8Array(60000)],holes:[]};s.walkable.layers[0][Math.floor(p.y/6)*300+Math.floor(p.x/6)]=1;C.input(s,0,-1);C.step(s,.1);assert.equal(p.x,200);assert.equal(p.y,300);assert.equal(p.visualMoving,false);assert.equal(p.visualStair,undefined);});
test('actual entryRoutes are recognized when a legacy stage lacks the new edge manifest',()=>{const {s,p}=fixture();s.definition={...s.definition,stairEdges:[],activityAreas:[{id:'upstairs',level:1,entryRoutes:[[0,1]]}]};C.step(s,.1);assert.equal(p.visualStair,'up');});
