const {chromium}=require('playwright'),assert=require('node:assert/strict'),path=require('node:path'),fs=require('node:fs');
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',args:['--allow-file-access-from-files']});
 try{
  const context=await browser.newContext({viewport:{width:1440,height:900}});await context.addInitScript(()=>{window.mockPads=[];window.makePad=index=>({connected:true,axes:[0,0],buttons:Array.from({length:16},()=>({pressed:false,value:0})),id:'QA simulated Switch-compatible gamepad '+index,index,mapping:'standard'});Object.defineProperty(navigator,'getGamepads',{value:()=>{if(window.blockPads)throw new DOMException('Gamepad denied','SecurityError');return window.mockPads;}});});
  const page=await context.newPage(),checks=[],errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('file://'+path.resolve('expedition/index.html'));await page.waitForSelector('[data-action=stage]');assert.equal(await page.locator('input[name=mode]').count(),0);checks.push('mode selection is removed and no controller is required to enter any town');
  await page.locator('[data-action=stage][data-id="0"]').click();await page.waitForSelector('[data-action=begin]',{timeout:90000});await page.locator('[data-action=begin]').click();
  for(const n of [3,2,1]){await page.waitForFunction(n=>document.getElementById('countdown-number').textContent===String(n)&&!document.getElementById('start-countdown').hidden,n);assert.equal(await page.evaluate(()=>Wacha24Debug.state.remaining),180);assert.equal(await page.locator('#time-left').innerText(),'03:00');}
  await page.waitForFunction(()=>Wacha24Debug.state.status==='playing');assert.equal(await page.locator('#start-countdown').isVisible(),false);assert.equal(await page.locator('#time-left').isVisible(),true);checks.push('3, 2, 1 appears before the 180-second timer and all residents start');
  const before=await page.evaluate(()=>{const {state:s,world:w}=Wacha24Debug,p=s.people[s.targetId];window.mockPads=[makePad(0),makePad(1)];window.mockPads[1].axes=[.8,.4];return{x:p.x,y:p.y,cx:w.cx,cy:w.cy};});await page.waitForTimeout(650);
  const after=await page.evaluate(()=>{const {state:s,world:w}=Wacha24Debug,p=s.people[s.targetId];return{x:p.x,y:p.y,cx:w.cx,cy:w.cy,controlled:s.targetControlled,input:s.input,index:Wacha24Debug.controllerDiagnostics.input.index};});assert.equal(after.controlled,true);assert.equal(after.index,1);assert.ok(Math.hypot(after.x-before.x,after.y-before.y)>2);assert.equal(before.cx,after.cx);assert.equal(before.cy,after.cy);assert.ok((await page.locator('#control-status').innerText()).includes('操作中'));checks.push('input from the second controller takes over the target while an idle first controller cannot mask it; search camera remains independent');
  await page.evaluate(()=>{window.mockPads[1].axes=[0,0];window.mockPads[1].buttons[15].pressed=true;});await page.waitForFunction(()=>Wacha24Debug.state.input.x===1&&Wacha24Debug.state.input.y===0);checks.push('D-pad works as movement without analog-stick input');
  await page.evaluate(()=>{window.mockPads[1].buttons[15].pressed=false;});await page.waitForFunction(()=>Wacha24Debug.state.input.x===0);await page.waitForTimeout(500);assert.equal(await page.evaluate(()=>Wacha24Debug.state.targetControlled),true);await page.evaluate(()=>WachaExpedition.step(Wacha24Debug.state,8.1));await page.waitForFunction(()=>!Wacha24Debug.state.targetControlled);assert.equal(await page.evaluate(()=>Wacha24Debug.state.status),'playing');checks.push('short rests retain manual control and eight seconds of inactivity returns the resident to AI without stopping play');
  await page.evaluate(()=>window.mockPads[0].axes=[-.75,.3]);await page.waitForFunction(()=>Wacha24Debug.state.targetControlled);await page.evaluate(()=>window.mockPads=[]);await page.waitForFunction(()=>!Wacha24Debug.state.targetControlled);const disconnected=await page.evaluate(()=>Wacha24Debug.state.remaining);await page.waitForTimeout(300);assert.equal(await page.evaluate(()=>Wacha24Debug.state.status),'playing');assert.ok(await page.evaluate(()=>Wacha24Debug.state.remaining)<disconnected);assert.equal(await page.locator('#dialog').isVisible(),false);checks.push('unplugging a controller returns to AI immediately and the timer continues');
  await page.locator('#pause-button').click();const paused=await page.evaluate(()=>({time:Wacha24Debug.state.remaining,people:Wacha24Debug.state.people.map(p=>[p.x,p.y])}));await page.waitForTimeout(300);assert.deepEqual(await page.evaluate(()=>({time:Wacha24Debug.state.remaining,people:Wacha24Debug.state.people.map(p=>[p.x,p.y])})),paused);await page.keyboard.press('p');await page.waitForFunction(()=>Wacha24Debug.state.status==='playing');checks.push('the visible pause button freezes the clock and all residents; P resumes');await page.screenshot({path:'assets/production/review/automatic-controller-s01.png'});
  await page.locator('#game-actions [data-action=leave]').click();await page.locator('[data-action=stage][data-id="23"]').click();await page.waitForSelector('[data-action=begin]',{timeout:90000});assert.equal(await page.locator('[data-action=begin]').isEnabled(),true);await page.locator('[data-action=begin]').click();await page.waitForFunction(()=>Wacha24Debug.state.status==='playing');assert.equal(await page.evaluate(()=>Wacha24Debug.state.people.length),2000);checks.push('the 2,000-resident final town starts on one screen without a private window');
  await page.locator('#pause-button').click();const popupPromise=context.waitForEvent('page');await page.locator('[data-action=runner]').click();const runner=await popupPromise;runner.on('pageerror',e=>errors.push(e.message));await runner.waitForSelector('#runner-banner');await page.locator('[data-action=resume]').click();await page.waitForFunction(()=>Wacha24Debug.state.status==='playing');await runner.waitForFunction(()=>Wacha24Debug.state?.status==='playing',null,{timeout:90000});assert.equal(await runner.locator('#target-peek').isVisible(),false);assert.equal(await runner.locator('#game-actions').isVisible(),false);assert.equal(await runner.evaluate(()=>Wacha24Debug.state.targetType),await page.evaluate(()=>Wacha24Debug.state.targetType));
  await runner.evaluate(()=>{window.mockPads=[makePad(0)];window.mockPads[0].axes=[.8,.4];});await page.waitForFunction(()=>Wacha24Debug.state.targetControlled);await runner.screenshot({path:'assets/production/review/private-runner.png'});checks.push('an optional private view follows the same target and forwards controller input');await runner.close();await page.waitForFunction(()=>!Wacha24Debug.state.targetControlled,null,{timeout:10000});assert.equal(await page.evaluate(()=>Wacha24Debug.state.status),'playing');assert.equal(await page.evaluate(()=>Wacha24Debug.state.targetControlled),false);checks.push('closing the optional private window returns to AI and never blocks or pauses the main game');
  await page.evaluate(()=>window.blockPads=true);await page.waitForFunction(()=>Wacha24Debug.controllerDiagnostics.blocked);assert.equal(await page.evaluate(()=>Wacha24Debug.state.status),'playing');await page.locator('#pause-button').click();await page.locator('[data-action=controller]').click();assert.ok((await page.locator('#dialog-body').innerText()).includes('制限されています'));await page.locator('[data-action=resume]').click();await page.waitForFunction(()=>Wacha24Debug.state.status==='playing');checks.push('a browser Gamepad permission error shows actionable connection help and never crashes the game');
  await page.evaluate(()=>{Wacha24Debug.state.remaining=29;});await page.waitForFunction(()=>document.getElementById('timer-panel').classList.contains('urgent'));const displayedTimer=await page.evaluate(()=>({text:document.getElementById('time-left').textContent,remaining:Wacha24Debug.state.remaining}));assert.ok(displayedTimer.remaining>0&&displayedTimer.remaining<=29);assert.equal(displayedTimer.text,'00:'+String(Math.ceil(displayedTimer.remaining)).padStart(2,'0'));await page.setViewportSize({width:390,height:844});await page.waitForTimeout(300);for(const sel of ['#target-peek','#time-left','#game-actions [data-action=leave]','#pause-button','#camera-button']){assert.equal(await page.locator(sel).isVisible(),true);const b=await page.locator(sel).boundingBox();assert.ok(b.x>=0&&b.y>=0&&b.x+b.width<=390&&b.y+b.height<=844,sel+' must remain in the mobile viewport');}await page.screenshot({path:'assets/production/review/automatic-controller-mobile.png'});checks.push('target, live countdown, urgent time, pause, leave, and camera remain visible on a narrow phone screen');
  await page.locator('#pause-button').click();await page.locator('[data-action=quit]').click();assert.equal(await page.evaluate(()=>Wacha24Debug.state),null);assert.equal(await page.locator('#lobby').isVisible(),true);assert.ok((await page.locator('#dialog-body').innerText()).includes('ゲームを終了しました'));checks.push('quit clears the active game and returns to the town list');
  await page.locator('[data-action=dismiss]').click();await page.setViewportSize({width:1440,height:900});await page.locator('[data-action=stage][data-id="0"]').click();await page.waitForSelector('[data-action=begin]',{timeout:90000});const pausedDuringCountdown=await page.evaluate(()=>{document.querySelector('[data-action=begin]').click();const active=!!Wacha24Debug.countdown;document.querySelector('#pause-button').click();return active;});assert.equal(pausedDuringCountdown,true);assert.equal(await page.locator('#start-countdown').isVisible(),false);await page.waitForTimeout(3200);assert.equal(await page.evaluate(()=>Wacha24Debug.state.remaining),180);assert.equal(await page.evaluate(()=>Wacha24Debug.state.status),'ready');await page.locator('[data-action=resume]').click();await page.waitForFunction(()=>!!Wacha24Debug.countdown);await page.waitForFunction(()=>{const a=Wacha24Sound.getState();return !a.paused&&a.events.lastIndexOf('countdown')>a.events.lastIndexOf('pause');});await page.locator('#game-actions [data-action=leave]').click();await page.waitForTimeout(3200);assert.equal(await page.evaluate(()=>Wacha24Debug.state),null);assert.equal(await page.locator('#start-countdown').isVisible(),false);checks.push('pause cancels a pending start, resume restores countdown audio, and leave prevents starting an abandoned game');
  assert.deepEqual(errors,[]);const report={at:new Date().toISOString(),checks,errors,method:'simulated Gamepad API; macOS HID scan detected no connected gamepad, and the registered Pro Controller was disconnected; physical input not verified'};fs.writeFileSync('assets/production/review/duo-browser-report.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report));
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
