const {chromium}=require('playwright'),assert=require('node:assert/strict'),path=require('node:path'),fs=require('node:fs');
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',args:['--allow-file-access-from-files']});
 try{
  const context=await browser.newContext({viewport:{width:1440,height:900}});await context.addInitScript(()=>{window.mockPad={connected:true,axes:[0,0],buttons:Array.from({length:16},()=>({pressed:false,value:0})),id:'QA simulated Switch-compatible gamepad',index:0,mapping:'standard'};Object.defineProperty(navigator,'getGamepads',{value:()=>[window.mockPad.connected?window.mockPad:null]});});
  const page=await context.newPage(),checks=[],errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('file://'+path.resolve('expedition/index.html'));await page.locator('input[name=mode][value=duo]').check();
  await page.locator('[data-action=stage][data-id="0"]').click();await page.waitForSelector('[data-action=begin]',{timeout:90000});await page.locator('[data-action=begin]').click();await page.waitForFunction(()=>Wacha24Debug.state.status==='playing');
  const before=await page.evaluate(()=>{const {state:s,world:w}=Wacha24Debug,p=s.people[s.targetId];window.mockPad.axes=[.8,.4];return{x:p.x,y:p.y,cx:w.cx,cy:w.cy};});await page.waitForTimeout(500);
  const after=await page.evaluate(()=>{const {state:s,world:w}=Wacha24Debug,p=s.people[s.targetId];window.mockPad.axes=[0,0];return{x:p.x,y:p.y,cx:w.cx,cy:w.cy};});assert.ok(Math.hypot(after.x-before.x,after.y-before.y)>2);assert.equal(before.cx,after.cx);assert.equal(before.cy,after.cy);checks.push('gamepad moves only the runner; search camera stays independent');
  await page.evaluate(()=>window.mockPad.connected=false);await page.waitForFunction(()=>Wacha24Debug.state.status==='paused');const paused=await page.evaluate(()=>({remaining:Wacha24Debug.state.remaining,positions:Wacha24Debug.state.people.map(p=>[p.x,p.y])}));await page.waitForTimeout(350);assert.deepEqual(await page.evaluate(()=>({remaining:Wacha24Debug.state.remaining,positions:Wacha24Debug.state.people.map(p=>[p.x,p.y])})),paused);assert.ok((await page.locator('#dialog-body').innerText()).includes('コントローラーが外れました'));checks.push('disconnect pauses both players and the timer with visible feedback');
  await page.evaluate(()=>window.mockPad.connected=true);await page.locator('[data-action=resume]').click();await page.waitForFunction(()=>Wacha24Debug.state.status==='playing');checks.push('reconnection resumes the same game');
  await page.locator('#pause-button').click();await page.locator('[data-action=leave]').click();
  const big=await page.evaluate(()=>WACHA24_DATA.stages.filter(s=>s.ready&&s.area>1).sort((a,b)=>b.population-a.population)[0]?.id);assert.notEqual(big,undefined,'requires a completed large-map stage');await page.locator(`[data-action=stage][data-id="${big}"]`).click();await page.waitForSelector('[data-action=runner]');const popupPromise=context.waitForEvent('page');await page.locator('[data-action=runner]').click();const runner=await popupPromise;runner.on('pageerror',e=>errors.push(e.message));await runner.waitForSelector('#runner-banner');await page.waitForTimeout(500);
  await runner.evaluate(()=>{const prepare=Wacha24Art.prepare;Wacha24Art.prepare=async function(...args){await new Promise(resolve=>window.releaseRunnerArt=resolve);return prepare(...args);};});
  await page.locator(`[data-action=stage][data-id="${big}"]`).click();await page.waitForSelector('[data-action=begin]',{timeout:90000});await runner.waitForFunction(()=>typeof window.releaseRunnerArt==='function');assert.equal(await page.locator('[data-action=begin]').isDisabled(),true);assert.ok((await page.locator('[data-action=begin]').innerText()).includes('準備中'));await runner.evaluate(()=>window.opener.postMessage({type:'wacha-scene-ready',token:location.hash.slice(1),sceneKey:'previous-scene'},'*'));await page.evaluate(()=>Wacha24Debug.resume());assert.equal(await page.locator('[data-action=resume]').isDisabled(),true);const loading=await page.evaluate(()=>({status:Wacha24Debug.state.status,remaining:Wacha24Debug.state.remaining,positions:Wacha24Debug.state.people.map(p=>[p.x,p.y])}));assert.equal(loading.status,'ready');assert.equal(loading.remaining,180);await page.waitForTimeout(600);assert.deepEqual(await page.evaluate(()=>({status:Wacha24Debug.state.status,remaining:Wacha24Debug.state.remaining,positions:Wacha24Debug.state.people.map(p=>[p.x,p.y])})),loading);await runner.evaluate(()=>window.releaseRunnerArt());await page.waitForSelector('[data-action=resume]:not([disabled])',{timeout:90000});assert.equal(await page.evaluate(()=>Wacha24Debug.state.remaining),180);checks.push('delayed private artwork blocks both begin and resume, freezes both players, and ignores stale readiness messages');await page.locator('[data-action=resume]').click();await page.waitForFunction(()=>Wacha24Debug.state.status==='playing');await runner.waitForFunction(()=>Wacha24Debug.state?.status==='playing',{timeout:90000});
  const same=await Promise.all([page.evaluate(()=>Wacha24Debug.state.targetType),runner.evaluate(()=>Wacha24Debug.state.targetType)]);assert.equal(same[0],same[1]);assert.equal(await runner.locator('#target-peek').isVisible(),false);checks.push('private runner window loads the identical cast and target on the large map');await runner.screenshot({path:'assets/production/review/private-runner.png'});
  const remoteBefore=await page.evaluate(()=>{const s=Wacha24Debug.state,p=s.people[s.targetId];return{x:p.x,y:p.y,cx:Wacha24Debug.world.cx,cy:Wacha24Debug.world.cy};});await runner.evaluate(()=>window.mockPad.axes=[.8,.4]);await page.waitForTimeout(500);await runner.evaluate(()=>window.mockPad.axes=[0,0]);const remoteAfter=await page.evaluate(()=>{const s=Wacha24Debug.state,p=s.people[s.targetId];return{x:p.x,y:p.y,cx:Wacha24Debug.world.cx,cy:Wacha24Debug.world.cy};});assert.ok(Math.hypot(remoteAfter.x-remoteBefore.x,remoteAfter.y-remoteBefore.y)>2,'private-window input cannot be masked by an idle local gamepad');assert.equal(remoteAfter.cx,remoteBefore.cx);assert.equal(remoteAfter.cy,remoteBefore.cy);checks.push('the private-window controller drives the runner on the 2000-person map while the search camera stays fixed');
  await runner.close();await page.waitForFunction(()=>Wacha24Debug.state.status==='paused');await page.locator('[data-action=resume]').click();assert.equal(await page.evaluate(()=>Wacha24Debug.state.status),'paused');await page.waitForSelector('[data-action=runner]');checks.push('closing the private window pauses the large-map game and blocks blind resume');
  const reopenPromise=context.waitForEvent('page');await page.locator('[data-action=runner]').click();const reopened=await reopenPromise;reopened.on('pageerror',e=>errors.push(e.message));await reopened.waitForSelector('#runner-banner');await page.waitForSelector('[data-action=resume]');await page.locator('[data-action=resume]').click();await page.waitForFunction(()=>Wacha24Debug.state.status==='playing');await reopened.waitForFunction(()=>Wacha24Debug.state?.status==='playing',{timeout:90000});checks.push('reopening the private window restores an explicit resume button and the same game');
  await page.evaluate(()=>{const s=Wacha24Debug.state;WachaExpedition.touch(s,s.people.find(p=>p.photographer).id);Wacha24Debug.camera();Wacha24Debug.camera();});await page.waitForFunction(()=>WachaExpedition.photoReady(Wacha24Debug.state,0));await page.evaluate(()=>Wacha24Debug.pause());await reopened.close();await page.waitForSelector('[data-action=photo]');await page.locator('[data-action=photo]').click();assert.equal(await page.evaluate(()=>Wacha24Debug.state.status),'paused');assert.equal(await page.locator('#photo-view').isVisible(),false);checks.push('a saved-photo button cannot resume play after the private window closes');
  assert.deepEqual(errors,[]);const report={at:new Date().toISOString(),checks,errors,method:'simulated Gamepad API; physical controller not available'};fs.writeFileSync('assets/production/review/duo-browser-report.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report));
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
