const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs'),path=require('node:path');
const {pathToFileURL}=require('node:url');
const dir=path.resolve(__dirname,'../test-results'),url=pathToFileURL(path.resolve(__dirname,'../index.html')).href;
fs.mkdirSync(dir,{recursive:true});const errors=[],remote=[],results=[];let browser;
const snapshot=p=>p.evaluate(()=>WachaGame.snapshot());
const click=(p,text)=>p.getByRole('button',{name:text,exact:true}).click();
const shot=(p,name)=>p.screenshot({path:path.join(dir,name+'.png'),fullPage:true});
async function check(name,fn){await fn();results.push({name,passed:true});console.log('PASS '+name);}
async function load(p){p.on('pageerror',e=>errors.push(e.message));p.on('request',r=>{if(/^https?:/.test(r.url()))remote.push(r.url());});await p.goto(url,{timeout:60000});await p.waitForFunction(()=>window.WachaGame?.snapshot().ready,undefined,{timeout:60000});}
async function targetClick(p,id){const s=await snapshot(p),who=s.people.find(x=>x.id===(id??s.targetId)),r=await p.locator('#world').boundingBox();const x=(who.x-s.view.cx)*s.view.scale+s.view.width/2,y=(who.y-18-s.view.cy)*s.view.scale+s.view.height/2;await p.mouse.click(r.x+x,r.y+y);}
(async()=>{
 browser=await chromium.launch({channel:'chrome',headless:true});const context=await browser.newContext({viewport:{width:1440,height:1080},deviceScaleFactor:1});const page=await context.newPage();await load(page);
 await check('Offline standalone home opens with all 320 cached sprite variants',async()=>{assert.equal((await snapshot(page)).screen,'home');assert.equal(await page.evaluate(()=>WachaArt.spriteCount),320);assert.equal(remote.length,0);await shot(page,'01-home');});
 await check('All seven distinct scenes are selectable',async()=>{await click(page,'7つの街');assert.equal(await page.locator('.stage-card').count(),7);await shot(page,'02-stages');});
 await check('Collection displays all 16 archetypes and 20 color variants',async()=>{await click(page,'住人ずかん');assert.equal(await page.locator('#character-tabs button').count(),16);assert.equal(await page.locator('.character-card').count(),20);await click(page,'シェフ');await shot(page,'03-collection');const hashes=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=80;c.height=96;const x=c.getContext('2d');return Array.from({length:320},(_,type)=>{WachaArt.portrait(c,type,0);return c.toDataURL();});});assert.equal(new Set(hashes).size,320);});
 await check('Scene 1 starts with exactly 600 moving people and 180-second limit',async()=>{await click(page,'7つの街');await page.locator('[data-stage="0"]').click();let s=await snapshot(page);assert.equal(s.status,'ready');assert.equal(s.count,600);assert.equal(s.types,320);assert.equal(s.remaining,180);await shot(page,'04-ready');await click(page,'準備OK、さがそう！');s=await snapshot(page);const initial=s.people;await page.waitForTimeout(700);s=await snapshot(page);assert.equal(s.status,'playing');assert.equal(s.rendered,600);assert.ok(s.remaining<=180&&s.remaining>178);assert.ok(s.people.filter((p,i)=>Math.hypot(p.x-initial[i].x,p.y-initial[i].y)>.5).length>300);assert.ok(s.life.counts.shopping>0);assert.ok(s.life.counts.fishing>0);await shot(page,'05-gameplay');});
 await check('Zoom, pan, fit and pause/resume work',async()=>{await page.getByRole('button',{name:'拡大',exact:true}).click();assert.ok((await snapshot(page)).zoom>1);const r=await page.locator('#world').boundingBox();await page.mouse.move(r.x+r.width/2,r.y+r.height/2);await page.mouse.down();await page.mouse.move(r.x+r.width/2-130,r.y+r.height/2-60,{steps:6});await page.mouse.up();await shot(page,'06-zoom');await page.getByRole('button',{name:'全体表示に戻す'}).click();assert.equal((await snapshot(page)).zoom,1);await page.keyboard.press('Escape');const rem=(await snapshot(page)).remaining;await page.waitForTimeout(300);assert.equal((await snapshot(page)).remaining,rem);await shot(page,'07-pause');await click(page,'おさんぽを続ける');assert.equal((await snapshot(page)).status,'playing');});
 await check('Wrong target and hint apply penalties, correct target clears and saves result',async()=>{let s=await snapshot(page);const wrong=s.people.find(p=>p.id!==s.targetId&&Math.hypot(p.x-s.people[s.targetId].x,p.y-s.people[s.targetId].y)>80);await targetClick(page,wrong.id);let after=await snapshot(page);assert.ok(after.remaining<s.remaining-2.8);await page.locator('#hint-button').click();after=await snapshot(page);assert.ok(after.remaining<s.remaining-12.8);assert.ok(await page.locator('#hint-button').isDisabled());await targetClick(page);await page.waitForFunction(()=>WachaGame.snapshot().status==='won');await shot(page,'08-clear');assert.equal((await snapshot(page)).records[0].cleared,true);});
 await check('Every other scene renders 600 residents; next/retry navigation works',async()=>{await click(page,'次の街へ →');assert.equal((await snapshot(page)).stage,1);await click(page,'準備OK、さがそう！');await shot(page,'09-garden');await page.keyboard.press('Escape');await click(page,'街をえらぶ');for(let n=2;n<7;n++){await page.locator(`[data-stage="${n}"]`).click();await click(page,'準備OK、さがそう！');await page.waitForTimeout(70);const s=await snapshot(page);assert.equal(s.count,600);assert.equal(s.rendered,600);assert.equal(s.types,320);assert.equal(s.stage,n);await shot(page,`stage-${n+1}`);await page.keyboard.press('Escape');await click(page,'街をえらぶ');}});
 await check('Timer expires in browser at three minutes, and result offers restart',async()=>{await page.clock.install();await page.clock.pauseAt(new Date());await page.locator('[data-stage="4"]').click();await page.clock.runFor(30);await click(page,'準備OK、さがそう！');await page.clock.fastForward(179900);assert.equal((await snapshot(page)).status,'playing');await page.clock.fastForward(320);assert.equal((await snapshot(page)).status,'lost');await shot(page,'10-timeout');await click(page,'もう一度さがす');assert.equal((await snapshot(page)).remaining,180);assert.equal((await snapshot(page)).count,600);});
 await check('Record persists after reload',async()=>{await page.clock.resume();const another=await context.newPage();await load(another);assert.equal((await snapshot(another)).records[0].cleared,true);await another.close();});
 const mobile=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:1,isMobile:true,hasTouch:true});const phone=await mobile.newPage();await load(phone);
 await check('Mobile home and gameplay fit screen with touch zoom controls',async()=>{await shot(phone,'11-mobile-home');assert.ok(await phone.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await click(phone,'さがしにいこう ↗');await click(phone,'準備OK、さがそう！');await phone.getByRole('button',{name:'拡大',exact:true}).tap();assert.ok((await snapshot(phone)).zoom>1);await shot(phone,'12-mobile-game');assert.ok(await phone.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));});
 assert.deepEqual(errors,[]);assert.deepEqual(remote,[]);fs.writeFileSync(path.join(dir,'browser-report.json'),JSON.stringify({results,errors,externalRequests:remote},null,2));console.log(`${results.length} browser checks passed`);await browser.close();
})().catch(async e=>{console.error(e);fs.writeFileSync(path.join(dir,'browser-report.json'),JSON.stringify({results,errors,failure:String(e)},null,2));if(browser)await browser.close();process.exit(1);});
