const {chromium}=require('playwright');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {pathToFileURL}=require('node:url');
const dir=path.resolve(__dirname,'../test-results'),url=pathToFileURL(path.resolve(__dirname,'../index.html')).href;
fs.mkdirSync(dir,{recursive:true});const errors=[],remote=[],results=[];let browser;
const snapshot=p=>p.evaluate(()=>WachaGame.snapshot());
const click=(p,text)=>p.getByRole('button',{name:text,exact:true}).click();
const shot=(p,name)=>p.screenshot({path:path.join(dir,name+'.png'),fullPage:true});
async function check(name,fn){await fn();results.push({name,passed:true});console.log('PASS '+name);}
async function load(p){p.on('pageerror',e=>errors.push(e.message));p.on('request',r=>{if(/^https?:/.test(r.url()))remote.push(r.url());});await p.goto(url,{timeout:50000});await p.waitForFunction(()=>window.WachaGame?.snapshot().ready,undefined,{timeout:50000});}
async function targetClick(p,id){const s=await snapshot(p),who=s.people.find(x=>x.id===(id??s.targetId)),r=await p.locator('#world').boundingBox();const x=(who.x-s.view.cx)*s.view.scale+s.view.width/2,y=(who.y-18*(who.height||1)-s.view.cy)*s.view.scale+s.view.height/2;await p.mouse.click(r.x+x,r.y+y);}
(async()=>{
 browser=await chromium.launch({channel:'chrome',headless:true});const context=await browser.newContext({viewport:{width:1672,height:941},deviceScaleFactor:1});const page=await context.newPage();await load(page);
 await check('Offline home opens with 250 archetypes and 1000 visual variants',async()=>{assert.equal((await snapshot(page)).screen,'home');assert.equal((await snapshot(page)).baseTypes,250);assert.equal(await page.evaluate(()=>WachaArt.spriteCount),1000);assert.equal(remote.length,0);await shot(page,'01-home');});
 await check('Seven scenes and all character groups are available; 1000 portraits are visually distinct',async()=>{await click(page,'7つの街');assert.equal(await page.locator('.stage-card').count(),7);await shot(page,'02-stages');await click(page,'住人ずかん');assert.equal(await page.locator('#character-tabs button').count(),26);await click(page,'年齢・体格');assert.equal(await page.locator('.character-card').count(),32);await shot(page,'03-collection');const hashes=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=100;c.height=120;return Array.from({length:1000},(_,type)=>{WachaArt.portrait(c,type,0);return c.toDataURL();});});assert.equal(new Set(hashes).size,1000);});
 await check('500 residents start with many activities and a three-minute limit; search has no visible UI',async()=>{await click(page,'7つの街');await page.locator('[data-stage="0"]').click();let s=await snapshot(page);assert.equal(s.status,'ready');assert.equal(s.count,500);assert.equal(s.types,500);assert.equal(s.remaining,180);assert.ok(s.life.counts.walk<110);await shot(page,'04-ready');await click(page,'準備OK、さがそう！');const initial=(await snapshot(page)).people;await page.waitForTimeout(700);s=await snapshot(page);assert.equal(s.status,'playing');assert.equal(s.rendered,500);assert.ok(s.remaining<180&&s.remaining>178);assert.ok(s.people.filter((p,i)=>Math.hypot(p.x-initial[i].x,p.y-initial[i].y)>.2).length>20);assert.ok(s.people.filter((p,i)=>p.phase!==initial[i].phase).length>490);const ui=await page.evaluate(()=>{const r=document.querySelector('#world').getBoundingClientRect();return{rect:[r.x,r.y,r.width,r.height],viewport:[0,0,innerWidth,innerHeight],visible:['.header','.game-hud','.game-top','.game-bottom','.life-strip','.world-label','.zoom-controls','.toast'].filter(sel=>document.querySelector(sel).getBoundingClientRect().height>0),gl:document.querySelector('#world').getContext('webgl2')?.getError()};});assert.deepEqual(ui.rect,ui.viewport);assert.deepEqual(ui.visible,[]);assert.equal(ui.gl,0);await shot(page,'05-gameplay');});
 await check('Keyboard zoom, drag, reset and pause keep the screen clear',async()=>{await page.keyboard.press('+');assert.ok((await snapshot(page)).zoom>1);const r=await page.locator('#world').boundingBox();await page.mouse.move(r.width/2,r.height/2);await page.mouse.down();await page.mouse.move(r.width/2-130,r.height/2-60,{steps:6});await page.mouse.up();await shot(page,'06-zoom');await page.keyboard.press('0');assert.equal((await snapshot(page)).zoom,1);await page.keyboard.press('Escape');assert.equal((await snapshot(page)).status,'paused');const rem=(await snapshot(page)).remaining;await page.waitForTimeout(300);assert.equal((await snapshot(page)).remaining,rem);assert.ok(await page.locator('#dialog-portrait').isVisible());await shot(page,'07-pause');await click(page,'おさんぽを続ける');assert.equal((await snapshot(page)).status,'playing');});
 await check('Photo pixels omit every other person and reveal nothing when the target is outside the crop',async()=>{
  const result=await page.evaluate(()=>{
   const C=WachaCore,A=WachaArt,s=C.create(0,999),p=s.people[s.targetId];p.x=800;p.y=700;s.life.props=[];s.life.rides=[];const view={scale:1,dpr:1,visible:()=>true,prop:A.World.prototype.prop,ambient:A.World.prototype.ambient},photo=rect=>A.World.prototype.photo.call(view,s,rect).toDataURL();
   const area={x:700,y:600,w:200,h:160},first=photo(area);for(const q of s.people)if(q.id!==s.targetId){q.x=800;q.y=700;q.type=(q.type+77)%1000;}const othersChanged=photo(area);p.x=-1000;p.y=-1000;const empty=photo(area);p.x=800;p.y=700;const outside=photo({x:0,y:0,w:200,h:160});p.x=-1000;p.y=-1000;const outsideEmpty=photo({x:0,y:0,w:200,h:160});return{sameDespiteOthers:first===othersChanged,targetVisible:first!==empty,outsideEmpty:outside===outsideEmpty};
  });assert.deepEqual(result,{sameDespiteOthers:true,targetVisible:true,outsideEmpty:true});
 });
 await check('Wrong taps cost three seconds; three photos each develop after three seconds and capture the selected region',async()=>{
  let s=await snapshot(page);const target=s.people[s.targetId],wrong=s.people.find(p=>p.id!==s.targetId&&p.height>=1&&Math.hypot(p.x-target.x,p.y-target.y)>80);await targetClick(page,wrong.id);let after=await snapshot(page);assert.ok(after.remaining<s.remaining-2.8);
  await page.clock.install();await page.clock.pauseAt(new Date());await page.keyboard.press('Escape');await click(page,'おさんぽを続ける');
  for(let id=0;id<3;id++){
   await page.keyboard.press('c');s=await snapshot(page);assert.ok(s.camera);assert.ok(Math.abs(s.camera.w*s.camera.h/(s.view.width*s.view.height)-.1)<1e-8);
   const target=s.people[s.targetId],x=(target.x-s.view.cx)*s.view.scale+s.view.width/2,y=(target.y-18*target.height-s.view.cy)*s.view.scale+s.view.height/2;await page.mouse.move(id===0?x:80,id===0?y:80);await page.keyboard.press('c');s=await snapshot(page);assert.equal(s.photos.length,id+1);assert.equal(s.photos[id].ready,false);assert.equal(await page.locator('#photo-mount canvas').count(),0);await page.keyboard.press('c');assert.equal((await snapshot(page)).photos.length,id+1);
   await page.clock.fastForward(2900);assert.equal((await snapshot(page)).photos[id].ready,false);assert.equal((await snapshot(page)).status,'playing');await page.clock.fastForward(150);assert.equal((await snapshot(page)).photos[id].ready,true);assert.equal((await snapshot(page)).status,'paused');assert.ok(await page.locator('#photo-mount canvas').isVisible());if(id===0)await shot(page,'14-photo-developed');const image=await page.locator('#photo-mount canvas').evaluate(c=>c.toDataURL());await page.clock.fastForward(500);assert.equal(await page.locator('#photo-mount canvas').evaluate(c=>c.toDataURL()),image);await click(page,'街へ戻って探す');
  }
  await page.keyboard.press('c');assert.equal((await snapshot(page)).camera,null);assert.equal((await snapshot(page)).photos.length,3);await page.clock.resume();await targetClick(page);await page.waitForFunction(()=>WachaGame.snapshot().status==='won');await shot(page,'08-clear');assert.equal((await snapshot(page)).records[0].cleared,true);
 });
 await check('All seven scenes retain 500 agents, 500 looks, and a full-viewport world',async()=>{await click(page,'次の街へ →');assert.equal((await snapshot(page)).stage,1);await click(page,'準備OK、さがそう！');await shot(page,'09-garden');await page.keyboard.press('Escape');await click(page,'街をえらぶ');for(let n=2;n<7;n++){await page.locator(`[data-stage="${n}"]`).click();await click(page,'準備OK、さがそう！');await page.waitForTimeout(90);const s=await snapshot(page);assert.equal(s.count,500);assert.equal(s.rendered,500);assert.equal(s.types,500);assert.equal(s.stage,n);assert.ok(Object.keys(s.life.counts).length>55);await shot(page,`stage-${n+1}`);await page.keyboard.press('Escape');await click(page,'街をえらぶ');}});
 await check('Browser timer expires at three minutes and restart resets the game',async()=>{await page.clock.install();await page.clock.pauseAt(new Date());await page.locator('[data-stage="4"]').click();await page.clock.runFor(30);await click(page,'準備OK、さがそう！');await page.clock.fastForward(179900);assert.equal((await snapshot(page)).status,'playing');await page.clock.fastForward(320);assert.equal((await snapshot(page)).status,'lost');await shot(page,'10-timeout');await click(page,'もう一度さがす');assert.equal((await snapshot(page)).remaining,180);assert.equal((await snapshot(page)).count,500);assert.equal((await snapshot(page)).photos.length,0);});
 await check('Clear record persists after reload',async()=>{await page.clock.resume();const another=await context.newPage();await load(another);assert.equal((await snapshot(another)).records[0].cleared,true);await another.close();});
 const mobile=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:1,isMobile:true,hasTouch:true});const phone=await mobile.newPage();await load(phone);
 await check('Portrait mobile search fills the viewport and supports pinch zoom without buttons',async()=>{await shot(phone,'11-mobile-home');assert.ok(await phone.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await click(phone,'さがしにいこう ↗');await click(phone,'準備OK、さがそう！');const s=await snapshot(phone);assert.equal(s.view.width,390);assert.equal(s.view.height,844);assert.equal(s.zoom,1);const cdp=await mobile.newCDPSession(phone);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:140,y:400,id:1},{x:240,y:400,id:2}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:80,y:400,id:1},{x:300,y:400,id:2}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert.ok((await snapshot(phone)).zoom>1.4);await shot(phone,'12-mobile-game');assert.equal((await snapshot(phone)).status,'playing');});
 await check('Mobile camera supports choosing a frame, taking a photo, and returning to the live town',async()=>{
  await phone.locator('#camera-button').tap();assert.ok((await snapshot(phone)).camera);await phone.touchscreen.tap(195,340);let s=await snapshot(phone);assert.ok(Math.abs(s.camera.x+s.camera.w/2-195)<1);await phone.locator('#camera-button').tap();assert.equal((await snapshot(phone)).photos.length,1);await phone.waitForTimeout(3100);assert.equal((await snapshot(phone)).status,'paused');assert.ok(await phone.locator('#photo-mount canvas').isVisible());await shot(phone,'15-mobile-photo');await click(phone,'街へ戻って探す');assert.equal((await snapshot(phone)).status,'playing');
 });
 await check('Two-finger hold opens pause and target reference on mobile',async()=>{const cdp=await mobile.newCDPSession(phone);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:140,y:400,id:1},{x:240,y:400,id:2}]});await phone.waitForTimeout(800);await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert.equal((await snapshot(phone)).status,'paused');assert.ok(await phone.locator('#dialog-portrait').isVisible());await shot(phone,'13-mobile-pause');});
 assert.deepEqual(errors,[]);assert.deepEqual(remote,[]);fs.writeFileSync(path.join(dir,'browser-report.json'),JSON.stringify({results,errors,externalRequests:remote},null,2));console.log(`${results.length} browser checks passed`);await browser.close();
})().catch(async e=>{console.error(e);fs.writeFileSync(path.join(dir,'browser-report.json'),JSON.stringify({results,errors,failure:String(e)},null,2));if(browser)await browser.close();process.exit(1);});
