const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const C=require('../src/expedition-core.js'),context={window:{}};vm.runInNewContext(fs.readFileSync(require('node:path').join(__dirname,'../expedition/data.js'),'utf8'),context);const D=context.window.WACHA24_DATA;
function corridor(height=1,gap=8){
 const data={...D,characters:D.characters.filter(p=>p.stage==='S01'),stages:[{...D.stages[0],population:100,livingTown:true,activityAreas:[],navigation:[[100,200,[1],0],[300,200,[0],0]],sites:[],vehicles:[]}]},s=C.create(data,0,3);
 s.people=s.people.filter(p=>!p.photographer).slice(0,2);s.people.forEach((p,id)=>Object.assign(p,{id,height,x:100+id*gap,y:200,node:0,layer:0,level:0,station:null,ride:null,path:[],to:null,homeSite:null,compatibleSites:[],exitSite:null,transitSite:null,pendingSite:undefined,activity:'acting',until:1e5,pauseUntil:0,speed:8,pace:.4,wantPace:.4,nextPace:1e5}));
 s.targetId=1;s.rides=[];s.sites=[];s.nextEvent=1e5;s.overlaps.clear();s.stats.maxOverlap=0;C.start(s);C.controlTarget(s,true);C.input(s,0,0);return s;
}
test('a slow resident can leave a narrow dead end within three seconds without pushing the player or crossing the floor boundary',t=>{
 for(const [height,gap] of [[1,8],[1,10],[1.13,10],[1.13,12]]){const s=corridor(height,gap),p=s.people[0],target=s.people[1],fixed=[target.x,target.y];let escaped=false,walked=false;
  for(let tick=0;tick<60;tick++){const wasEscaping=!!p.floorEscape,before=[p.x,p.y];C.step(s,.1);assert.deepEqual([target.x,target.y],fixed,'the stationary player remains fixed');assert.ok(C.canStand(s,p,p.x,p.y),'the escape remains on the measured floor');if(wasEscaping&&p.floorEscape){walked=true;assert.ok(Math.hypot(p.x-before[0],p.y-before[1])<=6.01,'escape advances by walking, not a teleport');}if(!C.overlapPairs(s).some(pair=>pair.d<1))escaped=true;}
  assert.ok(escaped&&walked);assert.ok(s.stats.maxOverlap<3,`${height}/${gap}: overlap ${s.stats.maxOverlap}`);assert.ok(!p.floorEscape,'the resident returns to normal AI after yielding');t.diagnostic(`height ${height}, gap ${gap}: ${s.stats.maxOverlap.toFixed(1)} seconds maximum overlap`);
 }
});
test('controller takeover cancels an active floor escape without imposing automatic movement',()=>{const s=corridor(),p=s.people[0];for(let i=0;i<20&&!p.floorEscape;i++)C.step(s,.1);assert.ok(p.floorEscape);C.controlTarget(s,false);s.targetId=p.id;C.controlTarget(s,true);const fixed=[p.x,p.y];C.input(s,0,0);C.step(s,.1);assert.equal(p.floorEscape,undefined);assert.deepEqual([p.x,p.y],fixed);});

test('the viewport inset never clamps a valid narrow floor position into a wall',()=>{const s=corridor(),p=s.people[0];s.people=[p];s.targetId=0;p.x=100;p.y=12;const g=s.walkable;g.layers[0].fill(0);g.layers[0][Math.floor(p.y/g.unit)*g.cols+Math.floor(p.x/g.unit)]=1;assert.ok(C.canStand(s,p,p.x,p.y));C.step(s,.1);assert.equal(p.y,12);assert.ok(C.canStand(s,p,p.x,p.y));});

test('swimming animals keep their measured water route near the viewport edge',()=>{const s=corridor(),p=s.people[0];s.people=[p];s.targetId=-1;s.targetControlled=false;s.definition={...s.definition,waterPoints:[[100,12],[200,12]]};Object.assign(p,{animal:true,habitat:'water',layer:5,x:100,y:12,travelIndex:0,travelDirection:1});for(let i=0;i<60;i++){C.step(s,.1);assert.equal(p.y,12,'ground inset must not move the animal off its water route');}assert.ok(p.x>100);});

test('stages without a measured water route use land and air animals while preserving the complete unique cast',()=>{for(const index of [2,23])for(const waterPoints of [[],[[100,12]]]){const data={...D,stages:D.stages.map((stage,id)=>id===index?{...stage,waterPoints}:stage)},s=C.create(data,index,246810+index);assert.equal(s.people.filter(p=>p.habitat==='water').length,0);assert.equal(s.people.filter(p=>p.animal).length,18);assert.equal(s.people.length,D.stages[index].population);assert.equal(new Set(s.people.map(p=>p.design)).size,s.people.length);assert.equal(s.people.filter(p=>p.exclusive).length,100);assert.equal(s.people.filter(p=>p.photographer).length,5);}});

test('a walker yields to both passengers of a moving vehicle instead of escaping into the second seat',()=>{const s=corridor(1.13,8),p=s.people[0],a=s.people[1],b={...a,id:2};s.people=[p,a,b];s.targetId=-1;s.targetControlled=false;Object.assign(p,{x:150,y:200,height:1.13,activity:'walking',node:0,to:1,path:[],speed:34,pace:1,wantPace:1,nextPace:1e5});for(const [i,q] of [a,b].entries())Object.assign(q,{x:150+(i-.5)*29,y:181,height:1.13,ride:0,station:null,layer:3,level:0,activity:'riding'});for(const q of s.people){q.lastFloorX=q.x;q.lastFloorY=q.y;}const r={id:0,x:150,y:200,node:0,to:1,path:[],goal:1,speed:34,pace:1,level:0,phase:0,facing:1,activity:'walking',passengers:[1,2],stoppedUntil:-1,nextStop:100,altitude:0,water:false,air:false,streetOnly:true,initialBoarded:true};s.rides=[r];const g=s.walkable;g.layers[0].fill(0);for(let x=100;x<=300;x++)g.layers[0][Math.floor(200/g.unit)*g.cols+Math.floor(x/g.unit)]=1;let separated=false;for(let i=0;i<40;i++){C.step(s,.1);assert.ok(C.canStand(s,p,p.x,p.y));for(const [seat,q] of [a,b].entries()){assert.equal(q.ride,0);assert.equal(q.x,r.x+(seat-.5)*29);assert.equal(q.y,r.y-19);}if(!C.overlapPairs(s).some(pair=>pair.d<1&&(pair.p.id===p.id||pair.q.id===p.id)))separated=true;}assert.ok(separated);assert.ok(s.stats.maxOverlap<3,`moving vehicle overlap ${s.stats.maxOverlap}`);});

test('controller takeover immediately clears a cooperative pause and accepts movement',()=>{const s=corridor(),p=s.people[s.targetId];C.controlTarget(s,false);p.yieldWaitUntil=s.elapsed+1.6;C.controlTarget(s,true);assert.equal(p.yieldWaitUntil,undefined);const x=p.x;C.input(s,1,0);C.step(s,.1);assert.ok(p.x>x+1,'manual input is never held by an AI yielding pause');assert.ok(C.canStand(s,p,p.x,p.y));});
