const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');const path=require('node:path');
const C=require('../src/core.js');
const root=path.resolve(__dirname,'..'),url=require('node:url').pathToFileURL(path.join(root,'index.html')).href;
const out=path.join(root,'test-results');let browser;const results=[],errors=[],requests=[];
async function check(name,fn){await fn();results.push(name);console.log('PASS '+name)}
async function state(p){return p.evaluate(()=>ToiletApp.snapshot())}
async function run(p,ms){await p.clock.runFor(ms)}
async function click(p,name,exact=false){const d=p.getByRole('dialog');await (await d.count()?d:p).getByRole('button',{name,exact}).click()}
async function go(p,target){let s=await state(p);const route=C.path(s.map,s.player,target).slice(1);assert.ok(route.length||C.distance(s.player,target)<.1);for(const point of route){for(const axis of ['x','y'])for(let i=0;i<15;i++){s=await state(p);assert.equal(s.state,'playing');const delta=point[axis]-s.player[axis];if(Math.abs(delta)<.06)break;const k=axis==='x'?(delta>0?'ArrowRight':'ArrowLeft'):(delta>0?'ArrowDown':'ArrowUp');await p.keyboard.down(k);await run(p,Math.max(17,Math.min(150,Math.round(Math.abs(delta)/s.speeds[k]*1000))));await p.keyboard.up(k);}}assert.ok(C.distance((await state(p)).player,target)<.14)}
(async()=>{
 browser=await chromium.launch({channel:'chrome'});const context=await browser.newContext({viewport:{width:1440,height:1000}});const p=await context.newPage();p.on('pageerror',e=>errors.push(e.message));p.on('request',r=>{if(/^https?:/.test(r.url()))requests.push(r.url())});await p.clock.install({time:new Date('2026-09-28T12:00:00Z')});await p.goto(url);await p.clock.pauseAt(new Date('2026-09-28T12:00:01Z'));
 await check('All six generated atlases decode offline from the single HTML',async()=>{await p.waitForFunction(()=>ToiletRender.textures.length===6&&ToiletRender.textures.every(i=>i.complete&&i.naturalWidth>1000));assert.equal((await p.locator('[download]').count()),1);assert.equal(requests.length,0)});
 await click(p,'ステージ選択',true);await p.locator('#map-variation').uncheck();await click(p,'EASY',true);await click(p,'このステージで遊ぶ');await click(p,'準備OK');await run(p,32);
 await check('A broad dungeon and map overlay are playable with the timer paused while reading',async()=>{const s=await state(p);assert.ok(s.map.w*s.map.h>5000);assert.equal(s.features.length,62);assert.equal(s.gates.length,6);await p.keyboard.press('m');let rem=(await state(p)).remaining;await run(p,2000);assert.equal((await state(p)).remaining,rem);await p.screenshot({path:path.join(out,'12-dungeon-map.png'),fullPage:true});await click(p,'探索に戻る')});
 await check('Real keyboard pickup and E interaction unlock a shortcut',async()=>{let s=await state(p);const f=s.features.filter(f=>f.type==='key').sort((a,b)=>C.path(s.map,s.player,a).length-C.path(s.map,s.player,b).length)[0];await go(p,f);await run(p,30);assert.ok((await state(p)).keys>0);
 s=await state(p);const approaches=s.gates.flatMap(g=>g.horizontal?[{x:g.x-2,y:g.y,g},{x:g.x+2,y:g.y,g}]:[{x:g.x,y:g.y-2,g},{x:g.x,y:g.y+2,g}]).filter(a=>C.path(s.map,s.player,a).length).sort((a,b)=>C.path(s.map,s.player,a).length-C.path(s.map,s.player,b).length);const target=approaches[0];await go(p,target);await p.keyboard.press('e');assert.equal((await state(p)).gates[target.g.id].open,true);await p.screenshot({path:path.join(out,'13-shortcut.png'),fullPage:true})});
 await check('Reload and a new browser tab resume the same exact run including opened gates',async()=>{await p.keyboard.press('Escape');const before=await state(p);await p.reload();await run(p,32);assert.ok(await p.getByRole('button',{name:'つづきから'}).isVisible());await click(p,'つづきから');let after=await state(p);assert.equal(after.paused,true);assert.equal(after.remaining,before.remaining);assert.equal(after.seed,before.seed);assert.deepEqual(after.player,before.player);assert.deepEqual(after.gates,before.gates);await click(p,'続ける');await run(p,500);await p.keyboard.press('Escape');
 const q=await context.newPage();await q.goto(url);assert.ok(await q.getByRole('button',{name:'つづきから'}).isVisible());await q.close();await p.bringToFront()});
 await check('Same-map retry preserves seed and new-layout retry changes it',async()=>{const seed=(await state(p)).seed;await click(p,'同じマップでやり直す');await click(p,'準備OK');await run(p,32);assert.equal((await state(p)).seed,seed);await p.keyboard.press('Escape');await click(p,'新しい配置でやり直す');await click(p,'準備OK');await run(p,32);assert.notEqual((await state(p)).seed,seed)});
 await check('All six location themes render distinct generated materials at dungeon size',async()=>{
 for(let i=0;i<6;i++){await p.keyboard.press('Escape');await click(p,'ステージ選択へ');await click(p,C.THEMES[i].name,true);await click(p,'このステージで遊ぶ');await click(p,'準備OK');await run(p,64);assert.equal((await state(p)).map.themeId,i);await p.screenshot({path:path.join(out,`theme-${i+1}.png`),fullPage:true});assert.ok(await p.evaluate(i=>!!ToiletRender.material(i,0)&&!!ToiletRender.material(i,3),i));}
 });
 await check('Reshuffle option changes stage layout on each fresh attempt',async()=>{await p.keyboard.press('Escape');await click(p,'ステージ選択へ');await p.locator('#map-variation').check();await click(p,'このステージで遊ぶ');await click(p,'準備OK');const seed=(await state(p)).seed;await p.keyboard.press('Escape');await click(p,'ステージ選択へ');await click(p,'このステージで遊ぶ');await click(p,'準備OK');assert.notEqual((await state(p)).seed,seed)});
 await check('No script errors or external network dependencies',async()=>{assert.deepEqual(errors,[]);assert.deepEqual(requests,[])});
 fs.writeFileSync(path.join(out,'dungeon-browser-report.json'),JSON.stringify({passed:results.length,failed:0,results,errors,requests},null,2));await browser.close();
})().catch(async e=>{console.error(e);fs.writeFileSync(path.join(out,'dungeon-browser-report.json'),JSON.stringify({passed:results.length,failed:1,results,error:e.stack,errors},null,2));if(browser)await browser.close();process.exit(1)});
