(() => {
  'use strict';
  const B=window.BombStudio, $=id=>document.getElementById(id), $$=selector=>[...document.querySelectorAll(selector)];
  const STORAGE='bomb-studio-v1', C=60, canvas=$('game'), ctx=canvas.getContext('2d');
  let saved={stages:[],characters:[],character:B.PRESETS[0],weapon:'normal',egg:'paku'}, storageAvailable=true;
  const validCharacter=c=>c&&typeof c.name==='string'&&c.name.length<=16&&['dress','pixel'].includes(c.mode)&&['helmet','body','accent'].every(k=>/^#[0-9a-f]{6}$/i.test(c[k]))&&['antenna','cat','crown','leaf','none'].includes(c.accessory)&&(c.mode!=='pixel'||(Array.isArray(c.pixels)&&c.pixels.length===256&&c.pixels.every(p=>p===null||/^#[0-9a-f]{6}$/i.test(p))));
  try{const data=JSON.parse(localStorage.getItem(STORAGE)||'null');if(data){saved.stages=(data.stages||[]).filter(s=>!B.validateStage(s)&&typeof s.id==='string'&&typeof s.name==='string').slice(0,12);saved.characters=(data.characters||[]).filter(validCharacter).slice(0,16);if(validCharacter(data.character))saved.character=data.character;if(B.WEAPONS[data.weapon])saved.weapon=data.weapon;if(B.EGGS[data.egg])saved.egg=data.egg;}}catch{storageAvailable=false;}
  let selectedStage=B.createStage('garden',17), currentView='play', game, particles=[], soundOn=false,audio;
  let draft=B.clone(selectedStage), draftId=null, brush='crate',stageUndo=[], paintingStage=false,lastStageCell='';
  let character=B.clone(saved.character),characterId=saved.characters.some(c=>c.id===character.id)?character.id:null,eraser=false,pixelUndo=[],paintingPixel=false,lastPixelCell='';
  let pressed=new Map(),touchDirection=null,lastTime=0,toastTimer,eggPulse=0,shake=0;
  const colors=['#fff9ed','#f4bdd1','#b9e4c4','#bfc8eb','#7161e8','#f4d05e','#333d47'];
  const stageCanvases=new Map();

  function persist(){try{localStorage.setItem(STORAGE,JSON.stringify(saved));storageAvailable=true;return true;}catch{storageAvailable=false;toast('ブラウザに保存できませんでした。この画面を開いている間は使えるよ。');return false;}}
  function toast(message){$('toast').textContent=message;$('toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('visible'),3500);}
  function uid(prefix){return `${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,7)}`;}
  function rounded(g,x,y,w,h,r,fill,stroke,line=1){g.beginPath();g.roundRect(x,y,w,h,r);if(fill){g.fillStyle=fill;g.fill();}if(stroke){g.strokeStyle=stroke;g.lineWidth=line;g.stroke();}}
  function ellipse(g,x,y,rx,ry,color){g.beginPath();g.ellipse(x,y,rx,ry,0,0,Math.PI*2);g.fillStyle=color;g.fill();}
  function line(g,x1,y1,x2,y2,color,width=2){g.beginPath();g.moveTo(x1,y1);g.lineTo(x2,y2);g.strokeStyle=color;g.lineWidth=width;g.lineCap='round';g.stroke();}

  function drawCharacter(g,c,x,y,size,time=0,direction='down',walking=false){
    g.save();g.translate(x,y);g.scale(size/60,size/60);
    ellipse(g,0,24,20,6,'#20322125');
    const bounce=walking?Math.sin(time*23)*2:Math.sin(time*2)*1.3;g.translate(0,bounce);
    if(c.mode==='pixel'&&c.pixels){g.imageSmoothingEnabled=false;for(let i=0;i<256;i++)if(c.pixels[i]){g.fillStyle=c.pixels[i];g.fillRect((i%16-8)*3.2,(Math.floor(i/16)-8)*3.2,3.3,3.3);}g.restore();return;}
    const outline='#333d3d', step=walking?Math.sin(time*23)*3:0;
    rounded(g,-17,14+step,15,11,5,c.accent,outline,1.5);rounded(g,2,14-step,15,11,5,c.accent,outline,1.5);
    rounded(g,-12,0,24,20,8,c.body,outline,1.7);
    rounded(g,-12,10,24,5,2,'#fff8e9');rounded(g,-3,9,6,7,1,'#edc654',outline,1);
    ellipse(g,-17,9-step,7,7,c.accent);ellipse(g,17,9+step,7,7,c.accent);
    if(c.accessory==='antenna'){line(g,0,-24,0,-33,outline,4);ellipse(g,0,-35,6.2,6.2,c.accent);ellipse(g,-2,-37,2,2,'#ffffffaa');}
    if(c.accessory==='cat'){g.fillStyle=c.helmet;g.strokeStyle=outline;g.lineWidth=1.5;for(const d of[-1,1]){g.beginPath();g.moveTo(d*9,-24);g.lineTo(d*22,-39);g.lineTo(d*22,-17);g.closePath();g.fill();g.stroke();g.fillStyle=c.accent;g.beginPath();g.moveTo(d*13,-24);g.lineTo(d*19,-32);g.lineTo(d*19,-21);g.closePath();g.fill();g.fillStyle=c.helmet;}}
    rounded(g,-24,-27,48,37,13,c.helmet,outline,1.8);rounded(g,-20,-24,39,8,5,'#ffffff66');
    const shift=direction==='left'?-3:direction==='right'?3:0;
    if(direction!=='up'){
      rounded(g,-17+shift,-18,34,23,8,'#f3d6b0',outline,1.2);
      line(g,-7+shift,-12,-7+shift,-4,outline,3.2);line(g,7+shift,-12,7+shift,-4,outline,3.2);
      ellipse(g,-11+shift,0,3.3,1.7,'#ef9a9577');ellipse(g,11+shift,0,3.3,1.7,'#ef9a9577');
    }else{rounded(g,-10,-15,20,15,5,'#ffffff33');}
    if(c.accessory==='crown'){g.beginPath();g.moveTo(-15,-26);g.lineTo(-17,-39);g.lineTo(-7,-32);g.lineTo(0,-43);g.lineTo(7,-32);g.lineTo(17,-39);g.lineTo(15,-26);g.closePath();g.fillStyle='#f5ce60';g.fill();g.strokeStyle=outline;g.lineWidth=1.4;g.stroke();ellipse(g,0,-30,2.3,2.3,c.accent);}
    if(c.accessory==='leaf'){line(g,0,-25,0,-38,'#4d7b53',2.5);g.save();g.translate(-7,-35);g.rotate(.4);ellipse(g,0,0,9,4,'#73a965');g.restore();g.save();g.translate(7,-39);g.rotate(-.5);ellipse(g,0,0,9,4,'#94c678');g.restore();}
    g.restore();
  }
  function drawEgg(g,type,x,y,size,time=0,active=false){g.save();g.translate(x,y);g.scale(size/40,size/40);ellipse(g,0,15,13,4,'#26332122');g.translate(0,Math.sin(time*5)*2);g.beginPath();g.moveTo(0,-19);g.bezierCurveTo(16,-19,23,18,0,18);g.bezierCurveTo(-23,18,-16,-19,0,-19);g.fillStyle=B.EGGS[type].color;g.fill();g.strokeStyle='#555d41';g.lineWidth=1.6;g.stroke();ellipse(g,-5,-10,3,4,'#fffdf399');ellipse(g,7,8,3.5,2.4,'#f0a88a');ellipse(g,-7,8,3.5,2.4,'#f0a88a');ellipse(g,-5,0,1.6,2.2,'#343a32');ellipse(g,5,0,1.6,2.2,'#343a32');if(active)ellipse(g,0,7,5,5,'#343a32');else{g.beginPath();g.arc(0,4,3,0,Math.PI);g.strokeStyle='#343a32';g.lineWidth=1.5;g.stroke();}if(type==='shield'){g.strokeStyle='#ffffee';g.lineWidth=2;g.beginPath();g.arc(0,0,23,0,Math.PI*2);g.stroke();}if(type==='speed'){ellipse(g,-6,-20,3,9,'#f3b9d2');ellipse(g,6,-20,3,9,'#f3b9d2');}g.restore();}
  function drawTile(g,tile,x,y,theme,decor=true){
    const t=B.THEMES[theme],px=x*C,py=y*C;
    g.fillStyle=t.floor[(x+y)%2];g.fillRect(px,py,C,C);
    if(tile===0&&decor&&((x*17+y*31)%11===0)){line(g,px+17,py+44,px+15,py+40,t.accent+'35',1.5);line(g,px+17,py+44,px+20,py+39,t.accent+'35',1.5);if(theme==='candy'){ellipse(g,px+44,py+17,2,2,'#fff7');}if(theme==='space'){ellipse(g,px+40,py+40,7,4,'#66799a15');}}
    if(tile===1){rounded(g,px+3,py+6,54,52,8,t.wallSide);rounded(g,px+3,py+1,54,48,8,t.wall);rounded(g,px+3,py+1,54,39,8,t.wallTop);line(g,px+12,py+7,px+45,py+7,'#ffffff33',3);if((x+y)%3===0){rounded(g,px+36,py+15,13,10,3,t.wall+'66');}if(theme==='space'){rounded(g,px+25,py+16,9,9,3,'#dbe5ed');} }
    if(tile===2){rounded(g,px+6,py+9,49,47,6,'#00000016');rounded(g,px+5,py+5,48,46,5,t.crate);rounded(g,px+5,py+2,48,41,5,t.crateTop,t.crate,1.3);if(theme==='candy'){line(g,px+10,py+8,px+47,py+36,'#fff9',7);line(g,px+14,py+36,px+45,py+10,'#fff5',5);}else if(theme==='space'){rounded(g,px+13,py+10,32,25,3,t.crate);rounded(g,px+24,py+16,11,12,2,'#d5e2d8');}else{line(g,px+13,py+10,px+45,py+36,t.crate,5);line(g,px+13,py+36,px+45,py+10,t.crate,5);line(g,px+11,py+7,px+11,py+38,'#f0d397',3);line(g,px+47,py+7,px+47,py+38,'#f0d397',3);}for(const [dx,dy]of[[10,7],[47,7],[10,38],[47,38]])ellipse(g,px+dx,py+dy,1.3,1.3,t.crate);}
  }
  function drawItem(g,item,time){if(item.delay>0)return;const x=item.x*C+30,y=item.y*C+31+Math.sin(time*4+item.x)*3;const palette={power:['#f4be6c','✦'],capacity:['#c2b6e9','●'],speed:['#a6d9d3','»'],heart:['#f4b5c8','♥']};const[color,mark]=palette[item.kind];rounded(g,x-16,y-16,32,32,8,'#fffbed','#526546',1.5);rounded(g,x-12,y-12,24,24,5,color);g.fillStyle='#4b5841';g.font='bold 23px sans-serif';g.textAlign='center';g.textBaseline='middle';g.fillText(mark,x,y+1);}
  function drawBomb(g,bomb,time){const x=bomb.x*C+30,y=bomb.y*C+34;const pulse=1+Math.sin(time*(bomb.timer<.8?27:9))*(bomb.timer<.8?.1:.035);g.save();g.translate(x,y);g.scale(pulse,pulse);ellipse(g,0,15,18,5,'#2833202c');line(g,5,-13,12,-23,'#726444',3);g.fillStyle='#fde898';g.font='22px sans-serif';g.textAlign='center';g.fillText('✦',13,-17);ellipse(g,0,0,17,17,bomb.weapon==='line'?'#80619a':bomb.weapon==='vertical'?'#be7665':bomb.weapon==='pierce'?'#4c7d82':'#303a3c');ellipse(g,-5,-6,5,4,'#ffffff33');if(bomb.weapon!=='normal'){g.fillStyle='#fff5c1';g.font='bold 17px sans-serif';g.textAlign='center';g.fillText(B.WEAPONS[bomb.weapon].mark,0,7);}g.restore();}
  function drawBoard(g,model,time,{editor=false,mini=false}={}){
    const width=model.grid[0].length,height=model.grid.length;for(let y=0;y<height;y++)for(let x=0;x<width;x++)drawTile(g,model.grid[y][x],x,y,model.stage?.theme||model.theme,!mini);
    if(model.items)for(const item of model.items)drawItem(g,item,time);
    if(model.bombs)for(const bomb of model.bombs)drawBomb(g,bomb,time);
    if(model.flames)for(const f of model.flames){const x=f.x*C+30,y=f.y*C+30;g.globalAlpha=Math.min(1,f.timer*5);rounded(g,x-27,y-18,54,36,12,f.egg?'#efe467':'#f5b34d');rounded(g,x-18,y-27,36,54,12,f.egg?'#efe467':'#f5b34d');rounded(g,x-15,y-15,30,30,9,'#fff7c4');ellipse(g,x,y,9,9,'#fffdef');g.globalAlpha=1;}
    if(model.actors){for(const actor of [...model.actors].sort((a,b)=>a.drawY-b.drawY)){if(!actor.alive)continue;if(actor.invincible>0&&Math.floor(time*12)%2===0)g.globalAlpha=.45;drawCharacter(g,actor.id===0?saved.character:B.PRESETS[actor.id],actor.drawX*C+30,actor.drawY*C+29,48,time,actor.direction,actor.motion<1);g.globalAlpha=1;if(actor.id===0){g.fillStyle='#3c5b3b';g.beginPath();g.moveTo(actor.drawX*C+24,actor.drawY*C-13);g.lineTo(actor.drawX*C+36,actor.drawY*C-13);g.lineTo(actor.drawX*C+30,actor.drawY*C-5);g.fill();}}
      const p=model.player;if(p.alive)drawEgg(g,model.egg,p.drawX*C+49,p.drawY*C+46,23,time,eggPulse>0);
    }else if(model.spawns){model.spawns.forEach((p,i)=>{if(!p)return;drawCharacter(g,i===0?saved.character:B.PRESETS[i],p.x*C+30,p.y*C+31,46,time);if(editor){rounded(g,p.x*C+2,p.y*C+1,23,13,3,i?'#806192':'#64824e');g.font='bold 8px sans-serif';g.fillStyle='#fff';g.textAlign='center';g.fillText(i?'CPU':'YOU',p.x*C+13,p.y*C+10);}});}
    if(editor){g.strokeStyle='#ffffff26';g.lineWidth=1;for(let x=0;x<=width;x++){g.beginPath();g.moveTo(x*C,0);g.lineTo(x*C,height*C);g.stroke();}for(let y=0;y<=height;y++){g.beginPath();g.moveTo(0,y*C);g.lineTo(width*C,y*C);g.stroke();}}
  }
  function renderGame(time){ctx.clearRect(0,0,canvas.width,canvas.height);ctx.save();if(shake>0&&!matchMedia('(prefers-reduced-motion: reduce)').matches)ctx.translate(Math.sin(time*97)*shake*5,Math.cos(time*83)*shake*5);drawBoard(ctx,game,time);for(const p of particles){ctx.globalAlpha=Math.min(1,p.life*2);if(p.star){ctx.fillStyle=p.color;ctx.font=`${p.size}px sans-serif`;ctx.textAlign='center';ctx.fillText('✦',p.x,p.y);}else{rounded(ctx,p.x,p.y,p.size,p.size,2,p.color);}}ctx.globalAlpha=1;ctx.restore();}

  function makeCanvas(w=100,h=100){const c=document.createElement('canvas');c.width=w;c.height=h;return c;}
  function renderStageCards(){
    $('stage-list').replaceChildren();stageCanvases.clear();
    const stages=[B.createStage('garden',17),B.createStage('candy',84),B.createStage('space',35),...saved.stages];
    $('stage-count').textContent=`${String(stages.length).padStart(2,'0')} STAGES`;
    for(const stage of stages){const button=document.createElement('button');button.className=`stage-card ${stage.theme}${selectedStage.id===stage.id?' selected':''}`;button.setAttribute('aria-pressed',selectedStage.id===stage.id);button.setAttribute('aria-label',`${stage.name}を選ぶ`);const preview=makeCanvas(220,180);preview.className='stage-thumb';const g=preview.getContext('2d');g.save();const size=B.dimensions(stage),scale=Math.min(216/(size.width*C),172/(size.height*C));g.translate((220-size.width*C*scale)/2,(180-size.height*C*scale)/2);g.scale(scale,scale);drawBoard(g,stage,0,{mini:true});g.restore();button.append(preview);const info=document.createElement('span');info.className='stage-info';const number=document.createElement('span');number.className='stage-number';number.textContent=`STAGE ${String(stages.indexOf(stage)+1).padStart(2,'0')}${stage.id.startsWith('custom-')?' / YOUR WORLD':''}`;const title=document.createElement('strong');title.textContent=stage.name;const detail=document.createElement('span');detail.className='stage-detail';detail.textContent=stage.id.startsWith('custom-')?'きみがつくったステージ。':B.THEMES[stage.theme].subtitle;info.append(number,title,detail);button.append(info);if(stage.id===selectedStage.id){const mark=document.createElement('span');mark.className='selected-mark';mark.textContent='●';button.append(mark);}button.addEventListener('click',()=>{selectedStage=B.clone(stage);prepareGame();renderStageCards();});$('stage-list').append(button);}
  }
  function prepareGame(){game=new B.Game(selectedStage,{weapon:saved.weapon,egg:saved.egg});particles=[];pressed.clear();touchDirection=null;canvas.width=game.width*C;canvas.height=game.height*C;fitCanvases();$('arena-size').textContent=`${game.width} × ${game.height} TILES`;showOverlay('ready');$('arena-name').textContent=selectedStage.name;$('game-message').textContent='爆弾をおいたら、すぐに離れよう！';$('arena-wrap').style.background=B.THEMES[selectedStage.theme].rim;updateHUD();drawPlayerPreview();renderRivals();}
  function showOverlay(kind){
    const data={ready:['A LITTLE BOMB, A BIG ADVENTURE.','✷','準備はいい？',`${game.actors.length-1}人のライバルと、たまごとバトル。`,'バトルスタート','ひとりで遊べる · CPU対戦'],paused:['TAKE A LITTLE BREAK.','Ⅱ','ちょっと、ひとやすみ。','準備ができたら、つづきから遊ぼう。','バトルにもどる','Esc / P キーでも再開できるよ'],won:['YOU MADE A BIG BOOM!','✦','やったね、きみの勝ち！',`スコア ${game.score} · 残り ${Math.ceil(game.time)} 秒`,'もう一度あそぶ','ほかのステージにも挑戦してみよう'],lost:['ONE MORE LITTLE ADVENTURE.','↻',game.time<=0?'タイムアップ！':'もう一回、挑戦しよう。',`スコア ${game.score} · 壁のかげに逃げるのがコツ！`,'もう一度あそぶ','パクたまの力も使ってみてね']};
    const d=data[kind];$('game-overlay').hidden=false;$('overlay-kicker').textContent=d[0];$('overlay-symbol').textContent=d[1];$('overlay-title').textContent=d[2];$('overlay-description').textContent=d[3];$('start-button').replaceChildren(document.createTextNode(d[4]+' '));const arrow=document.createElement('span');arrow.textContent='→';$('start-button').append(arrow);$('overlay-note').textContent=d[5];$('pause-button').disabled=kind!=='paused';$('pause-button').textContent=kind==='paused'?'▷':'Ⅱ';$('pause-button').setAttribute('aria-label',kind==='paused'?'再開':'一時停止');
  }
  function startGame(){ensureAudio();if(game.status==='paused'){game.status='playing';}else{if(['won','lost'].includes(game.status))prepareGame();game.start();}pressed.clear();$('game-overlay').hidden=true;$('pause-button').disabled=false;$('pause-button').textContent='Ⅱ';$('pause-button').setAttribute('aria-label','一時停止');canvas.focus({preventScroll:true});document.querySelector('.arena-panel').scrollIntoView({block:'start',behavior:'smooth'});playSound('start');updateHUD();}
  function pauseGame(){pressed.clear();touchDirection=null;if(game.status==='playing'){game.status='paused';showOverlay('paused');updateHUD();}}
  function togglePause(){if(game.status==='playing')pauseGame();else if(game.status==='paused')startGame();}
  function changeView(view){if(!['play','stage','character'].includes(view))return;if(view!==currentView)pauseGame();currentView=view;$$('.view').forEach(el=>{el.hidden=el.id!==`view-${view}`;el.classList.toggle('active',!el.hidden);});$$('.nav-button').forEach(el=>{el.classList.toggle('active',el.dataset.view===view);el.setAttribute('aria-current',el.dataset.view===view?'page':'false');});if(view==='stage')renderEditor();if(view==='character'){syncCharacterControls();renderPixel();}window.scrollTo({top:0,behavior:'instant'});}
  function updateHUD(){
    const seconds=Math.ceil(game.time);$('timer').textContent=`${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`;$('timer').style.color=seconds<30?'#c97074':'';
    $('health').textContent='♥ '.repeat(Math.max(0,game.player.hp)).trim()||'♡';$('capacity').replaceChildren(document.createTextNode(`${game.player.capacity} `));const countUnit=document.createElement('small');countUnit.textContent='個';$('capacity').append(countUnit);$('power').replaceChildren(document.createTextNode(game.weapon==='line'?'横一列':game.weapon==='vertical'?'縦一列':`${game.player.power} `));if(!['line','vertical'].includes(game.weapon)){const powerUnit=document.createElement('small');powerUnit.textContent='マス';$('power').append(powerUnit);}
    $('match-label').textContent={ready:'READY TO PLAY',playing:'BATTLE IN PROGRESS',paused:'PAUSED',won:'YOU WIN!',lost:'TRY AGAIN'}[game.status];
    const remaining=game.actors.slice(1).filter(a=>a.alive).length;$('rival-count').textContent=`${remaining} LEFT`;
    game.actors.slice(1).forEach(a=>{const row=$(`rival-${a.id}`);if(row){row.classList.toggle('eliminated',!a.alive);row.querySelector('span').textContent=a.alive?'CPU':'OUT';}});
    const locked=['playing','paused'].includes(game.status);$('weapon-select').disabled=locked;$('egg-select').disabled=locked;
    $('egg-status').textContent=game.eggCooldown>0?`ひとやすみ ${Math.ceil(game.eggCooldown)}秒`:game.egg==='paku'?'E で、ぱくっ！':game.egg==='shield'?'ガードの準備 OK':'いつでも、ぴょん！';$('egg-description').textContent=B.EGGS[game.egg].description;$('egg-button').disabled=game.egg!=='paku'||game.eggCooldown>0||game.status!=='playing';$('touch-egg').disabled=$('egg-button').disabled;
  }
  function drawPlayerPreview(){const p=$('player-preview');p.getContext('2d').clearRect(0,0,p.width,p.height);drawCharacter(p.getContext('2d'),saved.character,120,117,130,0);$('player-name').textContent=saved.character.name;}
  function renderRivals(){$('rivals').replaceChildren();for(const actor of game.actors.slice(1)){const row=document.createElement('div');row.className='rival-row';row.id=`rival-${actor.id}`;const c=makeCanvas(80,80);drawCharacter(c.getContext('2d'),B.PRESETS[actor.id],40,44,62);const name=document.createElement('b');name.textContent=B.PRESETS[actor.id].name;const label=document.createElement('span');label.textContent='CPU';row.append(c,name,label);$('rivals').append(row);}}
  function useEgg(){const message=game.useEgg();if(message)toast(message);else{eggPulse=.8;$('game-message').textContent='ぱくっ！ 爆弾の力で、横にドカーン！';}processEvents();updateHUD();}
  function spawnParticles(x,y,color,count=12,star=false){for(let i=0;i<count;i++){const angle=Math.random()*Math.PI*2,speed=35+Math.random()*110;particles.push({x:x*C+30,y:y*C+30,vx:Math.cos(angle)*speed,vy:Math.sin(angle)*speed-30,life:.4+Math.random()*.5,size:4+Math.random()*7,color,star});}}
  function processEvents(){for(const e of game.events.splice(0)){if(e.type==='explode'){playSound('explode');shake=.18;spawnParticles(e.x,e.y,'#efb15b',15);}if(e.type==='break')spawnParticles(e.x,e.y,B.THEMES[game.stage.theme].crateTop,7);if(e.type==='place')playSound('place');if(e.type==='eat'){playSound('egg');spawnParticles(e.x,e.y,'#e6df62',22,true);eggPulse=1;shake=.22;}if(e.type==='collect'){playSound('collect');spawnParticles(e.x,e.y,'#fff2a8',10,true);$('game-message').textContent={heart:'♥ ライフ回復！',power:'✦ 爆風が長くなった！',capacity:'● 爆弾をたくさん置けるようになった！',speed:'» 足が速くなった！'}[e.kind];}if(e.type==='shield'){playSound('collect');$('game-message').textContent='まもたまが、爆風をガード！';spawnParticles(game.player.x,game.player.y,'#aee3ed',17,true);}if(e.type==='hurt'){playSound('hurt');spawnParticles(e.x,e.y,'#f49eb3',14);if(e.id===0){shake=.4;$('game-message').textContent='あちち！ 爆風は壁のかげでよけよう。';}else $('game-message').textContent=`${B.PRESETS[e.id].name}をたおした！`;}if(e.type==='end'){pressed.clear();touchDirection=null;showOverlay(e.won?'won':'lost');playSound(e.won?'win':'lose');if(e.won)for(let i=0;i<20;i++)spawnParticles(1+Math.random()*(game.width-2),Math.random()*(game.height-2),['#f2c76a','#a8d9a4','#e4a2c0','#b8b0e4'][i%4],5,true);}}
  }
  function ensureAudio(){if(!soundOn)return;try{audio ||= new(window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume().catch(()=>{});}catch{soundOn=false;}}
  function tone(freq,duration,when=0,type='sine',volume=.055){if(!audio||!soundOn)return;const oscillator=audio.createOscillator(),gain=audio.createGain();oscillator.type=type;oscillator.frequency.setValueAtTime(freq,audio.currentTime+when);gain.gain.setValueAtTime(volume,audio.currentTime+when);gain.gain.exponentialRampToValueAtTime(.001,audio.currentTime+when+duration);oscillator.connect(gain);gain.connect(audio.destination);oscillator.start(audio.currentTime+when);oscillator.stop(audio.currentTime+when+duration);}
  function playSound(kind){if(!soundOn)return;ensureAudio();if(kind==='place')tone(220,.12,0,'triangle');if(kind==='explode'){tone(65,.25,0,'sawtooth',.04);tone(100,.12,0,'triangle',.035);}if(kind==='collect') [520,660,880].forEach((f,i)=>tone(f,.14,i*.06));if(kind==='hurt') [240,120].forEach((f,i)=>tone(f,.18,i*.09,'triangle'));if(kind==='egg') [190,380,750].forEach((f,i)=>tone(f,.18,i*.08,'triangle'));if(kind==='start') [392,523,784].forEach((f,i)=>tone(f,.17,i*.1));if(kind==='win') [523,659,784,1046].forEach((f,i)=>tone(f,.3,i*.14));if(kind==='lose') [330,294,220].forEach((f,i)=>tone(f,.3,i*.16));}

  function fitCanvases(){for(const c of [canvas,$('stage-editor')]){const maxHeight=Math.max(260,Math.min(640,innerHeight*.72));c.style.width=`min(100%, ${maxHeight*c.width/c.height}px)`;}}
  window.addEventListener('resize',fitCanvases);
  $('resize-stage').addEventListener('click',()=>{const width=Number($('stage-width').value),height=Number($('stage-height').value);if(!B.validSize(width,height)){toast('横7〜31マス、縦7〜25マスで決めてね。');return;}const old=B.dimensions(draft);if(old.width===width&&old.height===height)return;pushStageUndo();draft=B.resizeStage(draft,width,height);renderEditor();toast(`${width} × ${height}マスにしたよ。もどすボタンで元に戻せるよ。`);});
  function renderEditor(){const size=B.dimensions(draft),c=$('stage-editor');c.width=size.width*C;c.height=size.height*C;fitCanvases();$('stage-width').value=size.width;$('stage-height').value=size.height;$('editor-size').textContent=`${size.width} × ${size.height}`;const g=c.getContext('2d');g.clearRect(0,0,c.width,c.height);drawBoard(g,draft,0,{editor:true});$('stage-editor').parentElement.style.background=B.THEMES[draft.theme].rim;$('undo-stage').disabled=stageUndo.length===0;$('stage-validation').textContent=B.validateStage(draft)||'✓ いい感じ！ 保存してバトルしよう。';}
  function renderPalette(){const definitions=[['floor','道'],['wall','こわせない壁'],['crate','ブロック'],['player','プレイヤー'],['enemy','ライバル']];for(const [id,label]of definitions){const button=document.createElement('button');button.className='tile-brush'+(id===brush?' selected':'');button.dataset.brush=id;button.setAttribute('aria-pressed',id===brush);const c=makeCanvas(60,60),g=c.getContext('2d');if(id==='player'||id==='enemy'){drawTile(g,0,0,0,'garden',false);drawCharacter(g,id==='player'?saved.character:B.PRESETS[2],30,33,43);}else drawTile(g,{floor:0,wall:1,crate:2}[id],0,0,'garden',false);const span=document.createElement('span');span.textContent=label;button.append(c,span);button.addEventListener('click',()=>{brush=id;$$('.tile-brush').forEach(b=>{b.classList.toggle('selected',b.dataset.brush===brush);b.setAttribute('aria-pressed',b.dataset.brush===brush);});});$('tile-palette').append(button);}}
  function pushStageUndo(){stageUndo.push(B.clone(draft));if(stageUndo.length>40)stageUndo.shift();}
  function canvasCell(event,c,w,h){const r=c.getBoundingClientRect();return{x:Math.floor((event.clientX-r.left)/r.width*w),y:Math.floor((event.clientY-r.top)/r.height*h)};}
  function paintStage(event){const {width,height}=B.dimensions(draft);const{x,y}=canvasCell(event,$('stage-editor'),width,height),k=B.key(x,y);if(k===lastStageCell||x<=0||x>=width-1||y<=0||y>=height-1)return;lastStageCell=k;
    const index=draft.spawns.findIndex(p=>p.x===x&&p.y===y);
    if(brush==='player'){if(index>0)draft.spawns.splice(index,1);draft.spawns[0]={x,y};draft.grid[y][x]=0;}
    else if(brush==='enemy'){if(index===0)return;if(index>0)draft.spawns.splice(index,1);else if(draft.spawns.length<4){draft.spawns.push({x,y});draft.grid[y][x]=0;}else toast('ライバルは3人まで。置いたライバルを押すと消せるよ。');}
    else {if(index===0&&brush!=='floor')return;if(index>0)draft.spawns.splice(index,1);draft.grid[y][x]={floor:0,wall:1,crate:2}[brush];}renderEditor();
  }
  function saveStage(){draft.name=$('stage-name').value.trim()||'マイ・ステージ';const error=B.validateStage(draft);if(error){toast(error);return;}if(!draftId&&saved.stages.length>=12){toast('保存できるステージは12個まで。使わないステージを消してね。');return;}draft.id=draftId||uid('custom');draftId=draft.id;const existing=saved.stages.findIndex(s=>s.id===draftId);if(existing>=0)saved.stages[existing]=B.clone(draft);else saved.stages.push(B.clone(draft));const stored=persist();selectedStage=B.clone(draft);prepareGame();renderStageCards();renderSavedStages();changeView('play');if(stored)toast('ステージを保存したよ。さあ、バトルしよう！');}
  function newStage(){const {width,height}=B.dimensions(draft);draft=B.createStage($('stage-theme').value,Math.floor(Math.random()*10000),width,height);draft.name='マイ・ステージ';draftId=null;stageUndo=[];$('stage-name').value=draft.name;renderEditor();}
  function renderSavedStages(){$('saved-stages').replaceChildren();if(!saved.stages.length)return;const label=document.createElement('div');label.className='card-kicker';label.textContent='YOUR STAGES';$('saved-stages').append(label);for(const stage of saved.stages){const row=document.createElement('div');row.className='saved-item';const edit=document.createElement('button');edit.textContent=`▦ ${stage.name}`;edit.addEventListener('click',()=>{draft=B.clone(stage);draftId=stage.id;stageUndo=[];$('stage-name').value=stage.name;$('stage-theme').value=stage.theme;renderEditor();toast('ステージを読み込んだよ。');});const remove=document.createElement('button');remove.textContent='×';remove.setAttribute('aria-label',`${stage.name}を削除`);remove.addEventListener('click',()=>{if(!confirm(`「${stage.name}」を消しますか？`))return;saved.stages=saved.stages.filter(s=>s.id!==stage.id);if(draftId===stage.id)draftId=null;if(selectedStage.id===stage.id){selectedStage=B.createStage('garden',17);prepareGame();}persist();renderSavedStages();renderStageCards();});row.append(edit,remove);$('saved-stages').append(row);}}

  function seedPixels(){const pixels=Array(256).fill(null),fill=(x,y,w,h,color)=>{for(let yy=y;yy<y+h;yy++)for(let xx=x;xx<x+w;xx++)pixels[yy*16+xx]=color;};fill(7,0,2,2,character.accent);fill(3,3,10,6,character.helmet);fill(2,4,12,4,character.helmet);fill(4,5,8,3,'#f3d6b0');fill(5,5,1,2,'#333d47');fill(10,5,1,2,'#333d47');fill(5,9,6,4,character.body);fill(3,10,2,3,character.accent);fill(11,10,2,3,character.accent);fill(5,11,6,1,'#fff9ed');fill(4,13,3,2,character.accent);fill(9,13,3,2,character.accent);return pixels;}
  function syncCharacterControls(){$('character-name').value=character.name;$('helmet-color').value=character.helmet;$('body-color').value=character.body;$('accent-color').value=character.accent;$('accessory').value=character.accessory;$('dress-tools').hidden=character.mode==='pixel';$('pixel-tools').hidden=character.mode!=='pixel';$('mode-dress').classList.toggle('active',character.mode==='dress');$('mode-pixel').classList.toggle('active',character.mode==='pixel');$('mode-dress').setAttribute('aria-pressed',character.mode==='dress');$('mode-pixel').setAttribute('aria-pressed',character.mode==='pixel');$('character-preview-name').textContent=character.name||'なまえは、なににする？';$$('.swatches').forEach(group=>{[...group.children].forEach(button=>{const match=button.dataset.color===$(group.dataset.colorFor).value;button.classList.toggle('selected',match);button.setAttribute('aria-pressed',match);});});}
  function renderCharacterPreview(time){const c=$('character-preview'),g=c.getContext('2d');g.clearRect(0,0,c.width,c.height);drawCharacter(g,character,250,245,260,time);}
  function renderPixel(){const c=$('pixel-editor'),g=c.getContext('2d'),s=c.width/16;character.pixels ||= seedPixels();for(let y=0;y<16;y++)for(let x=0;x<16;x++){g.fillStyle=character.pixels[y*16+x]||((x+y)%2?'#e9ecde':'#f8f9ef');g.fillRect(x*s,y*s,s,s);g.strokeStyle='#5d6a4720';g.lineWidth=.6;g.strokeRect(x*s,y*s,s,s);}$('undo-pixel').disabled=pixelUndo.length===0;}
  function paintPixel(event){const{x,y}=canvasCell(event,$('pixel-editor'),16,16),k=B.key(x,y);if(x<0||y<0||x>=16||y>=16||k===lastPixelCell)return;lastPixelCell=k;character.pixels[y*16+x]=eraser?null:$('pixel-color').value;renderPixel();}
  function pushPixelUndo(){pixelUndo.push([...(character.pixels||seedPixels())]);if(pixelUndo.length>50)pixelUndo.shift();}
  function saveCharacter(){character.name=$('character-name').value.trim()||'マイキャラ';if(character.mode==='pixel'&&!character.pixels.some(Boolean)){toast('ドットを描いてから、保存してね。');return;}if(!characterId&&saved.characters.length>=16){toast('保存できるキャラクターは16人まで。使わないキャラを消してね。');return;}character.id=characterId||uid('hero');characterId=character.id;const index=saved.characters.findIndex(c=>c.id===character.id);if(index>=0)saved.characters[index]=B.clone(character);else saved.characters.push(B.clone(character));saved.character=B.clone(character);const stored=persist();drawPlayerPreview();renderSavedCharacters();prepareGame();changeView('play');if(stored)toast(`「${character.name}」を保存したよ。いっしょに遊ぼう！`);}
  function renderPresets(){for(const preset of B.PRESETS){const button=document.createElement('button');button.className='preset-button';const c=makeCanvas(90,88);drawCharacter(c.getContext('2d'),preset,45,48,65);const name=document.createElement('span');name.textContent=preset.name;button.append(c,name);button.setAttribute('aria-label',`${preset.name}をもとに作る`);button.addEventListener('click',()=>{character=B.clone(preset);characterId=null;pixelUndo=[];syncCharacterControls();renderPixel();});$('character-presets').append(button);}$$('.swatches').forEach(group=>{for(const color of colors){const button=document.createElement('button');button.className='swatch';button.style.setProperty('--swatch',color);button.dataset.color=color;button.setAttribute('aria-label',`${group.dataset.colorFor} ${color}`);button.addEventListener('click',()=>{$(group.dataset.colorFor).value=color;$(group.dataset.colorFor).dispatchEvent(new Event('input'));});group.append(button);}});}
  function renderSavedCharacters(){$('saved-characters').replaceChildren();if(!saved.characters.length)return;const label=document.createElement('div');label.className='card-kicker';label.textContent='YOUR CHARACTERS';$('saved-characters').append(label);for(const hero of saved.characters){const row=document.createElement('div');row.className='saved-item';const edit=document.createElement('button');edit.textContent=`☺ ${hero.name}`;edit.addEventListener('click',()=>{character=B.clone(hero);characterId=hero.id;pixelUndo=[];syncCharacterControls();renderPixel();toast('キャラクターを読み込んだよ。');});const remove=document.createElement('button');remove.textContent='×';remove.setAttribute('aria-label',`${hero.name}を削除`);remove.addEventListener('click',()=>{if(!confirm(`「${hero.name}」を消しますか？`))return;saved.characters=saved.characters.filter(c=>c.id!==hero.id);if(characterId===hero.id)characterId=null;if(saved.character.id===hero.id){saved.character=B.clone(B.PRESETS[0]);drawPlayerPreview();}persist();renderSavedCharacters();});row.append(edit,remove);$('saved-characters').append(row);}}

  $$('[data-view]').forEach(button=>button.addEventListener('click',()=>changeView(button.dataset.view)));
  document.querySelector('.brand').addEventListener('click',event=>{event.preventDefault();changeView('play');});
  $('start-button').addEventListener('click',startGame);$('pause-button').addEventListener('click',togglePause);
  $('restart-button').addEventListener('click',()=>{prepareGame();toast('最初から準備できたよ。');});
  $('sound-toggle').addEventListener('click',()=>{soundOn=!soundOn;$('sound-toggle').querySelector('span').textContent=soundOn?'ON':'OFF';$('sound-toggle').setAttribute('aria-label',soundOn?'音をオフにする':'音をオンにする');ensureAudio();if(soundOn)playSound('collect');});
  $('help-button').addEventListener('click',()=>{pauseGame();$('help-dialog').showModal();});$('close-help').addEventListener('click',()=>$('help-dialog').close());$('help-ok').addEventListener('click',()=>$('help-dialog').close());
  $('weapon-select').value=saved.weapon;$('egg-select').value=saved.egg;
  $('weapon-select').addEventListener('change',()=>{saved.weapon=$('weapon-select').value;persist();prepareGame();toast(B.WEAPONS[saved.weapon].description);});$('egg-select').addEventListener('change',()=>{saved.egg=$('egg-select').value;persist();prepareGame();toast(B.EGGS[saved.egg].description);});$('egg-button').addEventListener('click',useEgg);$('touch-egg').addEventListener('click',useEgg);
  const keyMap={ArrowUp:[0,-1],KeyW:[0,-1],ArrowDown:[0,1],KeyS:[0,1],ArrowLeft:[-1,0],KeyA:[-1,0],ArrowRight:[1,0],KeyD:[1,0]};
  window.addEventListener('keydown',event=>{if(currentView!=='play'||/INPUT|SELECT|TEXTAREA/.test(event.target.tagName)||$('help-dialog').open)return;if(keyMap[event.code]||['Space','Escape','KeyP','KeyE'].includes(event.code)){event.preventDefault();if(event.code==='Space'&&event.target.tagName==='BUTTON'&&game.status!=='playing'){if(!event.repeat)event.target.click();return;}if(keyMap[event.code]){if(!pressed.has(event.code))pressed.set(event.code,performance.now());}else if(!event.repeat){if(event.code==='Space'&&game.status==='playing'){game.placeBomb();processEvents();}if(event.code==='Escape'||event.code==='KeyP')togglePause();if(event.code==='KeyE'&&game.status==='playing')useEgg();}}});
  window.addEventListener('keyup',event=>pressed.delete(event.code));window.addEventListener('blur',pauseGame);document.addEventListener('visibilitychange',()=>{if(document.hidden)pauseGame();});
  const directions={up:[0,-1],left:[-1,0],down:[0,1],right:[1,0]};$$('[data-direction]').forEach(button=>{button.addEventListener('pointerdown',event=>{event.preventDefault();button.setPointerCapture(event.pointerId);touchDirection=directions[button.dataset.direction];});const release=()=>touchDirection=null;button.addEventListener('pointerup',release);button.addEventListener('pointercancel',release);button.addEventListener('lostpointercapture',release);});$('touch-bomb').addEventListener('pointerdown',event=>{event.preventDefault();game.placeBomb();processEvents();});
  $('stage-editor').addEventListener('pointerdown',event=>{event.preventDefault();if(event.button!==0)return;pushStageUndo();paintingStage=true;lastStageCell='';$('stage-editor').setPointerCapture(event.pointerId);paintStage(event);});$('stage-editor').addEventListener('pointermove',event=>{if(paintingStage)paintStage(event);});for(const type of['pointerup','pointercancel','lostpointercapture'])$('stage-editor').addEventListener(type,()=>{paintingStage=false;lastStageCell='';});
  $('undo-stage').addEventListener('click',()=>{if(stageUndo.length){draft=stageUndo.pop();$('stage-theme').value=draft.theme;$('stage-name').value=draft.name;renderEditor();}});$('clear-stage').addEventListener('click',()=>{pushStageUndo();const {width,height}=B.dimensions(draft);draft.grid=B.baseGrid(false,width,height);draft.spawns=[{x:1,y:1},{x:width-2,y:height-2}];renderEditor();});$('stage-theme').addEventListener('change',()=>{pushStageUndo();draft.theme=$('stage-theme').value;renderEditor();});$('stage-name').addEventListener('input',()=>draft.name=$('stage-name').value);$('save-stage').addEventListener('click',saveStage);$('new-stage').addEventListener('click',newStage);
  $('character-name').addEventListener('input',()=>{character.name=$('character-name').value;$('character-preview-name').textContent=character.name||'なまえは、なににする？';});for(const [id,prop]of[['helmet-color','helmet'],['body-color','body'],['accent-color','accent']])$(id).addEventListener('input',()=>{character[prop]=$(id).value;syncCharacterControls();});$('accessory').addEventListener('change',()=>character.accessory=$('accessory').value);
  $('mode-dress').addEventListener('click',()=>{character.mode='dress';syncCharacterControls();});$('mode-pixel').addEventListener('click',()=>{character.mode='pixel';character.pixels ||= seedPixels();syncCharacterControls();renderPixel();});$('pixel-eraser').addEventListener('click',()=>{eraser=!eraser;$('pixel-eraser').classList.toggle('selected',eraser);$('pixel-eraser').setAttribute('aria-pressed',eraser);});$('pixel-color').addEventListener('input',()=>{eraser=false;$('pixel-eraser').classList.remove('selected');$('pixel-eraser').setAttribute('aria-pressed','false');});$('clear-pixel').addEventListener('click',()=>{pushPixelUndo();character.pixels=Array(256).fill(null);renderPixel();});$('undo-pixel').addEventListener('click',()=>{if(pixelUndo.length){character.pixels=pixelUndo.pop();renderPixel();}});
  $('pixel-editor').addEventListener('pointerdown',event=>{event.preventDefault();if(event.button!==0)return;pushPixelUndo();paintingPixel=true;lastPixelCell='';$('pixel-editor').setPointerCapture(event.pointerId);paintPixel(event);});$('pixel-editor').addEventListener('pointermove',event=>{if(paintingPixel)paintPixel(event);});for(const type of['pointerup','pointercancel','lostpointercapture'])$('pixel-editor').addEventListener(type,()=>{paintingPixel=false;lastPixelCell='';});$('save-character').addEventListener('click',saveCharacter);
  function frame(now){const time=now/1000,dt=Math.min(.05,lastTime?(now-lastTime)/1000:0);lastTime=now;const latest=[...pressed.entries()].sort((a,b)=>b[1]-a[1])[0];game.update(dt,touchDirection||(latest?keyMap[latest[0]]:null));processEvents();if(game.status!=='paused'){particles=particles.filter(p=>p.life>0);for(const p of particles){p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=90*dt;}shake=Math.max(0,shake-dt);eggPulse=Math.max(0,eggPulse-dt);}if(currentView==='play'){renderGame(time);if(Math.floor(now/100)!==Math.floor((now-dt*1000)/100))updateHUD();}if(currentView==='character')renderCharacterPreview(time);requestAnimationFrame(frame);}
  renderStageCards();prepareGame();renderPalette();renderSavedStages();renderPresets();syncCharacterControls();renderPixel();renderSavedCharacters();requestAnimationFrame(frame);
  if(!storageAvailable)toast('保存データを読み込めませんでした。新しく遊びはじめられるよ。');
  // Small, read-only snapshot for reproducible browser checks and support.
  window.bombStudioSnapshot=()=>({view:currentView,status:game.status,stage:game.stage.name,width:game.width,height:game.height,weapon:game.weapon,egg:game.egg,time:game.time,player:{x:game.player.x,y:game.player.y,hp:game.player.hp},bombs:game.bombs.length,rivals:game.actors.slice(1).filter(a=>a.alive).length,savedStages:saved.stages.length,savedCharacters:saved.characters.length,character:saved.character.name,eggCooldown:game.eggCooldown});
})();
