(() => {
 'use strict';
 const C=WachaCore,A=WachaArt,$=s=>document.querySelector(s),dialog=$('#dialog');
 C.setNavigation(WACHA_ASSETS.navigation);
 C.installLife(WachaLife);
 let screen='home',state=null,world=null,lastTime=0,resultShown=false,collectionBase=0,toastTimer,dialogMode='',previousFocus=null,ready=false,lastDraw='';
 let records={};try{records=JSON.parse(localStorage.getItem('wacha-records-v1')||'{}')||{};}catch{}
 function safeRecords(){try{localStorage.setItem('wacha-records-v1',JSON.stringify(records));}catch{}}
 function format(seconds){const n=Math.max(0,Math.ceil(seconds));return String(Math.floor(n/60)).padStart(2,'0')+':'+String(n%60).padStart(2,'0');}
 function show(name){screen=name;document.querySelectorAll('.screen').forEach(s=>s.classList.toggle('hidden',s.id!==name));$('#footer').classList.toggle('hidden',name==='game');document.body.classList.remove('paused');window.scrollTo(0,0);if(name==='game'){requestAnimationFrame(()=>world.resize());}if(name==='stages')renderStages();if(name==='collection')renderCollection();}
 function modal(mode,html){if(dialog.open)dialog.close();previousFocus=document.activeElement;dialogMode=mode;$('#dialog-body').innerHTML=html;dialog.showModal();requestAnimationFrame(()=>dialog.querySelector('button')?.focus());}
 function closeModal(){dialog.close();dialogMode='';previousFocus?.focus();}
 function renderStages(){
  $('#progress-label').innerHTML=Object.keys(records).filter(k=>records[k]?.cleared).length+' / 7<br>みつけた！';
  $('#stage-grid').innerHTML=C.STAGES.map(s=>`<button class="stage-card" data-action="stage" data-stage="${s.id}"><div class="stage-image"><img src="${WACHA_ASSETS.images[s.image]}" alt="${s.name}" loading="lazy"><span class="stage-no">${String(s.id+1).padStart(2,'0')}</span>${records[s.id]?.cleared?'<span class="stage-clear">✓ みつけた！</span>':''}</div><div class="stage-copy"><span class="eyebrow">${s.en}</span><h3>${s.name}</h3><p>${s.note}</p><div class="stage-meta"><span>600人 / 3分間</span><b>${records[s.id]?.cleared?'ベスト '+format(records[s.id].best):'この街へ →'}</b></div></div></button>`).join('');
 }
 function renderCollection(){
  $('#character-tabs').innerHTML=C.CHARACTERS.map((name,i)=>`<button class="${i===collectionBase?'active':''}" data-action="character" data-base="${i}">${name}</button>`).join('');
  $('#collection-grid').innerHTML=Array.from({length:20},(_,i)=>`<div class="character-card"><canvas width="100" height="120" data-type="${collectionBase*20+i}"></canvas><strong>${C.COLORS[i]}</strong><small>No. ${String(collectionBase*20+i+1).padStart(3,'0')}</small></div>`).join('');
 }
 function toast(text){$('#toast').textContent=text;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),2000);}
 function prepare(stage){
  state=C.create(stage,(Date.now()^Math.floor(Math.random()*1e9))>>>0);resultShown=false;lastDraw='';lifeAt=-1;world.fit();show('game');const s=C.STAGES[stage],t=C.typeInfo(state.targetType);
  requestAnimationFrame(()=>{world.resize();if(window.innerWidth<=700){world.zoom=Math.min(4,Math.max(1,world.height/941/world.base));world.clamp();updateZoom();}});
  $('#stage-title').textContent=s.name;$('#map-number').textContent=String(stage+1).padStart(2,'0');$('#map-english').textContent=s.en;$('#target-name').textContent=t.name;$('#target-color').textContent=t.color+'の衣装';$('#hint-button').disabled=false;$('#zoom-label').textContent='100%';$('#toast').classList.remove('show');hud();
  modal('ready',`<span class="ready-tag">STAGE ${String(stage+1).padStart(2,'0')} / 07</span><h2 id="dialog-title">この子を覚えてね。</h2><canvas id="dialog-portrait" class="dialog-portrait" width="144" height="174"></canvas><strong>${t.name} · ${t.color}</strong><p>600人の中に、この姿はたった1人。<br>3分以内に見つけて、タッチしよう。</p><div class="dialog-actions"><button class="primary" data-action="begin">準備OK、さがそう！</button><button class="text-button" data-action="cancel-ready">街をえらび直す</button></div>`);
 }
 function begin(){closeModal();C.start(state);lastTime=performance.now();$('#world').focus();}
 function pause(){if(!state||state.status!=='playing')return;C.pause(state);document.body.classList.add('paused');modal('pause',`<span class="eyebrow">A LITTLE BREAK</span><h2 id="dialog-title">ひとやすみ。</h2><p>住人も時計も、ちょっとおやすみ。<br>残り ${format(state.remaining)}</p><div class="dialog-actions"><button class="primary" data-action="resume">おさんぽを続ける</button><button class="secondary" data-action="leave">街をえらぶ</button></div>`);}
 function resume(){closeModal();document.body.classList.remove('paused');C.start(state);lastTime=performance.now();$('#world').focus();}
 function help(){const running=state?.status==='playing';if(running){C.pause(state);document.body.classList.add('paused');}
  modal('help',`<span class="eyebrow">HOW TO PLAY</span><h2 id="dialog-title">みつけて、タッチ！</h2><ol class="help-steps"><li><b>探す子の姿を覚えよう</b>帽子や服の色が目印。画面上の見本は、いつでも見られます。</li><li><b>600人が歩く街を見渡そう</b>ドラッグで移動。ホイール・ピンチ・＋と−で拡大できます。全体表示に戻すと街をひと目で見渡せます。</li><li><b>3分以内につかまえよう</b>買い物中や乗り物の上でも、同じ子をタッチでクリア。お手つきは−3秒。ヒントは−10秒で1回使えます。</li></ol><p class="keyboard-tip">キーボード：矢印キーで画面移動 / ＋・−でズーム / 0で全体 / Escで一時停止<br>別のアプリに切り替えると自動で一時停止します。</p><div class="dialog-actions"><button class="primary" data-action="help-close" data-resume="${running}">わかった！</button></div>`);
 }
 function finish(){if(resultShown)return;resultShown=true;const won=state.status==='won',t=C.typeInfo(state.targetType);
  if(won){const old=records[state.stage];records[state.stage]={cleared:true,best:Math.min(old?.best??Infinity,state.elapsed)};safeRecords();}
  const all=Object.keys(records).filter(k=>records[k]?.cleared).length===7;
  modal('result',`<span class="result-flower">${won?'✳':'⌕'}</span><h2 id="dialog-title">${won?(all?'7つの街、ぜんぶ発見！':'みーつけた！'):'また、会いにいこう。'}</h2><canvas id="dialog-portrait" class="dialog-portrait" width="144" height="174"></canvas><p>${won?`${t.name}をつかまえた！<br>今日のおさんぽ、大成功。`:`今回は時間切れ。<br>${t.name}は、街のどこかにいました。`}</p><div class="result-stats"><div><strong>${won?format(state.elapsed):'03:00'}</strong><span>${won?'見つけた時間':'制限時間'}</span></div><div><strong>${state.mistakes}</strong><span>お手つき</span></div><div><strong>${Object.keys(records).filter(k=>records[k]?.cleared).length}/7</strong><span>みつけた街</span></div></div><div class="dialog-actions">${won&&state.stage<6?'<button class="primary" data-action="next">次の街へ →</button>':'<button class="primary" data-action="retry">もう一度さがす</button>'}<button class="secondary" data-action="leave">7つの街へ</button></div>`);
 }
 function hud(){if(!state)return;$('#timer').textContent=format(state.remaining);$('#time-fill').style.width=(state.remaining/180*100)+'%';$('.clock-box').classList.toggle('urgent',state.remaining<=30);$('#hint-button').disabled=!state.hints||state.status!=='playing';if(state.life&&lifeAt!==Math.floor(state.elapsed)){lifeAt=Math.floor(state.elapsed);const n=state.life.counts;$('#life-feed').textContent=state.life.feed[0]?.text||'';$('#life-counts').textContent='お買いもの '+((n.queue||0)+(n.shopping||0))+' · おしゃべり '+(n.chat||0)+' · 釣り '+(n.fishing||0)+' · 遊び '+((n.play||0)+(n.tag||0)+(n.dance||0))+' · 乗り物 '+(n.ride||0);}}
 function navigate(name){if(screen==='game'&&state?.status==='playing'){pause();return;}if(dialog.open)closeModal();state=null;show(name);}
 document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b||!ready)return;const a=b.dataset.action;
  if(a==='home')navigate('home');else if(a==='stages')navigate('stages');else if(a==='collection')navigate('collection');else if(a==='play')prepare(0);else if(a==='stage')prepare(Number(b.dataset.stage));else if(a==='character'){collectionBase=Number(b.dataset.base);renderCollection();}
  else if(a==='begin')begin();else if(a==='pause'||a==='exit')pause();else if(a==='resume')resume();else if(a==='leave'||a==='cancel-ready'){closeModal();state=null;show('stages');}else if(a==='help')help();else if(a==='help-close'){const go=b.dataset.resume==='true';closeModal();if(go){document.body.classList.remove('paused');C.start(state);lastTime=performance.now();}}
  else if(a==='retry'){const n=state.stage;closeModal();prepare(n);}else if(a==='next'){const n=state.stage+1;closeModal();prepare(n);}else if(a==='hint'){if(C.hint(state)){toast('このあたりにいたよ！ −10秒');hud();}}else if(a==='zoom-in'){world.zoomAt(1.35);updateZoom();}else if(a==='zoom-out'){world.zoomAt(1/1.35);updateZoom();}else if(a==='fit'){world.fit();updateZoom();}
 });
 dialog.addEventListener('cancel',e=>{e.preventDefault();if(dialogMode==='pause')resume();else if(dialogMode==='help')dialog.querySelector('[data-action="help-close"]').click();else if(dialogMode==='ready'){closeModal();state=null;show('stages');}});
 function updateZoom(){$('#zoom-label').textContent=Math.round(world.zoom*100)+'%';}
 const pointer=new Map();let gesture=null,pinchDistance=0,pinched=false;
 function point(e){const r=$('#world').getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top};}
 $('#world').addEventListener('pointerdown',e=>{if(!state||state.status!=='playing')return;const p=point(e);pointer.set(e.pointerId,p);e.target.setPointerCapture(e.pointerId);if(pointer.size===1){gesture={...p,originX:p.x,originY:p.y,moved:false};pinched=false;}else{pinched=true;gesture=null;const v=[...pointer.values()];pinchDistance=Math.hypot(v[0].x-v[1].x,v[0].y-v[1].y);}});
 $('#world').addEventListener('pointermove',e=>{if(!pointer.has(e.pointerId))return;const p=point(e);pointer.set(e.pointerId,p);if(pointer.size===2){const v=[...pointer.values()],d=Math.hypot(v[0].x-v[1].x,v[0].y-v[1].y);if(pinchDistance>0)world.zoomAt(d/pinchDistance,(v[0].x+v[1].x)/2,(v[0].y+v[1].y)/2);pinchDistance=d;updateZoom();}else if(gesture){if(Math.hypot(p.x-gesture.originX,p.y-gesture.originY)>6)gesture.moved=true;if(gesture.moved)world.pan(p.x-gesture.x,p.y-gesture.y);gesture.x=p.x;gesture.y=p.y;}});
 $('#world').addEventListener('pointerup',e=>{const p=point(e);if(gesture&&!gesture.moved&&!pinched&&state?.status==='playing'){const hit=world.hit(state,p.x,p.y);if(hit!==null){if(!C.touch(state,hit))toast('ちがう子だった！ −3秒');hud();}}pointer.delete(e.pointerId);if(!pointer.size){gesture=null;pinched=false;}});
 $('#world').addEventListener('pointercancel',e=>{pointer.delete(e.pointerId);gesture=null;});
 $('#world').addEventListener('wheel',e=>{if(!state||state.status!=='playing')return;e.preventDefault();const p=point(e);world.zoomAt(Math.exp(-e.deltaY*.002),p.x,p.y);updateZoom();},{passive:false});
 document.addEventListener('keydown',e=>{if(screen!=='game'||!state||dialog.open)return;if(e.key==='Escape'||e.key.toLowerCase()==='p'){e.preventDefault();pause();return;}if(state.status!=='playing')return;const dirs={ArrowLeft:[70,0],ArrowRight:[-70,0],ArrowUp:[0,70],ArrowDown:[0,-70]};if(dirs[e.key]){e.preventDefault();world.pan(...dirs[e.key]);}else if(e.key==='+'||e.key==='='){world.zoomAt(1.3);updateZoom();}else if(e.key==='-'){world.zoomAt(1/1.3);updateZoom();}else if(e.key==='0'){world.fit();updateZoom();}});
 window.addEventListener('blur',()=>{pointer.clear();gesture=null;if(state?.status==='playing')pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&state?.status==='playing')pause();});window.addEventListener('resize',()=>world?.resize());
 let uiAt=0,portraitAt=0,lastPaint=0,lifeAt=-1;
 function frame(t){const dt=lastTime?Math.max(0,(t-lastTime)/1000):0;lastTime=t;
  if(screen==='game'&&state){C.step(state,dt);const stamp=[state.stage,state.status,world.zoom,world.cx,world.cy,world.canvas.width,world.canvas.height].join(':');if(stamp!==lastDraw||(state.status==='playing'&&t-lastPaint>=1000/30)){world.draw(state);lastDraw=stamp;lastPaint=t-(t-lastPaint)%(1000/30);}if(t-uiAt>100){hud();uiAt=t;}if((state.status==='won'||state.status==='lost')&&!resultShown)finish();}
  if(t-portraitAt>65){const phase=(t/900)%1;if(state){A.portrait($('#target-portrait'),state.targetType,phase);const c=$('#dialog-portrait');if(c)A.portrait(c,state.targetType,phase);}if(screen==='collection')document.querySelectorAll('#collection-grid canvas').forEach(c=>A.portrait(c,Number(c.dataset.type),phase));portraitAt=t;}
  requestAnimationFrame(frame);
 }
 window.WachaGame={snapshot(){return{ready,screen,status:state?.status,stage:state?.stage,count:state?.people.length,types:state?new Set(state.people.map(p=>p.type)).size:320,remaining:state?.remaining,elapsed:state?.elapsed,frames:15,rendered:world?.rendered,drawFrames:world?.drawFrames,renderer:world?.batch.mode,life:state?.life?{counts:state.life.counts,stats:state.life.stats,feed:state.life.feed,crime:state.life.crime}:null,zoom:world?.zoom,records,people:state?.people.map(p=>({id:p.id,type:p.type,x:p.x,y:p.y,phase:p.phase,activity:p.activity,role:p.role,inventory:p.inventory})),targetId:state?.targetId,targetType:state?.targetType,view:world?{cx:world.cx,cy:world.cy,width:world.width,height:world.height,scale:world.scale}:null};}};
 async function init(){try{await A.init(n=>{$('#load-progress').textContent=`320種類の住人を準備中… ${n} / 320`;$('#load-bar').value=n;});$('.hero-art').style.backgroundImage=`url("${WACHA_ASSETS.images.cover}")`;world=new A.World($('#world'));ready=true;$('#loading').classList.add('hidden');renderStages();requestAnimationFrame(frame);}catch(e){console.error(e);$('#load-progress').textContent='準備できませんでした。ページを開き直してください。';}}
 init();
})();
