(() => {
 'use strict';
 const C=WachaCore,A=WachaArt,$=s=>document.querySelector(s),dialog=$('#dialog');
 C.setNavigation(WACHA_ASSETS.navigation);
 C.installLife(WachaLife);
 let screen='home',state=null,world=null,lastTime=0,resultShown=false,collectionBase=0,toastTimer,dialogMode='',previousFocus=null,ready=false,lastDraw='';
 let aiming=null,cameraDrag=null,photoImages=[],seenPhotos=new Set();
 let records={};try{records=JSON.parse(localStorage.getItem('wacha-records-v1')||'{}')||{};}catch{}
 function safeRecords(){try{localStorage.setItem('wacha-records-v1',JSON.stringify(records));}catch{}}
 function format(seconds){const n=Math.max(0,Math.ceil(seconds));return String(Math.floor(n/60)).padStart(2,'0')+':'+String(n%60).padStart(2,'0');}
 function show(name){if(name!=='game'&&document.fullscreenElement)document.exitFullscreen().catch(()=>{});screen=name;document.body.classList.toggle('searching',name==='game');document.querySelectorAll('.screen').forEach(s=>s.classList.toggle('hidden',s.id!==name));$('#footer').classList.toggle('hidden',name==='game');document.body.classList.remove('paused');window.scrollTo(0,0);if(name==='game'){requestAnimationFrame(()=>world.resize());}if(name==='stages')renderStages();if(name==='collection')renderCollection();}
 function modal(mode,html){if(dialog.open)dialog.close();previousFocus=document.activeElement;dialogMode=mode;$('#dialog-body').innerHTML=html;dialog.showModal();requestAnimationFrame(()=>dialog.querySelector('button')?.focus());}
 function closeModal(){dialog.close();$('#dialog-body').replaceChildren();dialogMode='';previousFocus?.focus();}
 function renderStages(){
  $('#progress-label').innerHTML=Object.keys(records).filter(k=>records[k]?.cleared).length+' / 7<br>みつけた！';
  $('#stage-grid').innerHTML=C.STAGES.map(s=>`<button class="stage-card" data-action="stage" data-stage="${s.id}"><div class="stage-image"><img src="${WACHA_ASSETS.images[s.image]}" alt="${s.name}" loading="lazy"><span class="stage-no">${String(s.id+1).padStart(2,'0')}</span>${records[s.id]?.cleared?'<span class="stage-clear">✓ みつけた！</span>':''}</div><div class="stage-copy"><span class="eyebrow">${s.en}</span><h3>${s.name}</h3><p>${s.note}</p><div class="stage-meta"><span>500体 / 3分間</span><b>${records[s.id]?.cleared?'ベスト '+format(records[s.id].best):'この街へ →'}</b></div></div></button>`).join('');
 }
 function renderCollection(){
  const groups=['街の仲間','年齢・体格','犬と猫','おしごと','お祭り','スポーツ','ご近所','家族','仮装',"街の職人","おいしい街","市場のひと","町の仕事","音楽の時間","公園の遊び","いろいろな運動","庭と自然","ものづくり","おでかけ","おしゃれな住人","街の家族","物語の仮装","楽しい衣装","動物の仲間","働く乗りもの好き","夜のお祭り"];
  $('#character-tabs').innerHTML=groups.map((name,i)=>`<button class="${i===collectionBase?'active':''}" data-action="character" data-base="${i}">${name}</button>`).join('');
  const start=collectionBase===0?0:collectionBase<9?16+(collectionBase-1)*8:80+(collectionBase-9)*10,end=collectionBase===0?16:start+(collectionBase<9?8:10);
  $('#collection-grid').innerHTML=Array.from({length:(end-start)*C.PALETTES},(_,i)=>{const type=start*C.PALETTES+i,info=C.typeInfo(type);return `<div class="character-card"><canvas width="100" height="120" data-type="${type}"></canvas><strong>${info.name}</strong><small>${info.color} · No. ${String(type+1).padStart(3,'0')}</small></div>`;}).join('');
 }
 function toast(text,kind='info'){const el=$('#toast');el.textContent=text;el.dataset.kind=kind;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2600);}
 function prepare(stage){
  state=C.create(stage,(Date.now()^Math.floor(Math.random()*1e9))>>>0);resultShown=false;photoImages=[];seenPhotos.clear();cancelCamera();lastDraw='';lifeAt=-1;world.fit();show('game');const s=C.STAGES[stage],t=C.typeInfo(state.targetType);
  requestAnimationFrame(()=>{world.resize();world.fit();updateZoom();});
  $('#stage-title').textContent=s.name;$('#map-number').textContent=String(stage+1).padStart(2,'0');$('#map-english').textContent=s.en;$('#target-name').textContent=t.name;$('#target-color').textContent=t.color+'の衣装';$('#peek-name').textContent=t.name;$('#peek-color').textContent=t.color;$('#target-peek').classList.remove('expanded');$('#target-peek').setAttribute('aria-expanded','false');$('#target-peek').setAttribute('aria-label',`探す人の見本：${t.name}、${t.color}。タッチで拡大`);A.portrait($('#peek-portrait'),state.targetType,0);$('#hint-button').disabled=false;$('#zoom-label').textContent='100%';$('#toast').classList.remove('show');hud();
  modal('ready',`<span class="ready-tag">STAGE ${String(stage+1).padStart(2,'0')} / 07</span><h2 id="dialog-title">この子を覚えてね。</h2><canvas id="dialog-portrait" class="dialog-portrait" width="144" height="174"></canvas><strong>${t.name} · ${t.color}</strong><p>500の住人と動物の中に、同じ姿はひとつだけ。<br>3分以内に見つけて、タッチしよう。<br>見本は画面の左上。タッチすると大きく見られます。<br>ドラッグで移動、ホイール・ピンチで拡大。<br>カメラで街の一部を3枚まで撮影できます。<br>写真は3秒後に現像。写った本人だけが見えます。<br><small>Esc または2本指で長押し：見本・残り時間・一時停止</small></p><div class="dialog-actions"><button class="primary" data-action="begin">準備OK、さがそう！</button><button class="text-button" data-action="cancel-ready">街をえらび直す</button></div>`);
 }
 function begin(){if(document.fullscreenEnabled&&!document.fullscreenElement)document.documentElement.requestFullscreen().catch(()=>{});closeModal();C.start(state);lastTime=performance.now();$('#world').focus();}
 function pause(){if(!state||state.status!=='playing')return;cancelCamera();C.pause(state);document.body.classList.add('paused');modal('pause',`<span class="eyebrow">A LITTLE BREAK</span><h2 id="dialog-title">ひとやすみ。</h2><canvas id="dialog-portrait" class="dialog-portrait" width="144" height="174"></canvas><strong>${C.typeInfo(state.targetType).name} · ${C.typeInfo(state.targetType).color}</strong><p>残り ${format(state.remaining)} · 住人も時計も一時停止中</p><div class="dialog-actions"><button class="primary" data-action="resume">おさんぽを続ける</button><button class="secondary" data-action="pause-camera" ${state.photos.length<3&&!state.photos.some(p=>!C.photoReady(state,p.id))?'':'disabled'}>写真を撮る（残り ${3-state.photos.length} 枚）</button>${state.photos.filter(p=>C.photoReady(state,p.id)).map(p=>`<button class="secondary" data-action="photo-view" data-photo="${p.id}">写真 ${p.id+1} を見返す</button>`).join('')}<button class="secondary" data-action="fullscreen">端末の全画面表示にする</button><button class="secondary" data-action="leave">街をえらぶ</button></div>`);}
 function resume(){closeModal();document.body.classList.remove('paused');C.start(state);lastTime=performance.now();$('#world').focus();}
 function help(){const running=state?.status==='playing';if(running){C.pause(state);document.body.classList.add('paused');}
  modal('help',`<span class="eyebrow">HOW TO PLAY</span><h2 id="dialog-title">みつけて、タッチ！</h2><ol class="help-steps"><li><b>探す子の姿を覚えよう</b>帽子や服の色が目印。左上の見本は、タッチすると全画面のまま拡大できます。残り時間はEscか2本指の長押しで確認できます。</li><li><b>住人と動物が暮らす街を見渡そう</b>ドラッグで移動。ホイール・ピンチ・＋と−で拡大できます。画面を動かして街のすみずみまで探せます。</li><li><b>3分以内につかまえよう</b>買い物中や乗り物の上でも、同じ子をタッチでクリア。お手つきは−3秒。写真は3枚まで。カメラボタンかCキーで撮影枠を出し、枠をドラッグして範囲を選びます。もう一度押すと撮影。3秒後に写真を開くと、写っていた本人だけが見えます。</li></ol><p class="keyboard-tip">キーボード：矢印キーで画面移動 / ＋・−でズーム / 0で初期表示 / Escで一時停止<br>別のアプリに切り替えると自動で一時停止します。</p><div class="dialog-actions"><button class="primary" data-action="help-close" data-resume="${running}">わかった！</button></div>`);
 }
 function finish(){if(resultShown)return;cancelCamera();resultShown=true;const won=state.status==='won',t=C.typeInfo(state.targetType);
  if(won){const old=records[state.stage];records[state.stage]={cleared:true,best:Math.min(old?.best??Infinity,state.elapsed)};safeRecords();}
  const all=Object.keys(records).filter(k=>records[k]?.cleared).length===7;
  modal('result',`<span class="result-flower">${won?'✳':'⌕'}</span><h2 id="dialog-title">${won?(all?'7つの街、ぜんぶ発見！':'みーつけた！'):'また、会いにいこう。'}</h2><canvas id="dialog-portrait" class="dialog-portrait" width="144" height="174"></canvas><p>${won?`${t.name}をつかまえた！<br>今日のおさんぽ、大成功。`:`今回は時間切れ。<br>${t.name}は、街のどこかにいました。`}</p><div class="result-stats"><div><strong>${won?format(state.elapsed):'03:00'}</strong><span>${won?'見つけた時間':'制限時間'}</span></div><div><strong>${state.mistakes}</strong><span>お手つき</span></div><div><strong>${Object.keys(records).filter(k=>records[k]?.cleared).length}/7</strong><span>みつけた街</span></div></div><div class="dialog-actions">${won&&state.stage<6?'<button class="primary" data-action="next">次の街へ →</button>':'<button class="primary" data-action="retry">もう一度さがす</button>'}<button class="secondary" data-action="leave">7つの街へ</button></div>`);
 }
 function hud(){if(!state)return;cameraStatus();$('#timer').textContent=format(state.remaining);$('#time-fill').style.width=(state.remaining/180*100)+'%';$('.clock-box').classList.toggle('urgent',state.remaining<=30);$('#hint-button').disabled=!state.hints||state.status!=='playing';if(state.life&&lifeAt!==Math.floor(state.elapsed)){lifeAt=Math.floor(state.elapsed);const n=state.life.counts;$('#life-feed').textContent=state.life.feed[0]?.text||'';$('#life-counts').textContent='お買いもの '+((n.queue||0)+(n.shopping||0))+' · おしゃべり '+(n.chat||0)+' · 釣り '+(n.fishing||0)+' · 遊び '+((n.play||0)+(n.tag||0)+(n.dance||0))+' · 乗り物 '+(n.ride||0);}}
 function navigate(name){cancelCamera();if(screen==='game'&&state?.status==='playing'){pause();return;}if(dialog.open)closeModal();state=null;show(name);}
 document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b||!ready)return;const a=b.dataset.action;
  if(a==='home')navigate('home');else if(a==='stages')navigate('stages');else if(a==='collection')navigate('collection');else if(a==='play')prepare(0);else if(a==='stage')prepare(Number(b.dataset.stage));else if(a==='character'){collectionBase=Number(b.dataset.base);renderCollection();}
  else if(a==='target-peek'){const expanded=b.classList.toggle('expanded');b.setAttribute('aria-expanded',String(expanded));b.setAttribute('aria-label',`探す人の見本：${C.typeInfo(state.targetType).name}、${C.typeInfo(state.targetType).color}。タッチで${expanded?'縮小':'拡大'}`);}else if(a==='begin')begin();else if(a==='fullscreen'){document.documentElement.requestFullscreen?.().catch(()=>{});}else if(a==='pause-camera'){resume();camera();}else if(a==='camera'){camera();}else if(a==='camera-cancel'){cancelCamera();}else if(a==='photo-view'){openPhoto(Number(b.dataset.photo));}else if(a==='photo-return'){resume();}else if(a==='pause'||a==='exit')pause();else if(a==='resume')resume();else if(a==='leave'||a==='cancel-ready'){closeModal();state=null;show('stages');}else if(a==='help')help();else if(a==='help-close'){const go=b.dataset.resume==='true';closeModal();if(go){document.body.classList.remove('paused');C.start(state);lastTime=performance.now();}}
  else if(a==='retry'){const n=state.stage;closeModal();prepare(n);}else if(a==='next'){const n=state.stage+1;closeModal();prepare(n);}else if(a==='hint'){if(C.hint(state)){toast('このあたりにいたよ！ −10秒');hud();}}else if(a==='zoom-in'){world.zoomAt(1.35);updateZoom();}else if(a==='zoom-out'){world.zoomAt(1/1.35);updateZoom();}else if(a==='fit'){world.fit();updateZoom();}
 });
 dialog.addEventListener('cancel',e=>{e.preventDefault();if(dialogMode==='pause'||dialogMode==='photo')resume();else if(dialogMode==='help')dialog.querySelector('[data-action="help-close"]').click();else if(dialogMode==='ready'){closeModal();state=null;show('stages');}});
 function endCameraDrag(id=cameraDrag?.id){if(!cameraDrag||cameraDrag.id!==id)return;cameraDrag=null;$('#camera-frame').classList.remove('dragging');const canvas=$('#world');if(canvas.hasPointerCapture(id))canvas.releasePointerCapture(id);}
 function cancelCamera(){endCameraDrag();aiming=null;$('#camera-frame').classList.add('hidden');$('#camera-guide').classList.add('hidden');$('#camera-cancel').classList.add('hidden');$('#camera-button').classList.remove('aiming');}
 function aimAt(x,y){if(!aiming)return;const w=world.width*Math.sqrt(.1),h=world.height*Math.sqrt(.1);aiming={x:Math.max(0,Math.min(world.width-w,x-w/2)),y:Math.max(0,Math.min(world.height-h,y-h/2)),w,h};const f=$('#camera-frame');Object.assign(f.style,{left:aiming.x+'px',top:aiming.y+'px',width:w+'px',height:h+'px'});}
 function cameraStatus(){const b=$('#camera-button'),pending=state.photos.find(p=>!C.photoReady(state,p.id));b.classList.toggle('hidden',state.status!=='playing');b.disabled=!!pending||state.photos.length>=3;b.setAttribute('aria-label',pending?'写真を現像中':aiming?'この範囲を撮影':`写真を撮る。残り${3-state.photos.length}枚`);$('#camera-count').textContent=pending?Math.max(1,Math.ceil(pending.readyAt-state.elapsed))+'秒':aiming?'撮る':String(3-state.photos.length);}
 function camera(){
  if(!state||state.status!=='playing'||state.photos.length>=3||state.photos.some(p=>!C.photoReady(state,p.id)))return;
  if(aiming){const p=world.toWorld(aiming.x,aiming.y),rect={x:p.x,y:p.y,w:aiming.w/world.scale,h:aiming.h/world.scale},photo=C.takePhoto(state,rect);if(photo)photoImages[photo.id]=world.photo(state,rect);cancelCamera();cameraStatus();return;}
  pointer.clear();gesture=null;aiming={};aimAt(world.width/2,world.height/2);$('#camera-frame').classList.remove('hidden');$('#camera-guide').classList.remove('hidden');$('#camera-cancel').classList.remove('hidden');$('#camera-button').classList.add('aiming');cameraStatus();
 }
 function openPhoto(id){
  if(!state||!C.photoReady(state,id)||!photoImages[id])return;cancelCamera();C.pause(state);seenPhotos.add(id);document.body.classList.add('paused');
  modal('photo',`<span class="eyebrow">PHOTO ${id+1} / 3</span><h2 id="dialog-title">写真ができたよ。</h2><div id="photo-mount" class="photo-print"></div><p>撮影した瞬間に、ここにいた探し人だけが写ります。<br>姿がなければ、そのときは別の場所に。<br>街に戻って、本人をタッチしよう。</p><div class="dialog-actions"><button class="primary" data-action="photo-return">街へ戻って探す</button></div>`);
  const copy=document.createElement('canvas'),source=photoImages[id];copy.width=source.width;copy.height=source.height;copy.getContext('2d').drawImage(source,0,0);copy.setAttribute('aria-label',`撮影した範囲の写真 ${id+1}`);$('#photo-mount').append(copy);cameraStatus();
 }
 function updateZoom(){$('#zoom-label').textContent=Math.round(world.zoom*100)+'%';}
 const pointer=new Map();let gesture=null,pinchDistance=0,pinched=false,touchPauseTimer;
 function point(e){const r=$('#world').getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top};}
 $('#camera-frame').addEventListener('pointerdown',e=>{if(!aiming||cameraDrag||e.button!==0||state?.status!=='playing')return;e.preventDefault();const p=point(e);cameraDrag={id:e.pointerId,x:p.x,y:p.y,cx:aiming.x+aiming.w/2,cy:aiming.y+aiming.h/2};$('#world').setPointerCapture(e.pointerId);$('#camera-frame').classList.add('dragging');});
 $('#world').addEventListener('pointerdown',e=>{if(!state||state.status!=='playing'||aiming)return;const p=point(e);pointer.set(e.pointerId,p);e.target.setPointerCapture(e.pointerId);if(pointer.size===1){gesture={...p,originX:p.x,originY:p.y,moved:false};pinched=false;}else{pinched=true;gesture=null;clearTimeout(touchPauseTimer);touchPauseTimer=setTimeout(()=>{if(pointer.size===2){pause();pointer.clear();}},650);const v=[...pointer.values()];pinchDistance=Math.hypot(v[0].x-v[1].x,v[0].y-v[1].y);}});
 $('#world').addEventListener('pointermove',e=>{if(aiming){if(cameraDrag?.id===e.pointerId){const p=point(e);aimAt(cameraDrag.cx+p.x-cameraDrag.x,cameraDrag.cy+p.y-cameraDrag.y);}return;}if(!pointer.has(e.pointerId))return;const oldPoint=pointer.get(e.pointerId),p=point(e);if(Math.hypot(p.x-oldPoint.x,p.y-oldPoint.y)>3)clearTimeout(touchPauseTimer);pointer.set(e.pointerId,p);if(pointer.size===2){const v=[...pointer.values()],d=Math.hypot(v[0].x-v[1].x,v[0].y-v[1].y);if(pinchDistance>0)world.zoomAt(d/pinchDistance,(v[0].x+v[1].x)/2,(v[0].y+v[1].y)/2);pinchDistance=d;updateZoom();}else if(gesture){if(Math.hypot(p.x-gesture.originX,p.y-gesture.originY)>6)gesture.moved=true;if(gesture.moved)world.pan(p.x-gesture.x,p.y-gesture.y);gesture.x=p.x;gesture.y=p.y;}});
 $('#world').addEventListener('pointerup',e=>{clearTimeout(touchPauseTimer);const p=point(e);if(aiming){endCameraDrag(e.pointerId);return;}if(gesture&&!gesture.moved&&!pinched&&state?.status==='playing'){const hit=world.hit(state,p.x,p.y);if(hit!==null){if(C.touch(state,hit))finish();else toast('お手つき！ −3秒','mistake');hud();}else toast('住人にタッチしてね');}pointer.delete(e.pointerId);if(!pointer.size){gesture=null;pinched=false;}});
 $('#world').addEventListener('pointercancel',e=>{endCameraDrag(e.pointerId);clearTimeout(touchPauseTimer);pointer.delete(e.pointerId);gesture=null;});
 $('#world').addEventListener('lostpointercapture',e=>endCameraDrag(e.pointerId));
 $('#world').addEventListener('wheel',e=>{if(!state||state.status!=='playing'||aiming)return;e.preventDefault();const p=point(e);world.zoomAt(Math.exp(-e.deltaY*.002),p.x,p.y);updateZoom();},{passive:false});
 document.addEventListener('keydown',e=>{if(screen!=='game'||!state||dialog.open)return;if(e.key==='Escape'||e.key.toLowerCase()==='p'){e.preventDefault();if(aiming)cancelCamera();else pause();return;}if(e.key.toLowerCase()==='c'){e.preventDefault();camera();return;}if(state.status!=='playing'||aiming)return;const dirs={ArrowLeft:[70,0],ArrowRight:[-70,0],ArrowUp:[0,70],ArrowDown:[0,-70]};if(dirs[e.key]){e.preventDefault();world.pan(...dirs[e.key]);}else if(e.key==='+'||e.key==='='){world.zoomAt(1.3);updateZoom();}else if(e.key==='-'){world.zoomAt(1/1.3);updateZoom();}else if(e.key==='0'){world.fit();updateZoom();}});
 window.addEventListener('blur',()=>{pointer.clear();gesture=null;if(state?.status==='playing')pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&state?.status==='playing')pause();});window.addEventListener('resize',()=>{endCameraDrag();world?.resize();if(aiming)aimAt(world.width/2,world.height/2);});document.addEventListener('fullscreenchange',()=>{world?.resize();if(!document.fullscreenElement&&state?.status==='playing')pause();});
 let uiAt=0,portraitAt=0,lastPaint=0,lifeAt=-1;
 function frame(t){const dt=lastTime?Math.max(0,(t-lastTime)/1000):0;lastTime=t;
  if(screen==='game'&&state){C.step(state,dt);const stamp=[state.stage,state.status,world.zoom,world.cx,world.cy,world.canvas.width,world.canvas.height].join(':');if(stamp!==lastDraw||(state.status==='playing'&&t-lastPaint>=1000/30)){world.draw(state);lastDraw=stamp;lastPaint=t-(t-lastPaint)%(1000/30);}if(t-uiAt>100){hud();uiAt=t;}if((state.status==='won'||state.status==='lost')&&!resultShown)finish();else if(state.status==='playing'){const photo=state.photos.find(p=>C.photoReady(state,p.id)&&!seenPhotos.has(p.id));if(photo)openPhoto(photo.id);}}
  if(t-portraitAt>65){const phase=(t/900)%1;if(state){const c=$('#dialog-portrait');if(c)A.portrait(c,state.targetType,phase);if(screen==='game')A.portrait($('#peek-portrait'),state.targetType,phase);}if(screen==='collection')document.querySelectorAll('#collection-grid canvas').forEach(c=>A.portrait(c,Number(c.dataset.type),phase));portraitAt=t;}
  requestAnimationFrame(frame);
 }
 window.WachaGame={snapshot(){return{ready,screen,status:state?.status,stage:state?.stage,count:state?.people.length,baseTypes:C.CHARACTERS.length,types:state?new Set(state.people.map(p=>p.type)).size:C.TYPES,remaining:state?.remaining,elapsed:state?.elapsed,frames:15,rendered:world?.rendered,drawFrames:world?.drawFrames,renderer:world?.batch.mode,life:state?.life?{counts:state.life.counts,ambient:state.life.ambient,stats:state.life.stats,feed:state.life.feed,crime:state.life.crime}:null,zoom:world?.zoom,records,photos:state?.photos.map(p=>({id:p.id,ready:C.photoReady(state,p.id),takenAt:p.takenAt,readyAt:p.readyAt,rect:p.rect})),camera:aiming?{...aiming}:null,spacing:state?.space?{resolved:state.space.resolved,maxAge:state.space.maxAge}:null,people:state?.people.map(p=>({id:p.id,type:p.type,x:p.x,y:p.y,phase:p.phase,activity:p.activity,role:p.role,inventory:p.inventory,signature:p.signature,pace:p.pace,pauseUntil:p.pauseUntil,speed:p.speed,temperament:p.temperament,height:p.height,animal:p.animal})),targetId:state?.targetId,targetType:state?.targetType,view:world?{cx:world.cx,cy:world.cy,width:world.width,height:world.height,scale:world.scale}:null};}};
 async function init(){try{await A.init(n=>{$('#load-progress').textContent=`250種・1,000通りの住人を準備中… ${n} / 1000`;$('#load-bar').value=n;});$('.hero-art').style.backgroundImage=`url("${WACHA_ASSETS.images.cover}")`;world=new A.World($('#world'));ready=true;$('#loading').classList.add('hidden');renderStages();requestAnimationFrame(frame);}catch(e){console.error(e);$('#load-progress').textContent='準備できませんでした。ページを開き直してください。';}}
 init();
})();
