(() => {
 'use strict';
 const C=WachaExpedition,A=Wacha24Art,D=WACHA24_DATA,$=id=>document.getElementById(id),canvas=$('world'),world=new A.World(canvas),dialog=$('dialog');
 const isRunner=new URLSearchParams(location.search).get('view')==='runner';
 let s=null,last=performance.now(),aim=null,drag=null,photoCanvases=[],shownPhotos=new Set(),resultShown=false,busy=false,toastTimeout,runner=null,runnerReady=false,runnerLast=0,runnerToken='',lastBroadcast=0,remoteInput=null,remoteAt=0,collectionPage=0;
 let records={},buttonIndex=0;try{records=JSON.parse(localStorage.getItem('wacha-24-records')||'{}');buttonIndex=Number(localStorage.getItem('wacha-action-button')||0);}catch{}$('action-button').value=String(buttonIndex);
 const escape=t=>String(t).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const time=n=>{const seconds=Math.ceil(Math.max(0,n));return `${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`;};
 const pad=()=>Array.from(navigator.getGamepads?.()||[]).find(p=>p?.connected);
 const mode=()=>document.querySelector('input[name=mode]:checked').value;
 function toast(text,wrong=false){const el=$('toast');el.textContent=text;el.className='show'+(wrong?' wrong':'');clearTimeout(toastTimeout);toastTimeout=setTimeout(()=>el.className='',2500);}
 function modal(html){$('dialog-body').innerHTML=html;if(!dialog.open)dialog.showModal();}
 function close(){if(dialog.open)dialog.close();}
 function buttons(){return `<div class="actions"><button class="primary" data-action="resume">続ける</button><button data-action="leave">街をえらぶ</button></div>`;}
 function cameraLabel(){if(!s)return;const developing=s.photos.find(p=>!C.photoReady(s,p.id));$('camera-count').textContent=developing?`${Math.ceil(developing.readyAt-s.elapsed)}秒`:s.photoCredits;$('camera-button').setAttribute('aria-label',developing?'写真を現像中':`写真を撮る。残り${s.photoCredits}回`);}
 function cancelAim(){aim=null;drag=null;$('camera-frame').hidden=true;$('camera-cancel').hidden=true;}
 function positionAim(){if(!aim)return;const el=$('camera-frame');el.hidden=false;el.style.left=aim.x+'px';el.style.top=aim.y+'px';el.style.width=aim.w+'px';el.style.height=aim.h+'px';$('camera-cancel').hidden=false;}
 function photoOpen(id){if(!C.photoReady(s,id))return;$('photo-canvas').replaceChildren(photoCanvases[id]);$('photo-view').hidden=false;}
 function camera(){if(!s||s.status!=='playing')return;if(!s.photoCredits){toast('カメラを持った人を見つけると、1枚撮れます。');return;}if(s.photos.some(p=>!C.photoReady(s,p.id))){toast('写真を現像しています。');return;}
  if(!aim){const side=Math.sqrt(.1),w=world.width*side,h=world.height*side;aim={x:(world.width-w)/2,y:(world.height-h)/2,w,h};positionAim();return;}
  const point=world.toWorld(aim.x,aim.y),record=C.takePhoto(s,{x:point.x,y:point.y,w:aim.w/world.scale,h:aim.h/world.scale});if(record){photoCanvases[record.id]=world.photo(s,record);cancelAim();cameraLabel();toast('撮影しました。現像まで3秒。');}
 }
 function pause(reason='manual'){if(!s||s.status!=='playing')return;C.pause(s,reason);cancelAim();$('photo-view').hidden=true;pauseDialog();}
 function pauseDialog(){const disconnect=s.pauseReason==='controller';modal(`<h2>${disconnect?'コントローラーが外れました。':'ひとやすみ。'}</h2><p>残り ${time(s.remaining)} ／ カメラマン ${s.photographersFound.size} / 5人<br>住人も時計も止まっています。${disconnect?'<br>接続し直してボタンを押すと、再開できます。':''}</p><div class="actions">${s.photos.filter(p=>C.photoReady(s,p.id)).map(p=>`<button data-action="photo" data-id="${p.id}">写真 ${p.id+1}</button>`).join('')}</div>${buttons()}`);}
 function runnerAvailable(){return s?.mode!=='duo'||s.definition.area<=1||runnerReady&&runner&&!runner.closed&&performance.now()-runnerLast<3000;}
 function resume(){if(!s)return;if(!runnerAvailable()){modal('<h2>隠れる人の画面を開こう。</h2><p>専用画面をもう一度開くと、同じ街から続けられます。</p><div class="actions"><button data-action="runner">専用画面を開く</button><button data-action="leave">街をえらぶ</button></div>');return;}C.setPad(s,!!pad()||remoteInput?.connected&&performance.now()-remoteAt<500);if(!C.start(s)){toast('コントローラーを接続してください。');return;}close();last=performance.now();canvas.focus();}
 async function prepare(index){if(busy)return;const stage=D.stages[index];if(!stage.ready){modal('<h2>この街は制作中です。</h2><p>専用の原画と背景が揃い次第、遊べるようになります。</p><div class="actions"><button data-action="dismiss">戻る</button></div>');return;}
  if(mode()==='duo'&&stage.area>1&&(!runnerReady||!runner||runner.closed||performance.now()-runnerLast>=3000)){modal('<h2>隠れる人の画面を開こう。</h2><p>この街は画面より大きいため、隠れる側の専用画面を使います。画面を開き、別のディスプレイへ移動してください。</p><div class="actions"><button data-action="runner">専用画面を開く</button><button data-action="dismiss">戻る</button></div>');return;}
  busy=true;$('loading').hidden=false;try{s=C.create(D,index,Date.now()>>>0,mode());C.setPad(s,!!pad());await A.prepare(s,(n,total)=>{$('loading-progress').value=n/total;$('loading-text').textContent=`住人と街の画像 ${n} / ${total}`;});
   photoCanvases=[];shownPhotos.clear();resultShown=false;cancelAim();$('lobby').hidden=true;$('game').hidden=false;$('photo-view').hidden=true;world.resize();world.fit(s);world.lowEnvironment=$('quiet-environment').checked;
   const target=s.people[s.targetId];$('target-name').textContent=target.name;$('target-peek').classList.remove('expanded');A.portrait($('target-portrait'),target);cameraLabel();
   modal(`<span class="eyebrow">STAGE ${String(index+1).padStart(2,'0')} / 24</span><h2>この人を覚えてね。</h2><canvas class="dialog-portrait" id="ready-portrait" width="160" height="160"></canvas><p>${escape(target.name)}<br>${stage.population}人の街で、3分間のかくれんぼ。<br>カメラマンを見つけると写真を1枚撮れます。<br>${s.mode==='duo'?'隠れる人：左スティックで移動。行動ボタンで近くの設備を使えます。':'ドラッグで移動、ホイール・ピンチで拡大。'}<br><small>Esc・P：一時停止／C：カメラ</small></p><div class="actions"><button class="primary" data-action="begin">準備OK、はじめよう！</button><button data-action="leave">戻る</button></div>`);A.portrait($('ready-portrait'),target);world.draw(s);sendInit();
  }catch(e){modal(`<h2>街を開けませんでした。</h2><p>${escape(e.message)}</p><div class="actions"><button data-action="leave">戻る</button></div>`);}finally{busy=false;$('loading').hidden=true;}}
 function leave(){close();cancelAim();s=null;$('photo-view').hidden=true;$('game').hidden=true;$('lobby').hidden=false;if(document.fullscreenElement)document.exitFullscreen().catch(()=>{});stages();if(runner&&!runner.closed)runner.postMessage({type:'wacha-stop',token:runnerToken},'*');}
 function finish(){if(resultShown)return;resultShown=true;cancelAim();$('photo-view').hidden=true;const won=s.status==='won';if(won){const old=records[s.stage]?.best??Infinity;records[s.stage]={cleared:true,best:Math.min(old,s.elapsed)};try{localStorage.setItem('wacha-24-records',JSON.stringify(records));}catch{}}
  modal(`<span class="eyebrow">${s.mode==='duo'?'HIDE & SEEK':'A LITTLE DISCOVERY'}</span><h2>${won?'みーつけた！':s.mode==='duo'?'逃げきった！':'また、会いにいこう。'}</h2><canvas id="result-portrait" class="dialog-portrait" width="160" height="160"></canvas><p>${won?`${escape(s.people[s.targetId].name)}を発見！`:'3分間が終わりました。'}<br>${won?`発見まで ${time(s.elapsed)}`:'制限時間 03:00'} ／ お手つき ${s.mistakes}回</p><div class="actions"><button class="primary" data-action="retry">もう一度</button>${s.stage<23?'<button data-action="next">次の街へ</button>':''}<button data-action="leave">街をえらぶ</button></div>`);A.portrait($('result-portrait'),s.people[s.targetId]);}
 async function stages(){const cleared=Object.values(records).filter(r=>r.cleared).length;$('progress').textContent=`${cleared} / 24`;$('stage-grid').innerHTML=D.stages.map(stage=>`<button class="stage" data-action="stage" data-id="${stage.id}" aria-label="${escape(stage.name)} ${stage.population}人"><div class="art">${stage.ready?`<img data-background="${stage.background}" alt="${escape(stage.name)}" loading="lazy">`:'<span class="pending">原画を制作中</span>'}<span class="number">${String(stage.id+1).padStart(2,'0')}</span></div><div class="copy"><h3>${escape(stage.name)}</h3><p>${stage.population.toLocaleString()}人 · 3分間 · 広さ ${stage.area}倍</p><small>${records[stage.id]?.cleared?'✓ 発見済み　'+time(records[stage.id].best):stage.ready?'この街へ →':`専用原画 ${stage.castAvailable} / 100人`}</small></div></button>`).join('');
  const observer=new IntersectionObserver(entries=>{for(const e of entries)if(e.isIntersecting){const im=e.target;observer.unobserve(im);A.load(im.dataset.background).then(image=>im.src=image.src).catch(()=>{});}}, {rootMargin:'300px'});document.querySelectorAll('[data-background]').forEach(im=>observer.observe(im));}
 function help(){modal('<h2>街にまぎれた、ひとりを探そう。</h2><p>左上の見本と同じ人をクリックすると発見。見本はタッチで拡大できます。お手つきは3秒減ります。</p><p>写真は最初0枚。カメラマン5人をそれぞれ見つけると1回ずつ撮影できます。カメラで枠を出し、枠の中をドラッグして位置を決め、もう一度押すと撮影。3秒後、本人だけが写った写真を確認できます。</p><p>ふたりで遊ぶときはコントローラーを接続し、ボタンを押してください。左スティックで隠れる人を動かし、行動ボタンで設備を使います。広い街では専用画面を別のディスプレイに移動して遊びます。接続が外れると両者が一時停止します。</p><p>カメラの現像・確認中も、街と残り時間は進みます。</p><div class="actions"><button class="primary" data-action="dismiss">わかった！</button></div>');}
 async function collection(page=0){collectionPage=page;const list=D.characters.slice(page*32,page*32+32);modal(`<h2>街の住人ずかん</h2><p>${D.characters.length.toLocaleString()}種類の原画から。色違いはありません。</p><div class="collection-list">${list.map(c=>`<div><canvas data-person="${c.id}" width="96" height="96"></canvas>${escape(c.name)}</div>`).join('')}</div><div class="actions"><button data-action="collection-prev" ${page?'':'disabled'}>前へ</button><button data-action="collection-next" ${(page+1)*32<D.characters.length?'':'disabled'}>次へ</button><button data-action="dismiss">閉じる</button></div>`);await Promise.all([...new Set(list.map(c=>c.image))].map(A.load));document.querySelectorAll('[data-person]').forEach(el=>A.portrait(el,{design:el.dataset.person,height:1,activity:'acting',phase:0,facing:1}));}
 function openRunner(){runnerReady=false;runnerLast=0;remoteInput=null;remoteAt=0;runnerToken=Array.from(crypto.getRandomValues(new Uint32Array(4))).join('-');runner=window.open('index.html?view=runner#'+runnerToken,'wacha-runner','popup,width=1050,height=680');if(!runner){modal('<h2>専用画面を開けませんでした。</h2><p>ブラウザーのポップアップ許可を確認して、もう一度「隠れる人の画面を開く」を押してください。</p><div class="actions"><button data-action="dismiss">戻る</button></div>');}else close();}
 function sendInit(){if(!runnerReady||!s||!runner||runner.closed)return;runner.postMessage({type:'wacha-init',token:runnerToken,stage:s.stage,seed:s.seed,mode:s.mode,buttonIndex},'*');}
 window.addEventListener('message',e=>{const m=e.data;if(!m||typeof m!=='object')return;if(isRunner){if(e.source!==window.opener||m.token!==location.hash.slice(1))return;
   if(m.type==='wacha-init'){busy=true;buttonIndex=m.buttonIndex??0;s=C.create(D,m.stage,m.seed,m.mode);A.prepare(s).then(()=>{world.fit(s);busy=false;}).catch(err=>{busy=false;$('runner-banner').textContent=err.message;});}
   if(m.type==='wacha-state'&&s&&!busy){Object.assign(s,{elapsed:m.elapsed,status:m.status,remaining:m.remaining,people:m.people,sites:m.sites,rides:m.rides});const p=s.people[s.targetId];world.cx=p.x;world.cy=p.y;world.zoom=1.7;world.clamp();$('runner-banner').textContent=s.status==='playing'?'隠れる人の画面 · 左スティックで移動 ／ 行動ボタンで設備を使う':s.status==='won'?'みつかっちゃった！':s.status==='lost'?'逃げきった！':'ふたりとも一時停止中';}
   if(m.type==='wacha-stop'){s=null;$('runner-banner').textContent='探す人の画面で、街をえらんでください。';}
  }else{if(e.source!==runner||m.token!==runnerToken)return;if(m.type==='wacha-ready'){runnerReady=true;runnerLast=performance.now();sendInit();if(s?.status==='paused')pauseDialog();}if(m.type==='wacha-input'){remoteInput=m.input;remoteAt=runnerLast=performance.now();}if(m.type==='wacha-goodbye'){runnerReady=false;if(s?.mode==='duo'&&s.definition.area>1)pause('runner');}}});
 document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;const a=b.dataset.action;if(a==='stage')prepare(Number(b.dataset.id));else if(a==='begin'){if(!runnerAvailable()){resume();return;}C.setPad(s,!!pad()||!!remoteInput?.connected&&performance.now()-remoteAt<500);if(C.start(s)){document.documentElement.requestFullscreen?.().catch(()=>{});close();last=performance.now();canvas.focus();}else toast('コントローラーをつなぎ、ボタンを押してください。');}else if(a==='resume')resume();else if(a==='leave')leave();else if(a==='dismiss')close();else if(a==='retry'){const n=s.stage;close();prepare(n);}else if(a==='next'){const n=s.stage+1;close();prepare(n);}else if(a==='photo'){resume();if(s.status==='playing')photoOpen(Number(b.dataset.id));}else if(a==='runner')openRunner();else if(a==='collection-prev')collection(collectionPage-1);else if(a==='collection-next')collection(collectionPage+1);});
 $('help-button').onclick=help;$('collection-open').onclick=()=>collection();$('runner-open').onclick=openRunner;$('action-button').onchange=e=>{buttonIndex=Number(e.target.value);try{localStorage.setItem('wacha-action-button',String(buttonIndex));}catch{}};
 document.querySelectorAll('input[name=mode]').forEach(el=>el.onchange=()=>{$('controller-options').hidden=mode()!=='duo';});$('camera-button').onclick=camera;$('camera-cancel').onclick=cancelAim;$('pause-button').onclick=()=>pause();$('photo-close').onclick=()=>{$('photo-view').hidden=true;};$('target-peek').onclick=()=>{const expanded=$('target-peek').classList.toggle('expanded');$('target-peek').setAttribute('aria-expanded',String(expanded));};
 const pointers=new Map();let pinch=null;
 canvas.addEventListener('pointerdown',e=>{if(!s||s.status!=='playing')return;canvas.setPointerCapture(e.pointerId);pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===2){const [a,b]=[...pointers.values()];pinch={distance:Math.hypot(a.x-b.x,a.y-b.y),x:(a.x+b.x)/2,y:(a.y+b.y)/2};if(drag)drag.moved=true;return;}
  drag={id:e.pointerId,x:e.clientX,y:e.clientY,startX:e.clientX,startY:e.clientY,moved:false,camera:!!aim};});
 canvas.addEventListener('pointermove',e=>{if(!pointers.has(e.pointerId))return;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===2&&pinch&&!aim){const [a,b]=[...pointers.values()],dist=Math.hypot(a.x-b.x,a.y-b.y),x=(a.x+b.x)/2,y=(a.y+b.y)/2;world.zoomAt(dist/Math.max(1,pinch.distance),x,y);world.pan(x-pinch.x,y-pinch.y);pinch={distance:dist,x,y};return;}
  if(!drag||drag.id!==e.pointerId)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(Math.hypot(e.clientX-drag.startX,e.clientY-drag.startY)>5)drag.moved=true;if(drag.camera&&aim){aim.x=Math.max(0,Math.min(world.width-aim.w,aim.x+dx));aim.y=Math.max(0,Math.min(world.height-aim.h,aim.y+dy));positionAim();}else if(drag.moved)world.pan(dx,dy);drag.x=e.clientX;drag.y=e.clientY;});
 function pointerEnd(e){pointers.delete(e.pointerId);if(pinch){pinch=null;if(drag)drag.moved=true;}if(drag?.id!==e.pointerId)return;const click=!drag.moved&&!drag.camera;drag=null;if(click&&s?.status==='playing'){const id=world.hit(s,e.clientX,e.clientY);if(id!==null){const result=C.touch(s,id);if(result==='photographer'){toast('カメラマン発見！ 写真が1枚増えました。');cameraLabel();}else if(result==='used')toast('このカメラマンの写真は受け取り済みです。');else if(result==='wrong')toast('お手つき！ −3秒',true);}}}
 canvas.addEventListener('pointerup',pointerEnd);canvas.addEventListener('pointercancel',()=>{pointers.clear();pinch=null;drag=null;});canvas.addEventListener('wheel',e=>{e.preventDefault();if(!aim)world.zoomAt(Math.exp(-e.deltaY*.001),e.clientX,e.clientY);},{passive:false});
 document.addEventListener('keydown',e=>{if(isRunner)return;if(e.code==='Escape'){e.preventDefault();if(!$('photo-view').hidden){$('photo-view').hidden=true;return;}if(aim){cancelAim();return;}if(s?.status==='playing')pause();else if(s?.status==='paused')resume();return;}if(!s||dialog.open)return;if(e.code==='KeyC')camera();else if(e.code==='KeyP')pause();else if(e.code==='Digit0')world.fit();else if(['Equal','NumpadAdd'].includes(e.code))world.zoomAt(1.18);else if(['Minus','NumpadSubtract'].includes(e.code))world.zoomAt(1/1.18);else if(e.code.startsWith('Arrow')){e.preventDefault();world.pan(e.code==='ArrowLeft'?60:e.code==='ArrowRight'?-60:0,e.code==='ArrowUp'?60:e.code==='ArrowDown'?-60:0);}});
 dialog.addEventListener('cancel',e=>{e.preventDefault();if(s?.status==='paused')resume();else if(!s)close();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&!isRunner)pause('background');});window.addEventListener('resize',()=>{world.resize();cancelAim();});
 window.addEventListener('beforeunload',()=>{if(isRunner)window.opener?.postMessage({type:'wacha-goodbye',token:location.hash.slice(1)},'*');});
 if(isRunner){world.runnerView=true;$('lobby').hidden=true;$('game').hidden=false;for(const id of ['target-peek','camera-button','pause-button'])$(id).hidden=true;const banner=document.createElement('div');banner.id='runner-banner';banner.className='runner-banner';banner.textContent='探す人の画面で、街をえらんでください。';document.body.append(banner);world.resize();window.opener?.postMessage({type:'wacha-ready',token:location.hash.slice(1)},'*');}else{stages();A.load('cover').then(im=>$('cover').src=im.src).catch(()=>{});}
 function tick(now){requestAnimationFrame(tick);const dt=Math.min(.3,(now-last)/1000);last=now;const gamepad=pad(),v=gamepad?{x:gamepad.axes[0]||0,y:gamepad.axes[1]||0,act:gamepad.buttons[buttonIndex]?.pressed||false,connected:true}:{x:0,y:0,act:false,connected:false};
  if(isRunner){window.opener?.postMessage({type:'wacha-input',token:location.hash.slice(1),input:v},'*');if(s&&!busy)world.draw(s);return;}
  if(!s){$('pad-status').textContent=gamepad?`接続しました：${gamepad.id}`:'コントローラーをつなぎ、ボタンを押してください。';return;}
  const remoteFresh=performance.now()-remoteAt<400&&remoteInput;const input=s.mode==='duo'&&s.definition.area>1&&remoteFresh?.connected?remoteFresh:gamepad?v:remoteFresh||v;if(s.mode==='duo'){const before=s.status;C.setPad(s,input.connected);if(before==='playing'&&s.status==='paused')pauseDialog();C.input(s,input.x,input.y,input.act);if(s.definition.area>1&&runnerReady&&(runner?.closed||now-runnerLast>3000)){runnerReady=false;pause('runner');}}
  if(busy)return;C.step(s,dt);world.draw(s);A.portrait($('target-portrait'),s.people[s.targetId]);cameraLabel();for(const photo of s.photos)if(C.photoReady(s,photo.id)&&!shownPhotos.has(photo.id)){shownPhotos.add(photo.id);if(s.status==='playing')photoOpen(photo.id);}if(s.status==='won'||s.status==='lost')finish();
  if(runnerReady&&runner&&!runner.closed&&now-lastBroadcast>66){lastBroadcast=now;runner.postMessage({type:'wacha-state',token:runnerToken,elapsed:s.elapsed,status:s.status,remaining:s.remaining,people:s.people,sites:s.sites,rides:s.rides||[]},'*');}
 }
 requestAnimationFrame(tick);
 window.Wacha24Debug={get state(){return s;},get world(){return world;},prepare,pause,resume,camera,get aiming(){return aim;},get photoCanvases(){return photoCanvases;}};
})();
